// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	CaptchaId  string `json:"captchaId"   label:"验证码id"`
	VerifyCode string `json:"verifyCode"  label:"验证码"`
	Account    string `json:"account"     validate:"required,min=2,max=17" label:"账号"`
	Password   string `json:"password"    label:"密码"`
}

type LoginResp struct {
	Token string `json:"token"`
}

type UserInfoResp struct {
	Username       string `json:"username"`
	Avatar         string `json:"avatar"`
	IsInitPassport bool   `json:"isInitPassport"` // 是否为初始化密码
}

type UserProfileInfoResp struct {
	Username string `json:"username"`
	Nickname string `json:"nickname"`
	Gender   int64  `json:"gender"`
	Email    string `json:"email"`
	Mobile   string `json:"mobile"`
	Remark   string `json:"remark"`
	Avatar   string `json:"avatar"`
}

type UpdateProfileReq struct {
	Username string `json:"username"  validate:"required,min=2,max=12"   label:"姓名"`
	Nickname string `json:"nickname"  validate:"omitempty,min=2,max=12"  label:"昵称"`
	Gender   int64  `json:"gender"    validate:"gte=0,lte=2"             label:"性别"`
	Email    string `json:"email"     validate:"omitempty,email"         label:"邮箱"`
	Mobile   string `json:"mobile"    validate:"len=11"                  label:"手机号"`
	Avatar   string `json:"avatar"    validate:"required,url"            label:"头像"`
}

type Menu struct {
	Id           int64  `json:"id"`
	ParentId     int64  `json:"parentId"`
	Name         string `json:"name"`
	Router       string `json:"router"`
	Type         int64  `json:"type"`
	Icon         string `json:"icon"`
	OrderNum     int64  `json:"orderNum"`
	ViewPath     string `json:"viewPath"`
	IsShow       int64  `json:"isShow"`
	ActiveRouter string `json:"activeRouter"`
}

type UserPermMenuResp struct {
	Menus []Menu   `json:"menus"`
	Perms []string `json:"perms"`
}

type UpdatePasswordReq struct {
	OldPassword string `json:"oldPassword"  validate:"min=6,max=20"  label:"旧密码"`
	NewPassword string `json:"newPassword"  validate:"min=6,max=20"  label:"新密码"`
}

type LoginCaptchaResp struct {
	CaptchaId  string `json:"captchaId"`
	VerifyCode string `json:"verifyCode"`
}

type GenerateAvatarResp struct {
	AvatarUrl string `json:"avatarUrl"`
}

type PermMenu struct {
	Id           int64    `json:"id"`
	ParentId     int64    `json:"parentId"`
	Name         string   `json:"name"`
	Router       string   `json:"router"`
	Perms        []string `json:"perms"`
	Type         int64    `json:"type"`
	Icon         string   `json:"icon"`
	OrderNum     int64    `json:"orderNum"`
	ViewPath     string   `json:"viewPath"`
	IsShow       int64    `json:"isShow"`
	ActiveRouter string   `json:"activeRouter"`
	Has          int64    `json:"has"`
}

type SysPermMenuListResp struct {
	List []PermMenu `json:"list"`
}

type AddSysPermMenuReq struct {
	ParentId     int64    `json:"parentId"      validate:"number,gte=0"           label:"父级菜单id"`
	Name         string   `json:"name"          validate:"min=2,max=50"           label:"菜单名称"`
	Router       string   `json:"router"        validate:"omitempty,max=1024"     label:"路由"`
	Perms        []string `json:"perms"         validate:"omitempty,unique"       label:"权限"`
	Type         int64    `json:"type"          validate:"number,gte=0,lte=2"     label:"类型"`
	Icon         string   `json:"icon"          validate:"omitempty,max=200"      label:"图标"`
	OrderNum     int64    `json:"orderNum"      validate:"number,gte=0,lte=9999"  label:"排序"`
	ViewPath     string   `json:"viewPath"      validate:"omitempty,max=1024"     label:"视图路径"`
	IsShow       int64    `json:"isShow"        validate:"number,gte=0,lte=1"     label:"显示状态"`
	ActiveRouter string   `json:"activeRouter"  validate:"omitempty,max=1024"     label:"激活路由"`
}

type DeleteSysPermMenuReq struct {
	Id int64 `json:"id"  validate:"number,gte=1" label:"菜单id"`
}

type UpdateSysPermMenuReq struct {
	Id           int64    `json:"id"            validate:"number,gte=1"           label:"菜单id"`
	ParentId     int64    `json:"parentId"      validate:"number,gte=0"           label:"父级菜单id"`
	Name         string   `json:"name"          validate:"min=2,max=50"           label:"菜单名称"`
	Router       string   `json:"router"        validate:"omitempty,max=1024"     label:"路由"`
	Perms        []string `json:"perms"         validate:"omitempty,unique"       label:"权限"`
	Type         int64    `json:"type"          validate:"number,gte=0,lte=2"     label:"类型"`
	Icon         string   `json:"icon"          validate:"omitempty,max=200"      label:"图标"`
	OrderNum     int64    `json:"orderNum"      validate:"number,gte=0,lte=9999"  label:"排序"`
	ViewPath     string   `json:"viewPath"      validate:"omitempty,max=1024"     label:"视图路径"`
	IsShow       int64    `json:"isShow"        validate:"number,gte=0,lte=1"     label:"显示状态"`
	ActiveRouter string   `json:"activeRouter"  validate:"omitempty,max=1024"     label:"激活路由"`
}

type PageReq struct {
	Page  int64 `form:"page,optional"  validate:"number,gte=1"  label:"页数"`
	Limit int64 `form:"limit,optional" validate:"number,gte=1"  label:"条数"`
}

type Pagination struct {
	Page  int64 `json:"page"`
	Limit int64 `json:"limit"`
	Total int64 `json:"total"`
}

type TimeFilter struct {
	StartTime string `form:"startTime,optional" validate:"datetime" label:"开始时间"`
	EndTime   string `form:"endTime,optional"   validate:"datetime" label:"结束时间"`
}

type UserInfo struct {
	Id       int64  `json:"id"`
	Username string `json:"username"`
}

type Result struct {
	Result bool `json:"result"` // 结果是否成功
}

type Role struct {
	Id          int64   `json:"id"`
	ParentId    int64   `json:"parentId"`
	Name        string  `json:"name"`
	UniqueKey   string  `json:"uniqueKey"`
	PermMenuIds []int64 `json:"permMenuIds"`
	Remark      string  `json:"remark"`
	Status      int64   `json:"status"`
	OrderNum    int64   `json:"orderNum"`
}

type SysRoleListResp struct {
	List []Role `json:"list"`
}

type AddSysRoleReq struct {
	ParentId    int64   `json:"parentId"     validate:"number,gte=0"          label:"父级角色id"`
	Name        string  `json:"name"         validate:"min=2,max=50"          label:"角色名称"`
	UniqueKey   string  `json:"uniqueKey"    validate:"min=2,max=50"          label:"角色标识"`
	PermMenuIds []int64 `json:"permMenuIds"  validate:"omitempty,unique"      label:"权限ids"`
	Remark      string  `json:"remark"       validate:"max=200"               label:"备注"`
	Status      int64   `json:"status"       validate:"number,gte=0,lte=1"    label:"状态"`
	OrderNum    int64   `json:"orderNum"     validate:"number,gte=0,lte=9999" label:"排序"`
}

type DeleteSysRoleReq struct {
	Id int64 `json:"id"  validate:"number,gte=2" label:"角色id"`
}

type UpdateSysRoleReq struct {
	Id          int64   `json:"id"           validate:"number,gte=1"           label:"角色id"`
	ParentId    int64   `json:"parentId"     validate:"number,gte=0"           label:"父级角色id"`
	Name        string  `json:"name"         validate:"min=2,max=50"           label:"角色名称"`
	UniqueKey   string  `json:"uniqueKey"    validate:"min=2,max=50"           label:"角色标识"`
	PermMenuIds []int64 `json:"permMenuIds"  validate:"omitempty,unique"       label:"权限ids"`
	Remark      string  `json:"remark"       validate:"max=200"                label:"备注"`
	Status      int64   `json:"status"       validate:"number,gte=0,lte=1"     label:"状态"`
	OrderNum    int64   `json:"orderNum"     validate:"number,gte=0,lte=9999"  label:"排序"`
}

type Dept struct {
	Id        int64  `json:"id"`
	ParentId  int64  `json:"parentId"`
	Name      string `json:"name"`
	FullName  string `json:"fullName"`
	UniqueKey string `json:"uniqueKey"`
	Type      int64  `json:"type"`
	Status    int64  `json:"status"`
	OrderNum  int64  `json:"orderNum"`
	Remark    string `json:"remark"`
}

type SysDeptListResp struct {
	List []Dept `json:"list"`
}

type AddSysDeptReq struct {
	ParentId  int64  `json:"parentId"   validate:"number,gte=0"            label:"父级部门id"`
	Name      string `json:"name"       validate:"min=2,max=50"            label:"部门名称"`
	FullName  string `json:"fullName"   validate:"omitempty,min=2,max=50"  label:"部门全称"`
	UniqueKey string `json:"uniqueKey"  validate:"min=2,max=50"            label:"部门标识"`
	Type      int64  `json:"type"       validate:"number,gte=1,lte=3"      label:"部门类型"`
	Status    int64  `json:"status"     validate:"number,gte=0,lte=1"      label:"状态"`
	OrderNum  int64  `json:"orderNum"   validate:"number,gte=0,lte=9999"   label:"排序"`
	Remark    string `json:"remark"     validate:"max=200"                 label:"备注"`
}

type DeleteSysDeptReq struct {
	Id int64 `json:"id"  validate:"number,gte=1" label:"部门id"`
}

type UpdateSysDeptReq struct {
	Id        int64  `json:"id"         validate:"number,gte=1"            label:"部门id"`
	ParentId  int64  `json:"parentId"   validate:"number,gte=0"            label:"父级部门id"`
	Name      string `json:"name"       validate:"min=2,max=50"            label:"部门名称"`
	FullName  string `json:"fullName"   validate:"omitempty,min=2,max=50"  label:"部门全称"`
	UniqueKey string `json:"uniqueKey"  validate:"min=2,max=50"            label:"部门标识"`
	Type      int64  `json:"type"       validate:"number,gte=1,lte=3"      label:"部门类型"`
	Status    int64  `json:"status"     validate:"number,gte=0,lte=1"      label:"状态"`
	OrderNum  int64  `json:"orderNum"   validate:"number,gte=0,lte=9999"   label:"排序"`
	Remark    string `json:"remark"     validate:"max=200"                 label:"备注"`
}

type Job struct {
	Id       int64  `json:"id"`
	Name     string `json:"name"`
	Status   int64  `json:"status"`
	OrderNum int64  `json:"orderNum"`
}

type SysJobPageReq struct {
	PageReq
}

type SysJobPageResp struct {
	List       []Job      `json:"list"`
	Pagination Pagination `json:"pagination"`
}

type AddSysJobReq struct {
	Name     string `json:"name"      validate:"min=2,max=50"           label:"岗位名称"`
	Status   int64  `json:"status"    validate:"number,gte=0,lte=1"     label:"状态"`
	OrderNum int64  `json:"orderNum"  validate:"number,gte=0,lte=9999"  label:"排序"`
}

type DeleteSysJobReq struct {
	Id int64 `json:"id"  validate:"number,gte=1" label:"岗位id"`
}

type UpdateSysJobReq struct {
	Id       int64  `json:"id"        validate:"number,gte=1"           label:"岗位id"`
	Name     string `json:"name"      validate:"min=2,max=50"           label:"岗位名称"`
	Status   int64  `json:"status"    validate:"number,gte=0,lte=1"     label:"状态"`
	OrderNum int64  `json:"orderNum"  validate:"number,gte=0,lte=9999"  label:"排序"`
}

type Profession struct {
	Id       int64  `json:"id"`
	Name     string `json:"name"`
	Status   int64  `json:"status"`
	OrderNum int64  `json:"orderNum"`
}

type SysProfessionPageReq struct {
	PageReq
}

type SysProfessionPageResp struct {
	List       []Profession `json:"list"`
	Pagination Pagination   `json:"pagination"`
}

type AddSysProfessionReq struct {
	Name     string `json:"name"      validate:"min=2,max=50"           label:"职称"`
	Status   int64  `json:"status"    validate:"number,gte=0,lte=1"     label:"状态"`
	OrderNum int64  `json:"orderNum"  validate:"number,gte=0,lte=9999"  label:"排序"`
}

type DeleteSysProfessionReq struct {
	Id int64 `json:"id"  validate:"number,gte=1" label:"职称id"`
}

type UpdateSysProfessionReq struct {
	Id       int64  `json:"id"        validate:"number,gte=1"           label:"职称id"`
	Name     string `json:"name"      validate:"min=2,max=50"           label:"职称"`
	Status   int64  `json:"status"    validate:"number,gte=0,lte=1"     label:"状态"`
	OrderNum int64  `json:"orderNum"  validate:"number,gte=0,lte=9999"  label:"排序"`
}

type UserProfession struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
}

type UserJob struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
}

type UserDept struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
}

type UserRole struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
}

type User struct {
	Id         int64          `json:"id"`
	Account    string         `json:"account"`
	Username   string         `json:"username"`
	Nickname   string         `json:"nickname"`
	Gender     int64          `json:"gender"`
	Email      string         `json:"email"`
	Mobile     string         `json:"mobile"`
	Profession UserProfession `json:"profession"`
	Job        UserJob        `json:"job"`
	Dept       UserDept       `json:"dept"`
	Roles      []UserRole     `json:"roles"`
	Status     int64          `json:"status"`
	OrderNum   int64          `json:"orderNum"`
	Remark     string         `json:"remark"`
}

type SysUserPageReq struct {
	PageReq
	DeptId int64 `form:"deptId"  validate:"number,gte=0" label:"部门id"`
}

type SysUserPageResp struct {
	List       []User     `json:"list"`
	Pagination Pagination `json:"pagination"`
}

type AddSysUserReq struct {
	Account      string  `json:"account"       validate:"min=4,max=50"            label:"账号"`
	Username     string  `json:"username"      validate:"min=2,max=50"            label:"姓名"`
	Nickname     string  `json:"nickname"      validate:"omitempty,min=2,max=50"  label:"昵称"`
	Gender       int64   `json:"gender"        validate:"number,gte=0,lte=2"      label:"性别"`
	Email        string  `json:"email"         validate:"omitempty,email"         label:"邮箱"`
	Mobile       string  `json:"mobile"        validate:"omitempty,min=11"        label:"手机号"`
	ProfessionId int64   `json:"professionId"  validate:"number,gte=1"            label:"职称id"`
	JobId        int64   `json:"jobId"         validate:"number,gte=1"            label:"岗位id"`
	DeptId       int64   `json:"deptId"        validate:"number,gte=1"            label:"部门id"`
	RoleIds      []int64 `json:"roleIds"       validate:"unique"                  label:"角色ids"`
	Status       int64   `json:"status"        validate:"number,gte=0,lte=1"      label:"状态"`
	OrderNum     int64   `json:"orderNum"      validate:"number,gte=0,lte=9999"   label:"排序"`
	Remark       string  `json:"remark"        validate:"max=200"                 label:"备注"`
}

type DeleteSysUserReq struct {
	Id int64 `json:"id"  validate:"number,gte=2" label:"用户id"`
}

type UpdateSysUserReq struct {
	Id           int64   `json:"id"            validate:"number,gte=2"            label:"用户id"`
	Username     string  `json:"username"      validate:"min=2,max=50"            label:"姓名"`
	Nickname     string  `json:"nickname"      validate:"omitempty,min=2,max=50"  label:"昵称"`
	Gender       int64   `json:"gender"        validate:"number,gte=0,lte=2"      label:"性别"`
	Email        string  `json:"email"         validate:"omitempty,email"         label:"邮箱"`
	Mobile       string  `json:"mobile"        validate:"omitempty,min=11"        label:"手机号"`
	ProfessionId int64   `json:"professionId"  validate:"number,gte=1"            label:"职称id"`
	JobId        int64   `json:"jobId"         validate:"number,gte=1"            label:"岗位id"`
	DeptId       int64   `json:"deptId"        validate:"number,gte=1"            label:"部门id"`
	RoleIds      []int64 `json:"roleIds"       validate:"unique"                  label:"角色ids"`
	Status       int64   `json:"status"        validate:"number,gte=0,lte=1"      label:"状态"`
	OrderNum     int64   `json:"orderNum"      validate:"number,gte=0,lte=9999"   label:"排序"`
	Remark       string  `json:"remark"        validate:"max=200"                 label:"备注"`
}

type UpdateSysUserPasswordReq struct {
	Id       int64  `json:"id"        validate:"number,gte=2"  label:"用户id"`
	Password string `json:"password"  validate:"min=6,max=20"  label:"密码"`
}

type GetSysUserRdpjInfoReq struct {
	UserId int64 `form:"userId"  validate:"number,gte=0"  label:"用户id"`
}

type Rdpj struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
}

type DeptTree struct {
	Id       int64  `json:"id"`
	ParentId int64  `json:"parentId"`
	Name     string `json:"name"`
}

type RoleTree struct {
	Id       int64  `json:"id"`
	ParentId int64  `json:"parentId"`
	Name     string `json:"name"`
	Has      int64  `json:"has"`
}

type GetSysUserRdpjInfoResp struct {
	Role       []RoleTree `json:"role"`
	Dept       []DeptTree `json:"dept"`
	Profession []Rdpj     `json:"profession"`
	Job        []Rdpj     `json:"job"`
}

type ConfigDict struct {
	Id        int64  `json:"id"`
	ParentId  int64  `json:"parentId"`
	Name      string `json:"name"`
	Type      int64  `json:"type"`
	UniqueKey string `json:"uniqueKey"`
	Value     string `json:"value"`
	OrderNum  int64  `json:"orderNum"`
	Remark    string `json:"remark"`
	Status    int64  `json:"status"`
}

type ConfigDictListResp struct {
	List []ConfigDict `json:"list"`
}

type ConfigDictPageReq struct {
	PageReq
	ParentId int64 `form:"parentId"  validate:"number,gte=0" label:"字典集id"`
}

type ConfigDictPageResp struct {
	List       []ConfigDict `json:"list"`
	Pagination Pagination   `json:"pagination"`
}

type AddConfigDictReq struct {
	ParentId  int64  `json:"parentId"   validate:"number,gte=0"         label:"字典集id"`
	Name      string `json:"name"       validate:"min=2,max=50"         label:"名称"`
	Type      int64  `json:"type"       validate:"number,gte=1,lte=12"  label:"类型"`
	UniqueKey string `json:"uniqueKey"  validate:"min=2,max=50"         label:"标识"`
	Value     string `json:"value"      validate:"max=2048"             label:"字典项值"`
	OrderNum  int64  `json:"orderNum"   validate:"gte=0,lte=9999"       label:"排序"`
	Remark    string `json:"remark"     validate:"max=200"              label:"备注"`
	Status    int64  `json:"status"     validate:"number,gte=0,lte=1"   label:"状态"`
}

type DeleteConfigDictReq struct {
	Id int64 `json:"id"  validate:"number,gte=1" label:"字典id"`
}

type UpdateConfigDictReq struct {
	Id       int64  `json:"id"         validate:"number,gte=1"         label:"字典id"`
	ParentId int64  `json:"parentId"   validate:"number,gte=0"         label:"字典集id"`
	Name     string `json:"name"       validate:"min=2,max=50"         label:"名称"`
	Type     int64  `json:"type"       validate:"number,gte=1,lte=12"  label:"类型"`
	Value    string `json:"value"      validate:"max=2048"             label:"字典项值"`
	OrderNum int64  `json:"orderNum"   validate:"gte=0,lte=9999"       label:"排序"`
	Remark   string `json:"remark"     validate:"max=200"              label:"备注"`
	Status   int64  `json:"status"     validate:"number,gte=0,lte=1"   label:"状态"`
}

type LogLogin struct {
	Id         int64  `json:"id"`
	Account    string `json:"account"`
	Ip         string `json:"ip"`
	Uri        string `json:"uri"`
	Status     int64  `json:"status"`
	CreateTime string `json:"createTime"`
}

type LogLoginPageReq struct {
	PageReq
}

type LogLoginPageResp struct {
	List       []LogLogin `json:"list"`
	Pagination Pagination `json:"pagination"`
}

type MemberInfo struct {
	BaseUserId int64           `json:"baseUserId"` // 主用户ID
	UserNo     string          `json:"userNo"`     // 用户编号
	Phone      string          `json:"phone"`      // 手机号
	Product    int64           `json:"product"`    // 产品线 0.辞源 1.AI搜索 2.白帝辞 3.智普乌托邦(1001~1002) 4.豆子机器人
	Source     int64           `json:"source"`     // 首次来源 100.提审标记 0.APP 1.豆伴匠 2.风的颜色 1001.听力熊 1002.微软
	Status     int64           `json:"status"`     // 状态 0.正常 1.冻结 2.注销
	Remark     string          `json:"remark"`     // 备注
	SubList    []MemberSubInfo `json:"list"`       // 子用户列表
	CreatedAt  int64           `json:"createdAt"`  // 创建时间
	UpdatedAt  int64           `json:"updatedAt"`  // 最近登录时间
	RecentlyAt int64           `json:"recentlyAt"` // 子用户最近一次登录时间
}

type MemberSubInfo struct {
	BaseUserId     int64  `json:"baseUserId"`     // 主用户ID
	UserId         int64  `json:"userId"`         // 用户ID
	RoleType       int64  `json:"role"`           // 角色类型 1.孩子[默认] 2.家长
	Nickname       string `json:"nickname"`       // 昵称
	RealName       string `json:"realName"`       // 姓名
	Avatar         string `json:"avatar"`         // 头像
	Gender         int64  `json:"gender"`         // 性别 0.未知 1.男 2.女
	Grade          int64  `json:"grade"`          // 年级 10.学龄前 11.一年级 12.二年级 13.三年级 14.四年级 15.五年级 16.六年级 20.中小衔接 21.初一 22.初二 23.初三 31.高一 32.高二 33.高三 41.大学语文 42.中文专业 43.文学专家
	Birthday       string `json:"birthday"`       // 生日[年月日]
	Region         string `json:"region"`         // 地区
	IsInfoFinished int64  `json:"isInfoFinished"` // 是否完善信息 1.未完善 2.已完善
	VipName        string `json:"vipName"`        // 会员名称
	VipType        int64  `json:"vipType"`        // 会员类型 1.豆神会员（基础版） 2.豆神会员（典藏版） 3.豆神超级会员 4.豆神会员（特别版）
	IsVipValid     bool   `json:"isVipValid"`     // 会员是否到期
	VipEndTime     int64  `json:"vipEndTime"`     // 会员过期时间
	Status         int64  `json:"status"`         // 状态 0.正常 1.冻结 2.注销
	Remark         string `json:"remark"`         // 备注
	CreatedAt      int64  `json:"createdAt"`      // 创建时间
	UpdatedAt      int64  `json:"updatedAt"`      // 更新时间
	TencentLogURL  string `json:"tencentLogURL"`  // 腾讯云日志URL
}

type MemberListReq struct {
	Id      string `form:"baseUserId,optional"` // 主用户ID
	UserId  string `form:"userId,optional"`     // 子用户ID
	Phone   string `form:"phone,optional"`      // 手机号
	Product string `form:"product,optional"`    // 产品线 0.辞源 1.AI搜索 2.白帝辞 3.智普乌托邦(1001~1002) 4.豆子机器人
	Source  string `form:"source,optional"`     // 首次登录 100.提审标记 0.APP 1.豆伴匠 2.风的颜色 1001.听力熊 1002.微软
	Status  string `form:"status,optional"`     // 账号状态 0.正常 1.冻结 2.注销
	PageReq
}

type MemberListResp struct {
	List       []MemberInfo `json:"list"`
	Pagination Pagination   `json:"pagination"`
}

type MemberGetPhoneReq struct {
	BaseUserId int64 `form:"baseUserId"`
}

type MemberGetPhoneResp struct {
	Phone int64 `json:"phone"`
}

type MemberLogOffReq struct {
	UserId int64 `json:"userId"`
}

type MemberLogOffResp struct {
	Result bool `json:"result"`
}

type MemberDetailReq struct {
	UserId int64 `form:"userId"`
}

type MemberEditReq struct {
	UserId   int64  `json:"userId"`
	Name     string `json:"name"`               // 姓名
	Grade    int64  `json:"grade,range=[1:13]"` // 年级
	Gender   int64  `json:"gender,options=1|2"` // 性别
	Province int64  `json:"province"`           // 省
	City     int64  `json:"city,default=0"`     // 市 默认0
}

type MemberEditResp struct {
	Result bool `json:"result"`
}

type ExportMemberReq struct {
	MemberListReq
	ExportType int64 `form:"exportType"` // 是否导出 1.导出所有 2.导出本页
}

type ExportMemberResp struct {
	Url string `json:"url"` // 导出文件地址
}

type GetRoleListReq struct {
	Phone   string `form:"phone"`   // 手机号
	Product int64  `form:"product"` // 产品线 0.辞源 1.AI搜索 2.白帝辞 3.智普乌托邦(1001~1002) 4.豆子机器人
}

type GetRoleListResp struct {
	List []MemberSubInfo `json:"list"` // 角色列表
}

type WhiteListReq struct {
	Phone     string `form:"phone,optional"`     // 手机号
	StartTime string `form:"startTime,optional"` // 开始时间
	EndTime   string `form:"endTime,optional"`   // 结束时间
	Product   string `form:"product,optional"`   // 产品线 0.辞源 1.AI搜索 2.白帝辞 3.智普乌托邦(1001~1002) 4.豆子机器人
	Source    string `form:"source,optional"`    // 首次登录 100.提审标记 0.APP 1.豆伴匠 2.风的颜色 1001.听力熊 1002.微软
	Status    string `form:"status,optional"`    // 账号状态 0.正常 1.冻结 2.注销
	Remark    string `form:"remark,optional"`    // 备注
	PageReq
}

type WhiteListResp struct {
	List       []WhiteInfo `json:"list"`
	Pagination Pagination  `json:"pagination"`
}

type WhiteInfo struct {
	Id        int64  `json:"id"`        // ID
	Phone     string `json:"phone"`     // 手机号
	StartTime int64  `json:"startTime"` // 开始时间
	EndTime   int64  `json:"endTime"`   // 结束时间
	Product   int64  `json:"product"`   // 产品线 0.辞源 1.AI搜索 2.白帝辞 3.智普乌托邦(1001~1002) 4.豆子机器人
	Source    int64  `json:"source"`    // 首次来源 100.提审标记 0.APP 1.豆伴匠 2.风的颜色 1001.听力熊 1002.微软
	Status    int64  `json:"status"`    // 状态 1.正常 2.失效
	Remark    string `json:"remark"`    // 备注
	CreatedAt int64  `json:"createdAt"` // 创建时间
	UpdatedAt int64  `json:"updatedAt"` // 修改时间
}

type WhiteEditReq struct {
	Id      int64    `json:"id,optional" validate:"number"       label:"用户ID"`
	Phone   string   `json:"phone"                               label:"手机号"`
	Date    []string `json:"date"        validate:"len=2"        label:"生效时间"`
	Product int64    `json:"product"     validate:"number,gte=0" label:"产品线"`
	Source  int64    `json:"source"      validate:"number,gte=0" label:"来源"`
	Status  int64    `json:"status"      validate:"number,gt=0"  label:"状态"`
	Remark  string   `json:"remark,optional"                     label:"备注"`
}

type WhiteDeleteReq struct {
	Id int64 `json:"id"`
}

type ImportFileInfo struct {
	Filename      string `json:"fileName"`      // 文件名称
	FileId        string `json:"fileId"`        // 文件ID
	Type          int64  `json:"type"`          // 导入类别 1.权益发放 2.题库新增
	FileSheet     int64  `json:"fileSheet"`     // 文件表下标
	FileSheetName string `json:"fileSheetName"` // 文件表名称
}

type TaskDetailLog struct {
	Index     int64  `json:"index"`     // 数据下标
	Data      string `json:"data"`      // 数据内容
	Status    int64  `json:"status"`    // 当前状态 0.未开始 1.进行中 2.已完成 3.失败
	ErrorsMsg string `json:"errorsMsg"` // 错误信息
}

type TaskListInfo struct {
	Id int64 `json:"id"` // 任务ID
	ImportFileInfo
	Status      int64  `json:"status"`      // 任务状态 0.未开始 1.进行中 2.已完成 3.失败
	StartTime   string `json:"startTime"`   // 任务执行开始时间
	EndTime     string `json:"endTime"`     // 任务执行结束时间
	ErrorsMsg   string `json:"errorsMsg"`   // 错误信息
	Total       int64  `json:"total"`       // 总条数
	FilterNum   int64  `json:"filterNum"`   // 过滤条数
	PreNum      int64  `json:"preNum"`      // 预处理条数
	SuccessNum  int64  `json:"successNum"`  // 成功条数
	FailNum     int64  `json:"failNum"`     // 失败条数
	Progress    int64  `json:"progress"`    // 执行进度量
	OperateName string `json:"operateName"` // 操作人名称
}

type TaskListReq struct {
	Type   int64 `form:"type,optional"`   // 导入类别 1.权益发放 2.题库新增
	Status int64 `form:"status,optional"` // 任务状态 0.未开始 1.进行中 2.已完成 3.失败
	PageReq
}

type TaskListResp struct {
	List       []TaskListInfo `json:"list"`
	Pagination Pagination     `json:"pagination"`
}

type TaskDetailListReq struct {
	TaskId  int64  `form:"taskId"`           // 任务ID
	Status  int64  `form:"status,optional"`  // 任务状态 0.未开始 1.进行中 2.已完成 3.失败
	Keyword string `form:"keyword,optional"` // 查询关键字
	PageReq
}

type TaskDetailListResp struct {
	Progress   int64           `json:"progress"` // 任务进度执行量
	List       []TaskDetailLog `json:"list"`
	Pagination Pagination      `json:"pagination"`
}

type ImportFileReq struct {
	ImportFileInfo
}

type ExportDataReq struct {
	Parmas string `json:"params,optional"`
	Type   int64  `json:"type"`
}

type OrderBenefitInfo struct {
	Id           int64  `json:"id"`           // 渠道订单ID
	IsGrant      bool   `json:"isGrant"`      // 是否发放权益
	OrderNo      string `json:"orderNo"`      // 外部订单号
	GroupName    string `json:"groupName"`    // 权益名称
	Phone        string `json:"phone"`        // 手机号
	UserType     int64  `json:"userType"`     // 用户类型 1.单个子账号 2.主账号
	OrderType    int64  `json:"orderType"`    // 订单类型 1.发放 2.回收
	Source       string `json:"source"`       // 来源
	IsSmsNotifiy bool   `json:"isSmsNotifiy"` // 是否发送短信通知
	CreatedAt    int64  `json:"createdAt"`    // 创建时间
	UpdatedAt    int64  `json:"updatedAt"`    // 更新时间
}

type UserBenefitInfo struct {
	Id                 int64  `json:"id"`                 // ID
	BaseUserId         int64  `json:"baseUserId"`         // 主账号ID
	UserNo             string `json:"userNo"`             // 用户编号
	Phone              string `json:"phone"`              // 手机号
	UserId             int64  `json:"userId"`             // 子用户ID
	RealName           string `json:"realname"`           // 真实姓名
	BenefitsResourceId int64  `json:"benefitsResourceId"` // 资源ID
	Status             int64  `json:"status"`             // 状态 1.发放 2.回收
	BenefitName        string `json:"benefitName"`        // 权益名称
	GrantCount         int64  `json:"grantCount"`         // 发放数量
	ReclaimCount       int64  `json:"reclaimCount"`       // 回收数量
	StartTime          int64  `json:"startTime"`          // 开始时间
	EndTime            int64  `json:"endTime"`            // 结束时间
	CreatedAt          int64  `json:"createdAt"`          // 创建时间
	UpdatedAt          int64  `json:"updatedAt"`          // 更新时间
}

type ImportBenefitListReq struct {
	Phone   string `form:"phone,optional"`   // 手机号
	IsGrant int64  `form:"isGrant,optional"` // 是否发放 0.全部[默认] 1.是 2.否
	OrderNo string `form:"orderNo,optional"` // 订单号查询
	PageReq
}

type ImportBenefitListResp struct {
	List       []OrderBenefitInfo `json:"list"`
	Pagination Pagination         `json:"pagination"`
}

type ImportBenefitDescReq struct {
	ChannelOrderId int64 `form:"channelOrderId"` // 渠道主表ID
}

type ImportBenefitDescResp struct {
	List []UserBenefitInfo `json:"list"`
}

type UserBenefitDetailInfo struct {
	Id            int64  `json:"id"`            // ID
	UserId        int64  `json:"userId"`        // 子用户ID
	Type          int64  `json:"type"`          // 状态 1.发放 2.回收
	OrderNo       string `json:"orderNo"`       // 订单号
	BenefitName   string `json:"benefitName"`   // 权益名称
	BenefitType   string `json:"benefitType"`   // 权益类型
	UserBenefitId int64  `json:"userBenefitId"` // 用户权益ID
	HasBoth       bool   `json:"hasBoth"`       // 标识 相同订单号是否同时有type=1和type=2，即购买后退款
	Source        string `json:"source"`        // 来源
	CreatedAt     int64  `json:"createdAt"`     // 添加时间
}

type UserBenefitListReq struct {
	UserId             int64  `form:"userId,optional"`             // 子用户ID
	Phone              string `form:"phone,optional"`              // 手机号
	Status             int64  `form:"status,optional"`             // 状态 1.发放 2.回收
	BenefitsResourceId int64  `form:"benefitsResourceId,optional"` // 资源ID
	FromTime           string `form:"fromTime,optional"`           // 开始时间
	EndTime            string `form:"endTime,optional"`            // 结束时间
	PageReq
}

type UserBenefitListResp struct {
	List       []UserBenefitInfo `json:"list"`
	Pagination Pagination        `json:"pagination"`
}

type BenefitListResp struct {
	Id           int64  `json:"id"`           // 主键ID
	Name         string `json:"name"`         // 权益名称
	IsDeprecated bool   `json:"isDeprecated"` // 是否废弃
}

type UserBenefitDetailListReq struct {
	UserId             int64  `form:"userId"`             // 子用户ID
	BenefitsResourceId int64  `form:"benefitsResourceId"` // 资源ID
	OrderNo            string `form:"orderNo,optional"`   // 订单号
	Type               int64  `form:"type,optional"`      // 状态 1.发放 2.回收
	PageReq
}

type UserBenefitDetailListResp struct {
	List       []UserBenefitDetailInfo `json:"list"`
	Pagination Pagination              `json:"pagination"`
}

type UserPhoneModifyReq struct {
	Id        int64 `json:"id"`        // ID
	OldRoleId int64 `json:"oldRoleId"` // 当前用户ID
	NewRoleId int64 `json:"newRoleId"` // 目标用户ID
}

type GroupListResp struct {
	Id           int64  `json:"id"`           // 主键ID
	Name         string `json:"name"`         // 权益名称
	IsDeprecated bool   `json:"isDeprecated"` // 是否废弃
}

type UserBenefitAddReq struct {
	GroupId int64  `json:"groupId"` // 权益组主键ID
	Phone   string `json:"phone"`   // 手机号
	OrderId string `json:"orderId"` // 订单号
	Num     int64  `json:"num"`     // 数量
}

type ReissueReq struct {
	UserBenefitId int64 `json:"userBenefitId"` // 用户权益ID
}

type ChangeBenefitUserReq struct {
	BenefitId    int64 `json:"id"`           // 用户权益ID
	BaseUserId   int64 `json:"baseUserId"`   // 主账号ID
	TargetUserId int64 `json:"targetUserId"` // 目标子用户ID
}

type LessonInfo struct {
	LessonId      int64           `json:"lessonId"`      // 课程ID
	LessonNo      string          `json:"lessonNo"`      // 课程来源编号，导入时使用
	LessonGroupNo string          `json:"lessonGroupNo"` // 课程组编号
	ParentId      int64           `json:"parentId"`      // 导入数据时使用，只有大语文才会用到，用作关联父子级
	Level         int64           `json:"level"`         // 难度等级 只有小灶课才会使用，1-4个等级
	Name          string          `json:"name"`          // 课节名称
	LessonType    int64           `json:"lessonType"`    // 课程类型 1.主线课 2.月考 3.小灶课
	ReviewStatus  int64           `json:"reviewStatus"`  // 审核状态 1.初始录入 2.审核中 3.审核通过 4.审核未通过 5.下架
	Title         string          `json:"title"`         // 标题
	SubTitle      string          `json:"sub_title"`     // 副标题
	LearnTarget   []string        `json:"learn_target"`  // 学习目标
	Remark        string          `json:"remark"`        // 备注
	Grade         int64           `json:"grade"`         // 年级 10.学龄前 11.一年级 12.二年级 13.三年级 14.四年级 15.五年级 16.六年级 20.中小衔接 21.初一 22.初二 23.初三 31.高一 32.高二 33.高三 41.大学语文 42.中文专业 43.文学专家
	SubList       []LessonSubInfo `json:"list"`          // 题目列表
	CreatedAt     int64           `json:"createdAt"`     // 创建时间
	UpdatedAt     int64           `json:"updatedAt"`     // 更新时间
}

type LessonSubInfo struct {
	NodeType        int64  `json:"nodeType"`        // 导入数据时使用，节点类型 1.小灶课 2.小语文 3.大语文
	QuestionId      int64  `json:"questionId"`      // 题目ID
	QuestionNo      string `json:"questionNo"`      // 题目编号
	Type            int64  `json:"type"`            // 试题类型 1.单选 2.多选 3.填空 4.判断 5.简答 6.阅读题 7.作文
	UsageType       int64  `json:"usageType"`       // 使用类型 1.例题 2.练习题
	GradePhase      int64  `json:"gradePhase"`      // 年级学段 1.小学 2.初中 3.高中
	ReviewStatus    int64  `json:"reviewStatus"`    // 审核状态 1.初始录入 2.审核中 3.审核通过 4.审核未通过 5.下架
	Level           int64  `json:"level"`           // 等级
	ExampleId       int64  `json:"exampleId"`       // 例题ID
	MaterialId      int64  `json:"materialId"`      // 素材ID
	MaterialContent string `json:"materialContent"` // 素材内容，比如选取的阅读素材片段
	Ask             string `json:"ask"`             // 问题
	Answer          string `json:"answer"`          // 答案
	Analysis        string `json:"analysis"`        // 题目解析
	CreatedAt       int64  `json:"createdAt"`       // 创建时间
	UpdatedAt       int64  `json:"updatedAt"`       // 更新时间
}

type LessonListReq struct {
	LessonId          int64  `form:"lessonId,optional"`          // 课程ID
	LessonNo          int64  `form:"lessonNo,optional"`          // 课程编号
	Name              string `form:"name,optional"`              // 课程名称
	Title             string `form:"title,optional"`             // 主标题
	SubTitle          string `form:"subTitle,optional"`          // 副标题
	Status            int64  `form:"status,optional"`            // 审核状态 1.初始录入 2.审核中 3.审核通过 4.审核未通过 5.下架
	Grade             int64  `form:"grade,optional"`             // 年级 10.学龄前 11.一年级 12.二年级 13.三年级 14.四年级 15.五年级 16.六年级 20.中小衔接 21.初一 22.初二 23.初三 31.高一 32.高二 33.高三 41.大学语文 42.中文专业 43.文学专家
	QuestionId        int64  `form:"questionId,optional"`        // 题目ID
	QuestionNo        string `form:"questionNo,optional"`        // 题目编号
	QuestionUsageType int64  `form:"questionUsageType,optional"` // 使用类型 1.例题 2.练习题 3.候补题
	QuestionNodeType  int64  `form:"questionNodeType,optional"`  // 节点类型 1.小灶课 2.小语文 3.大语文
	QuestionType      int64  `form:"questionType,optional"`      // 试题类型 1.单选 2.多选 3.填空 4.判断 5.简答 6.阅读题 7.作文
	QuestionStatus    int64  `form:"questionStatus,optional"`    // 题目审核状态 1.初始录入 2.审核中 3.审核通过 4.审核未通过 5.下架
	QuestionAsk       string `form:"questionAsk,optional"`       // 题目问题
	PageReq
}

type LessonListResp struct {
	List       []LessonInfo `json:"list"`
	Pagination Pagination   `json:"pagination"`
}

type LessonExampleReq struct {
	ExampleId int64 `form:"exampleId"`
}

type LessonExampleResp struct {
	Content string `json:"content"` // 题目解析
}

type LessonDetailReq struct {
	UserId int64 `form:"userId"`
}

type LessonEditReq struct {
	UserId   int64  `json:"userId"`
	Name     string `json:"name"`               // 姓名
	Grade    int64  `json:"grade,range=[1:13]"` // 年级
	Gender   int64  `json:"gender,options=1|2"` // 性别
	Province int64  `json:"province"`           // 省
	City     int64  `json:"city,default=0"`     // 市 默认0
}

type LessonEditResp struct {
	Result bool `json:"result"`
}

type SuperTrainInfo struct {
	CourseId   int64               `json:"courseId,optional"`   // 课程ID
	CourseNo   string              `json:"courseNo,optional"`   // 课程编号
	CourseType int64               `json:"courseType,optional"` // 课程类型 1.写作慢练 2.写作快练 3.超练阅读
	Name       string              `json:"name,optional"`       // 课程名称
	Image      string              `json:"image,optional"`      // 课程封面图
	Intro      string              `json:"intro,optional"`      // 课程介绍
	Status     int64               `json:"status,optional"`     // 审核状态 1.初始录入 2.审核中 3.审核通过 4.审核未通过 5.下架
	OpenTime   int64               `json:"openTime,optional"`   // 开放时间
	Extra      string              `json:"extra,optional"`      // 额外信息
	SubList    []SuperTrainSubInfo `json:"list"`                // 题目列表
	CreatedAt  int64               `json:"createdAt"`           // 创建时间
	UpdatedAt  int64               `json:"updatedAt"`           // 更新时间
}

type SuperTrainSubInfo struct {
	ChapterId  int64  `json:"chapterId"`  // 章节ID
	ChapterNo  string `json:"chapterNo"`  // 章节编号
	Type       int64  `json:"type"`       // 试题类型 1.任务 2.文章
	Name       string `json:"name"`       // 章节名称
	Image      string `json:"image"`      // 章节封面图
	Intro      string `json:"intro"`      // 章节介绍
	Status     int64  `json:"status"`     // 状态 1.初始录入 2.审核中 3.审核通过 4.审核未通过 5.下架
	IsCanLearn int64  `json:"isCanLearn"` // 是否可学
	IsNew      int64  `json:"isNew"`      // 是否上新
	Extra      string `json:"extra"`      // 额外信息
	CreatedAt  int64  `json:"createdAt"`  // 创建时间
	UpdatedAt  int64  `json:"updatedAt"`  // 更新时间
}

type SuperTrainListReq struct {
	CourseId    int64  `form:"courseId,optional"`    // 课程ID
	CourseNo    string `form:"courseNo,optional"`    // 课程编号
	Type        int64  `form:"courseType,optional"`  // 课程类型 1.写作慢练 2.写作快练 3.超练阅读
	Name        string `form:"name,optional"`        // 课程名称
	Status      int64  `form:"status,optional"`      // 审核状态 1.初始录入 2.审核中 3.审核通过 4.审核未通过 5.下架
	ChapterId   int64  `form:"chapterId,optional"`   // 章节ID
	ChapterNo   string `form:"chapterNo,optional"`   // 章节编号
	ChapterName string `form:"chapterName,optional"` // 章节名称
	PageReq
}

type SuperTrainListResp struct {
	List       []SuperTrainInfo `json:"list"`
	Pagination Pagination       `json:"pagination"`
}

type GetOrderListReq struct {
	UserName    string `form:"userName,optional"`    // 用户名
	OrderNo     string `form:"orderNo,optional"`     // 订单号
	Phone       string `form:"phone,optional"`       // 手机号
	SkuType     int64  `form:"skuType,optional"`     // 商品组合类型：1.虚拟 2.实物 3.混合
	OrderStatus int64  `form:"orderStatus,optional"` // 订单状态：10. 待支付 20. 已支付 30. 已取消 40. 已全部退款 50. 已部分退款 60. 支付失败 70. 关闭订单
	PayStatus   int64  `form:"payStatus,optional"`   // 支付状态：1. 待支付 2.支付中 3. 支付成功 4. 支付取消 5. 支付失败 6. 退款中 7.已退款 8.部分退款 9.支付关闭
	PayChannel  int64  `form:"payChannel,optional"`  // 支付渠道 1.支付宝 2.微信 3.苹果 4.余额
	GrantStatus int64  `form:"grantStatus,optional"` // 商品发放状态： 1. 待发放 2.已发放 3. 已回收
	SubOrderNo  string `form:"subOrderNo,optional"`  // 子订单号
	SkuName     string `form:"skuName,optional"`     // 商品名称
	PageReq
	TimeFilter
	IsNeedLogistics int64 `form:"isNeedLogistics,optional"` // 是否需要物流 1 需要 2 不需要
}

type OrderResearchInfo struct {
	OrderNo         string `json:"orderNo"`         // 订单号
	SubOrderNo      string `json:"subOrderNo"`      // 子订单号
	UserName        string `json:"userName"`        // 用户名
	Phone           string `json:"phone"`           // 手机号
	SkuName         string `json:"skuName"`         // 商品名称
	SkuType         int64  `json:"skuType"`         // 商品组合类型：1.虚拟 2.实物 3.混合
	SkuId           int64  `json:"skuId"`           // sku id
	SkuNum          int64  `json:"skuNum"`          // 商品数量
	SkuPrice        int64  `json:"skuPrice"`        // 商品价格
	SkuStone        int64  `json:"skuStone"`        // 商品悟性石
	OrderStatus     int64  `json:"orderStatus"`     // 订单状态：10. 待支付 20. 已支付 30. 已取消 40. 已全部退款 50. 已部分退款 60. 支付失败 70. 关闭订单
	PayStatus       int64  `json:"payStatus"`       // 支付状态：1. 待支付 2.支付中 3. 支付成功 4. 支付取消 5. 支付失败 6. 退款中 7.已退款 8.部分退款 9.支付关闭
	GrantStatus     int64  `json:"grantStatus"`     // 商品发放状态： 1. 待发放 2.已发放 3. 已回收
	IsNeedLogistics int64  `json:"isNeedLogistics"` // 是否需要物流 1 需要 2 不需要
	CreatedAt       string `json:"createdAt"`       // 订单生成时间
}

type GetOrderListResp struct {
	List       []*OrderResearchInfo `json:"list"` // 订单列表
	Pagination Pagination           `json:"pagination"`
}

type OrderWaitSendReq struct {
	OrderNo     string `form:"orderNo,optional"`     // 订单号
	SubOrderNo  string `form:"subOrderNo,optional"`  // 子订单号
	GoodsName   string `form:"goodsName,optional"`   // 商品名称
	UserName    string `form:"userName,optional"`    // 用户名
	UserPhone   string `form:"userPhone,optional"`   // 手机号
	GrantStatus int64  `form:"grantStatus,optional"` // 商品发放状态： 1. 待发放 2.已发放 3. 已回收
	PageReq
	TimeFilter
	ExportAll int64 `form:"exportAll,optional"` // 是否导出 1.导出所有 2.导出本页
}

type OrderWaitSend struct {
	OrderNo     string `json:"orderNo"`     // 订单号
	SubOrderNo  string `json:"subOrderNo"`  // 子订单号
	GoodsName   string `json:"goodsName"`   // 商品名称
	Pcs         int64  `json:"pcs"`         // 商品数量
	UserName    string `json:"userName"`    // 用户名
	UserPhone   string `json:"userPhone"`   // 手机号
	Province    string `json:"province"`    // 省
	City        string `json:"city"`        // 市
	Area        string `json:"area"`        // 区
	Address     string `json:"address"`     // 详细地址
	GrantStatus int64  `json:"grantStatus"` // 商品发放状态： 1. 待发放 2.已发放 3. 已回收
	CreatedAt   string `json:"createdAt"`   // 订单生成时间
	PayChannel  int64  `json:"payChannel"`  // 支付渠道 1.微信 2.支付宝 3.苹果 4.余额
}

type OrderWaitSendResp struct {
	List       []*OrderWaitSend `json:"list"` // 订单列表
	Pagination Pagination       `json:"pagination"`
}

type ExportWaitSendResp struct {
	Url string `json:"url"` // 导出文件地址
}

type GoodsListReq struct {
	SkuId int64 `form:"skuId"` // SKU ID
}

type GoodsInfo struct {
	Id            int64  `json:"id"`            // 商品ID
	Name          string `json:"name"`          // 商品名称
	Stock         int64  `json:"stock"`         // 库存
	Description   string `json:"description"`   // 商品描述
	OriginalPrice int64  `json:"originalPrice"` // 原价
	Price         int64  `json:"price"`         // 折扣价
	Type          int64  `json:"type"`          // 商品类型 1:虚拟 2:实物
	Pcs           int64  `json:"pcs"`           // 商品数量
}

type GoodsListResp struct {
	List []*GoodsInfo `json:"list"` // 商品列表
}

type OrderExpressReq struct {
	SubOrderNo string `json:"subOrderNo"` // 子单号
}

type OrderExpressResp struct {
}

type HubLessonInfo struct {
	Id            int64  `json:"id"`
	LessonNo      string `json:"lessonNo"`      // 课节编号
	NodeType      int64  `json:"nodeType"`      // 节点类型 1.小灶课 2.小语文 3.大语文
	Name          string `json:"name"`          // 课程名称
	PointName     string `json:"pointName"`     // 知识点名称
	Status        int64  `json:"status"`        // 审核状态 1.初始录入 2.审核中 3.审核通过 4.未通过 5.下架
	Grade         int64  `json:"grade"`         // 年级 10.学龄前 11.一年级 12.二年级 13.三年级 14.四年级 15.五年级 16.六年级 20.中小衔接 21.初一 22.初二 23.初三 31.高一 32.高二 33.高三 41.大学语文 42.中文专业 43.文学专家
	Version       int64  `json:"version"`       // 版本号
	OperateStatus int64  `json:"operateStatus"` // 操作状态 0.未推送 1.已推送 2.已下架
	OperateName   string `json:"operateName"`   // 操作人名称
	Data          string `json:"data"`          // 原始数据
	AppVersion    string `json:"appVersion"`    // APP版本
	CreatedAt     int64  `json:"createdAt"`     // 接收数据时间
	UpdatedAt     int64  `json:"updatedAt"`     // 最后一次审核时间
}

type HubLessonListReq struct {
	Id            int64  `form:"id,optional"`
	LessonNo      string `form:"lessonNo,optional"`      // 课节编号
	NodeType      int64  `form:"nodeType,optional"`      // 节点类型 1.小灶课 2.小语文 3.大语文
	Name          string `form:"name,optional"`          // 课程名称
	PointName     string `form:"pointName,optional"`     // 知识点名称
	Status        int64  `form:"status,optional"`        // 审核状态 1.初始录入 2.审核中 3.审核通过 4.审核未通过 5.下架
	OperateStatus int64  `form:"operateStatus,optional"` // 操作状态 0.未推送 1.已推送 2.已下架
	PageReq
}

type HubLessonListResp struct {
	List       []HubLessonInfo `json:"list"`
	Pagination Pagination      `json:"pagination"`
}

type HubLessonDetailReq struct {
	Id int64 `form:"id"`
}

type HubLessonInspectReq struct {
	Id int64 `json:"id"`
}

type HubLessonBatchInspectReq struct {
	StartId int64 `json:"startId"`
	EndId   int64 `json:"endId"`
	Source  int64 `json:"source"`
}

type HubLiveInfo struct {
	Id            int64  `json:"id"`
	LiveNo        int64  `json:"lessonNo"`      // 课节编号
	NodeType      int64  `json:"nodeType"`      // 节点类型 1.小灶课 2.小语文 3.大语文
	Name          string `json:"name"`          // 课程名称
	PointName     string `json:"pointName"`     // 知识点名称
	Status        int64  `json:"status"`        // 审核状态 1.初始录入 2.审核中 3.审核通过 4.未通过 5.下架
	Grade         int64  `json:"grade"`         // 年级 10.学龄前 11.一年级 12.二年级 13.三年级 14.四年级 15.五年级 16.六年级 20.中小衔接 21.初一 22.初二 23.初三 31.高一 32.高二 33.高三 41.大学语文 42.中文专业 43.文学专家
	Version       int64  `json:"version"`       // 版本号
	OperateStatus int64  `json:"operateStatus"` // 操作状态 0.未推送 1.已推送 2.已下架
	OperateName   string `json:"operateName"`   // 操作人名称
	Data          string `json:"data"`          // 原始数据
	AppVersion    string `json:"appVersion"`    // APP版本
	CreatedAt     int64  `json:"createdAt"`     // 接收数据时间
	UpdatedAt     int64  `json:"updatedAt"`     // 最后一次审核时间
}

type HubLiveInspectReq struct {
	LiveNo string `json:"liveNo"`
}

type HubSuperTrainInfo struct {
	Id            int64  `json:"id"`
	No            string `json:"no"`            // 课节编号
	Name          string `json:"name"`          // 课程名称
	Status        int64  `json:"status"`        // 审核状态 1.初始录入 2.审核中 3.审核通过 4.未通过 5.下架
	Version       int64  `json:"version"`       // 版本号
	OperateStatus int64  `json:"operateStatus"` // 操作状态 0.未推送 1.已推送 2.已下架
	OperateName   string `json:"operateName"`   // 操作人名称
	Data          string `json:"data"`          // 原始数据
	AppVersion    string `json:"appVersion"`    // APP版本
	CreatedAt     int64  `json:"createdAt"`     // 接收数据时间
	UpdatedAt     int64  `json:"updatedAt"`     // 最后一次审核时间
}

type HubSuperTrainListReq struct {
	Id            int64  `form:"id,optional"`
	No            string `form:"no,optional"`            // 课程编号
	Name          string `form:"name,optional"`          // 课程名称
	Status        int64  `form:"status,optional"`        // 审核状态 1.初始录入 2.审核中 3.审核通过 4.审核未通过 5.下架
	OperateStatus int64  `form:"operateStatus,optional"` // 操作状态 0.未推送 1.已推送 2.已下架
	PageReq
}

type HubSuperTrainListResp struct {
	List       []HubSuperTrainInfo `json:"list"`
	Pagination Pagination          `json:"pagination"`
}

type HubSuperTrainDetailReq struct {
	Id int64 `form:"id"`
}

type HubSuperTrainInspectReq struct {
	Id int64 `json:"id"`
}

type HubSuperTrainBatchInspectReq struct {
	StartId int64 `json:"startId"`
	EndId   int64 `json:"endId"`
}

type HubSuperTrainSyncReq struct {
	Data string `json:"data"`
}

type LiveBetaUserListReq struct {
	Id       int64  `form:"id,optional"`       // ID
	Phone    string `form:"phone,optional"`    // 手机号
	Username string `form:"username,optional"` // 用户名
	Company  string `form:"company,optional"`  // 公司名
	Status   int64  `form:"status,optional"`   // 审核状态 1.审核中 2.审核通过 3.审核不通过
	PageReq
}

type LiveBetaUserListResp struct {
	List       []LiveBetaUserInfo `json:"list"`
	Pagination Pagination         `json:"pagination"`
}

type LiveBetaUserInfo struct {
	Id          int64  `json:"id"`          // 手机号
	Phone       string `json:"phone"`       // 手机号
	Username    string `json:"username"`    // 用户名
	Company     string `json:"company"`     // 公司名
	Status      int64  `json:"status"`      // 审核状态 1.审核中 2.审核通过 3.审核不通过
	Remark      string `json:"remark"`      // 备注
	OperateName string `json:"operateName"` // 操作人
	OperateAt   int64  `json:"operateAt"`   // 审核时间
	CreatedAt   int64  `json:"createdAt"`   // 创建时间
	UpdatedAt   int64  `json:"updatedAt"`   // 更新时间
}

type LiveBetaUserInspectReq struct {
	Id     int64 `json:"id"`
	Status int64 `json:"status"`
}

type LiveBetaUserInspectResp struct {
	Result bool `json:"result"`
}

type GetActiveLivesResp struct {
	List []ActiveLiveInfo `json:"list"` // 直播列表
}

type ActiveLiveInfo struct {
	StreamId int64  `json:"streamId"` // 直播间ID
	Name     string `json:"name"`     // 直播名称
}

type GetLiveStudentsReq struct {
	StreamId    int64  `form:"streamId"`             //直播间id
	StudentName string `form:"studentName,optional"` // 学生名称，支持模糊搜索
	PageReq
}

type GetLiveStudentsResp struct {
	List       []LiveStudentInfo `json:"list"` // 学生列表
	Pagination Pagination        `json:"pagination"`
}

type LiveStudentInfo struct {
	UserId   int64  `json:"userId"`   // 用户ID，界面展示用
	ImUserId string `json:"imUserId"` // IM用户ID，禁言时传参
	UserName string `json:"userName"` // 用户名
	IsMute   int64  `json:"isMute"`   // 禁言状态 1-禁言 2-未禁言
	EndAt    int64  `json:"endAt"`    // 禁言结束时间戳，单位：秒，-1表示永久禁言
	RoomId   string `json:"roomId"`   //直播间信令房间
}

type MutePersonalReq struct {
	RoomId   string `json:"roomId"`   // 直播房间号
	IsMute   int64  `json:"isMute"`   // 是否禁言 1.禁言 2.取消禁言
	ImUserId string `json:"imUserId"` // 学生用户ID
	Duration int64  `json:"duration"` // 禁言时长，单位：秒 -1:表示永久禁言 >0:表示具体时长
}

type AddCodeReq struct {
	CodeNumber      int64  `json:"codeNumber"          validate:"number,gte=0,lte=10000"         label:"兑换码数量"`
	BenefitsGroupId int64  `json:"benefitsGroupId"     validate:"number,gte=0"                   label:"权益组表ID"`
	Batch           int64  `json:"batch"               validate:"number"                         label:"批次"`
	ValidDate       string `json:"validDate"           validate:"max=100"                        label:"有效期"`
}

type ListCodeReq struct {
	Code            string `form:"code,optional"` // 兑换码
	Page            int64  `form:"page,optional"`
	PageSize        int64  `form:"pageSize,optional"`
	Batch           int64  `form:"batch,optional"`
	BenefitsGroupId int64  `form:"benefitsGroupId,optional"`
}

type ListCodeResp struct {
	List       []CodeList         `json:"list"`
	Pagination ListCodePagination `json:"pagination"`
}

type CodeList struct {
	Code            string `json:"code"`
	BenefitsGroupId int64  `json:"benefitsGroupId"`
	ValidDate       string `json:"validDate"`
	Batch           int64  `json:"batch"`
	Status          int64  `json:"status"`
	Id              int64  `json:"id"`
}

type ListCodePagination struct {
	Page  int64 `json:"page"`
	Limit int64 `json:"limit"`
	Total int64 `json:"total"`
}

type ExportCodeResp struct {
	Url string `json:"url"` // 导出文件地址
}

type GetListByUserIdReq struct {
	UserId int64 `form:"userId"` // 用户ID
}

type GetListByUserIdResp struct {
	List []*EventSession `json:"list"` // 用户会话关系列表
}

type EventSession struct {
	StratTime string `json:"stratTime"` // 开始时间
	EndTime   string `json:"endTime"`   // 结束时间
	Session   string `json:"session"`   // 会话
	SessionId int64  `json:"sessionId"` //  会话ID
}

type EventRecord struct {
	EventId   string `json:"eventId"`   // 事件ID
	EventType string `json:"eventType"` // 事件类型
	EventTime int64  `json:"eventTime"` // 事件时间
	Page      string `json:"page"`      // 事件页面
	AppId     string `json:"appId"`     // 应用ID
	Phone     string `json:"phone"`     // 手机号
	UserAgent string `json:"userAgent"` // 浏览器信息
	Screen    string `json:"screen"`    // 屏幕信息
	Language  string `json:"language"`  // 语言
	Data      string `json:"data"`      // 事件数据
}

type GetListBySessionIdReq struct {
	SessionId int64 `form:"sessionId"` // 会话ID
}

type GetListBySessionIdResp struct {
	List []*EventRecord `json:"list"` // 用户会话关系列表
}

type UserIdListResp struct {
	List []int64 `json:"list"` // 用户ID列表
}

type SeriesType struct {
	SeriesType     int    `json:"series_type"`
	SeriesTypeName string `json:"series_type_name"`
}

type CourseType struct {
	CourseType     int    `json:"course_type"`
	CourseTypeName string `json:"course_type_name"`
}

type Teacher struct {
	Id   int    `json:"id"`
	Name string `json:"name"`
}

type TaskType struct {
	TaskType     int    `json:"task_type"`
	TaskTypeName string `json:"task_type_name"`
}

type SubTaskType struct {
	SubTaskType     int    `json:"sub_task_type"`
	SubTaskTypeName string `json:"sub_task_type_name"`
}

type CourseCommonData struct {
	SeriesTypeList  []SeriesType  `json:"series_type_list"`
	CourseTypeList  []CourseType  `json:"course_type_list"`
	TeacherIds      []Teacher     `json:"teacher_ids"`
	TaskTypeList    []TaskType    `json:"task_type_list"`
	SubTaskTypeList []SubTaskType `json:"sub_task_type_list"`
}

type GetCourseChapterReq struct {
	CourseId int64 `form:"courseId"` // 课程ID
}

type GetCourseChapterResp struct {
	ChapterList []CourseChapter `json:"chapterList"`
}

type CourseChapter struct {
	Id        int64  `json:"id"`        // 章节ID
	CourseId  int64  `json:"courseId"`  // 课程ID
	ChapterNo string `json:"chapterNo"` // 编号
	Name      string `json:"name"`      // 名字
	Title     string `json:"title"`     // 精简版标题
}

type GetChapterTaskReq struct {
	ChapterId int64 `form:"chapterId"` // 章节ID
}

type GetChapterTaskResp struct {
	TaskList []ChapterTask `json:"taskList"`
}

type ChapterTask struct {
	Id        int64  `json:"id"`        // 任务ID
	ChapterId int64  `json:"chapterId"` // 章节ID
	TaskNo    string `json:"taskNo"`    // 编号
	Title     string `json:"title"`     // 名字
}

type AzureAuthReq struct {
	Type int `form:"type,options=7"` // type=7 TTS授权
}

type AzureAuthResp struct {
	Token  string `json:"token"`  // 临时token
	Region string `json:"region"` // 地区Region
}

type TencentAuthReq struct {
	Type int `form:"type,options=1|2|3|4|5|6|8"` // type=1:OSS文章授权 type=2:OSSapp通用资源授权 type=3:OSSFormula授权 type=4:OSSH5授权 type=5:ASR授权 type=6:TTS授权type=8:数字人图片授权
}

type TencentAuthResp struct {
	TmpSecretID  string `json:"tmpSecretId"`
	TmpSecretKey string `json:"tmpSecretKey"`
	SessionToken string `json:"sessionToken"`
	StartTime    string `json:"startTime"`
	ExpiredTime  string `json:"expiredTime"`
	RequestId    string `json:"requestId"`
	Bucket       string `json:"bucket"`
	Region       string `json:"region"`
	FileDir      string `json:"fileDir"`
	StaticUrl    string `json:"StaticUrl"`
}

type SysDictWhite struct {
	Id        int64  `json:"id"`        // ID
	Key       string `json:"key"`       // 字典key
	Remark    string `json:"remark"`    // 备注
	CreatedAt int64  `json:"createdAt"` // 创建时间
	UpdatedAt int64  `json:"updatedAt"` // 修改时间
}

type MuseDictPageReq struct {
	PageReq
	Key    string `form:"key,optional"`
	Remark string `form:"remark,optional"`
}

type MuseDictPageResp struct {
	List       []SysDictWhite `json:"list"`
	Pagination Pagination     `json:"pagination"`
}

type AddMuseDictReq struct {
	Key    string `json:"key"`    // 字典key
	Remark string `json:"remark"` // 备注
}

type DeleteMuseDictReq struct {
	Id int64 `json:"id"  validate:"number,gte=1" label:"字典id"`
}

type UpdateMuseDictReq struct {
	Id     int64  `json:"id"         validate:"number,gte=1"         label:"字典id"`
	Key    string `json:"key"`    // 字典key
	Remark string `json:"remark"` // 备注
}

type SupervisorListReq struct {
	Id           int64 `form:"id,optional"`           // ID
	TeacherId    int64 `form:"teacherId,optional"`    // 教师id
	CourseId     int64 `form:"courseId,optional"`     // 课程id
	Status       int64 `form:"status,optional"`       // 状态 1.待开放 2.开放 3.进行中 4.结束
	ScheduleType int64 `form:"scheduleType,optional"` // 排课类型 1.直播 2.录播
	PageReq
}

type SupervisorListResp struct {
	List       []SupervisorInfo `json:"list"`
	Pagination Pagination       `json:"pagination"`
}

type SupervisorInfo struct {
	Id               int64  `json:"id"`               // 手机号
	TeacherId        int64  `json:"teacherId"`        // 教师id
	TeacherName      string `json:"teacherName"`      // 教师名称
	CourseId         int64  `json:"courseId"`         // 课程id
	CourseName       string `json:"courseName"`       // 课程名称
	CourseType       int64  `json:"courseType"`       // 课程类型 1.超练作文慢练 2.超练作文快练 3.超练阅读
	Name             string `json:"name"`             // 督学课名称
	StreamTitle      string `json:"streamTitle"`      // 直播表标题
	ScheduleType     int64  `json:"scheduleType"`     // 排课类型 1.直播 2.录播
	StartTime        int64  `json:"startTime"`        // 开课时间
	AppointmentStart int64  `json:"appointmentStart"` // 开始预约时间
	AppointmentEnd   int64  `json:"appointmentEnd"`   // 结束预约时间
	MaxStock         int64  `json:"maxStock"`         // 最大库存
	SurplusStock     int64  `json:"surplusStock"`     // 剩余库存
	Status           int64  `json:"status"`           // 状态 1.待开放 2.开放 3.进行中 4.结束
	BgUrl            string `json:"bgUrl"`            // 伴学、督学课程背景图片
	Content          string `json:"content"`          // 伴学、督学课程文案
	CreatedAt        int64  `json:"createdAt"`        // 创建时间
	UpdatedAt        int64  `json:"updatedAt"`        // 更新时间
}

type SupervisorScheduleStatusReq struct {
	Id     int64 `json:"id" validate:"number"`
	Status int64 `json:"status" validate:"number,gt=0"` // 1.待开放 2.开放 3.进行中 4.结束
}

type SupervisorScheduleEditReq struct {
	Id              int64    `json:"id,optional" validate:"number"`
	TearcherId      int64    `json:"teacherId"`
	TeacherName     string   `json:"teacherName"`
	CourseId        int64    `json:"courseId"`
	CourseType      int64    `json:"courseType"` // 类型 1.超练作文 2.超练阅读
	Name            string   `json:"name"`
	StreamTitle     string   `json:"streamTitle"`                          // 直播课标题
	EffectiveTime   []string `json:"effectiveTime"     validate:"len=2"`   // 活动时间
	AppointmentTime []string `json:"appointmentTime"     validate:"len=2"` // 预约时间
	StartTime       string   `json:"startTime"           validate:"len=1"` // 开课时间
	MaxStock        int64    `json:"maxStock"            validate:"number,gte=0"`
	SurplusStock    int64    `json:"surplusStock"        validate:"number,gte=0"`
	ScheduleType    int64    `json:"scheduleType"        validate:"number,gt=0"` // 1.直播2.录播
	Status          int64    `json:"status"              validate:"number,gt=0"` // 1.待开放 2.开放 3.进行中 4.结束
	BgUrl           string   `json:"bgUrl"`
	Content         string   `json:"content"`
}

type TeacherListReq struct {
	Role int64 `form:"role,optional"` //教师角色  '角色 0.未选择角色 1.主讲 2.班主任 3.导播'
}

type TeacherListResp struct {
	List []TeacherInfo `json:"list"`
}

type TeacherInfo struct {
	Id        int64  `json:"id"`        //教师id
	AccountId int64  `json:"accountId"` //教师账户ID
	Name      string `json:"name"`      //教师名称
	Phone     string `json:"phone"`     //手机号
}

type InteractionListReq struct {
	Name string `form:"name,optional"` // 互动名字
}

type InteractionListResp struct {
	List []InteractionInfo `json:"list"`
}

type InteractionInfo struct {
	Id           int64  `json:"id"`           // 互动ID
	Name         string `json:"name"`         // 互动名字
	Description  string `json:"description"`  // 描述
	TeachingData string `json:"teachingData"` // 教师ppt
	Data         string `json:"data"`         // 互动数据
}

type InteractionAddReq struct {
	Name         string `json:"name"         validate:"required,min=1,max=50"` // 互动名字
	Description  string `json:"description,optional"`                          // 描述
	TeachingData string `json:"teachingData,optional"`                         // 教师ppt
	Data         string `json:"data,optional"`                                 // 互动数据
}

type InteractionUpdateReq struct {
	Id           int64  `json:"id"           validate:"required,number,gt=0"`  // 互动ID
	Name         string `json:"name"         validate:"required,min=1,max=50"` // 互动名字
	Description  string `json:"description,optional"  validate:"omitempty"`    // 描述
	TeachingData string `json:"teachingData,optional"  validate:"omitempty"`   // 教师ppt
	Data         string `json:"data,optional"          validate:"omitempty"`   // 互动数据
}

type CourseListReq struct {
	UseCases   int64 `form:"useCases,optional"`   // 使用场景 1.练习 2.直播互动
	CourseType int64 `form:"courseType,optional"` // 课程类型 1.超练作文 2.超练阅读
}

type CourseListResp struct {
	List []Course `json:"list"`
}

type Course struct {
	Id         int64  `json:"id"`         // ID
	CourseType int64  `json:"courseType"` // 课程类型 1.超练作文慢练 2.超练作文快练 3.超练阅读
	Name       string `json:"name"`       // 课程名称
	LessonName string `json:"lessonName"` // 课节名称
}
