// Code generated by goctl. DO NOT EDIT.

package knowledge

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	exampleFieldNames          = builder.RawFieldNames(&Example{})
	exampleRows                = strings.Join(exampleFieldNames, ",")
	exampleRowsExpectAutoSet   = strings.Join(stringx.Remove(exampleFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	exampleRowsWithPlaceHolder = strings.Join(stringx.Remove(exampleFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	exampleModel interface {
		Insert(ctx context.Context, data *Example) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Example, error)
		Update(ctx context.Context, data *Example) error
		Delete(ctx context.Context, id int64) error
	}

	defaultExampleModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Example struct {
		Id               int64     `db:"id"`                 // 主键ID
		Content          string    `db:"content"`            // 例题内容，JSON格式 旧版
		Explain          string    `db:"explain"`            // 例题内容，JSON格式 新版
		PlainText        string    `db:"plain_text"`         // JSON中的纯文本内容
		PlainTextArticle string    `db:"plain_text_article"` // JSON中的纯文本文章
		Title            string    `db:"title"`              // 标题
		SubTitle         string    `db:"sub_title"`          // 副标题
		LessonNotes      string    `db:"lesson_notes"`       // 课堂笔记
		CreatedAt        time.Time `db:"created_at"`         // 创建时间
		UpdatedAt        time.Time `db:"updated_at"`         // 更新时间
	}
)

func newExampleModel(conn sqlx.SqlConn) *defaultExampleModel {
	return &defaultExampleModel{
		conn:  conn,
		table: "`kn_example`",
	}
}

func (m *defaultExampleModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultExampleModel) FindOne(ctx context.Context, id int64) (*Example, error) {

	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", exampleRows, m.table)

	var resp Example
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultExampleModel) Insert(ctx context.Context, data *Example) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, exampleRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Content, data.Explain, data.PlainText, data.PlainTextArticle, data.Title, data.SubTitle, data.LessonNotes)
	return ret, err
}

func (m *defaultExampleModel) Update(ctx context.Context, data *Example) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, exampleRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Content, data.Explain, data.PlainText, data.PlainTextArticle, data.Title, data.SubTitle, data.LessonNotes, data.Id)
	return err
}

func (m *defaultExampleModel) TableName() string {
	return m.table
}
