// Code generated by goctl. DO NOT EDIT.

package knowledge

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	lessonQuestionFieldNames          = builder.RawFieldNames(&LessonQuestion{})
	lessonQuestionRows                = strings.Join(lessonQuestionFieldNames, ",")
	lessonQuestionRowsExpectAutoSet   = strings.Join(stringx.Remove(lessonQuestionFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	lessonQuestionRowsWithPlaceHolder = strings.Join(stringx.Remove(lessonQuestionFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	lessonQuestionModel interface {
		Insert(ctx context.Context, data *LessonQuestion) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*LessonQuestion, error)
		Update(ctx context.Context, data *LessonQuestion) error
		Delete(ctx context.Context, id int64) error
	}

	defaultLessonQuestionModel struct {
		conn  sqlx.SqlConn
		table string
	}

	LessonQuestion struct {
		Id           int64          `db:"id"`            // 主键ID
		QuestionNo   string         `db:"question_no"`   // 题目编号
		NodeType     int64          `db:"node_type"`     // 节点类型 1.小灶课 2.小语文 3.大语文
		Type         int64          `db:"type"`          // 试题类型 1：单选，2：多选，3：填空，4：判断，5：简答，6：阅读题 7：作文
		UsageType    int64          `db:"usage_type"`    // 使用类型，1：例题；2：练习题；3：候补题
		GradePhase   int64          `db:"grade_phase"`   // 年级学段，1：小学；2：初中；3：高中
		ReviewStatus int64          `db:"review_status"` // 审核状态 1.初始录入 2.审核中 3.审核通过 4.审核未通过 5.下架
		Level        int64          `db:"level"`         // 等级
		MaterialId   int64          `db:"material_id"`   // 题目素材Id
		ExampleId    int64          `db:"example_id"`    // 例题id
		Ask          string         `db:"ask"`           // 问题
		Answer       sql.NullString `db:"answer"`        // 答案，针对简答题，用于答案判别
		Analysis     sql.NullString `db:"analysis"`      // 题目解析，用于答案判别
		StartTts     sql.NullString `db:"start_tts"`     // 开场白TTS
		Duration     int64          `db:"duration"`      // 预计用时
		Source       string         `db:"source"`        // 来源
		Version      int64          `db:"version"`       // 版本
		CreatedBy    int64          `db:"created_by"`    // 创建者，程序导入为0，其他为操作者ID
		UpdatedBy    int64          `db:"updated_by"`    // 更新者，程序导入为0，其他为操作者ID
		CreatedAt    time.Time      `db:"created_at"`    // 创建时间
		UpdatedAt    time.Time      `db:"updated_at"`    // 更新时间
	}
)

func newLessonQuestionModel(conn sqlx.SqlConn) *defaultLessonQuestionModel {
	return &defaultLessonQuestionModel{
		conn:  conn,
		table: "`kn_lesson_question`",
	}
}

func (m *defaultLessonQuestionModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultLessonQuestionModel) FindOne(ctx context.Context, id int64) (*LessonQuestion, error) {

	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", lessonQuestionRows, m.table)

	var resp LessonQuestion
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultLessonQuestionModel) Insert(ctx context.Context, data *LessonQuestion) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, lessonQuestionRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.QuestionNo, data.NodeType, data.Type, data.UsageType, data.GradePhase, data.ReviewStatus, data.Level, data.MaterialId, data.ExampleId, data.Ask, data.Answer, data.Analysis, data.StartTts, data.Duration, data.Source, data.Version, data.CreatedBy, data.UpdatedBy)
	return ret, err
}

func (m *defaultLessonQuestionModel) Update(ctx context.Context, data *LessonQuestion) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, lessonQuestionRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.QuestionNo, data.NodeType, data.Type, data.UsageType, data.GradePhase, data.ReviewStatus, data.Level, data.MaterialId, data.ExampleId, data.Ask, data.Answer, data.Analysis, data.StartTts, data.Duration, data.Source, data.Version, data.CreatedBy, data.UpdatedBy, data.Id)
	return err
}

func (m *defaultLessonQuestionModel) TableName() string {
	return m.table
}
