// Code generated by goctl. DO NOT EDIT.

package knowledge

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	lessonPointFieldNames          = builder.RawFieldNames(&LessonPoint{})
	lessonPointRows                = strings.Join(lessonPointFieldNames, ",")
	lessonPointRowsExpectAutoSet   = strings.Join(stringx.Remove(lessonPointFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	lessonPointRowsWithPlaceHolder = strings.Join(stringx.Remove(lessonPointFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	lessonPointModel interface {
		Insert(ctx context.Context, data *LessonPoint) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*LessonPoint, error)
		Update(ctx context.Context, data *LessonPoint) error
		Delete(ctx context.Context, id int64) error
	}

	defaultLessonPointModel struct {
		conn  sqlx.SqlConn
		table string
	}

	LessonPoint struct {
		Id        int64     `db:"id"`         // 主键ID
		LessonId  int64     `db:"lesson_id"`  // 课节ID
		Name      string    `db:"name"`       // 知识点名称
		CreatedAt time.Time `db:"created_at"` // 创建时间
		UpdatedAt time.Time `db:"updated_at"` // 更新时间
	}
)

func newLessonPointModel(conn sqlx.SqlConn) *defaultLessonPointModel {
	return &defaultLessonPointModel{
		conn:  conn,
		table: "`kn_lesson_point`",
	}
}

func (m *defaultLessonPointModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultLessonPointModel) FindOne(ctx context.Context, id int64) (*LessonPoint, error) {

	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", lessonPointRows, m.table)

	var resp LessonPoint
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultLessonPointModel) Insert(ctx context.Context, data *LessonPoint) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, lessonPointRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.LessonId, data.Name)
	return ret, err
}

func (m *defaultLessonPointModel) Update(ctx context.Context, data *LessonPoint) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, lessonPointRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.LessonId, data.Name, data.Id)
	return err
}

func (m *defaultLessonPointModel) TableName() string {
	return m.table
}
