// Code generated by goctl. DO NOT EDIT.

package knowledge

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	lessonResourceFieldNames          = builder.RawFieldNames(&LessonResource{})
	lessonResourceRows                = strings.Join(lessonResourceFieldNames, ",")
	lessonResourceRowsExpectAutoSet   = strings.Join(stringx.Remove(lessonResourceFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	lessonResourceRowsWithPlaceHolder = strings.Join(stringx.Remove(lessonResourceFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	lessonResourceModel interface {
		Insert(ctx context.Context, data *LessonResource) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*LessonResource, error)
		Update(ctx context.Context, data *LessonResource) error
		Delete(ctx context.Context, id int64) error
	}

	defaultLessonResourceModel struct {
		conn  sqlx.SqlConn
		table string
	}

	LessonResource struct {
		Id         int64     `db:"id"`          // 主键ID
		LessonId   int64     `db:"lesson_id"`   // 课节ID
		QuestionId int64     `db:"question_id"` // 题目ID
		Sequence   float64   `db:"sequence"`    // 排序，正序，从1开始，默认跨度1
		CreatedAt  time.Time `db:"created_at"`  // 创建时间
		UpdatedAt  time.Time `db:"updated_at"`  // 更新时间
	}
)

func newLessonResourceModel(conn sqlx.SqlConn) *defaultLessonResourceModel {
	return &defaultLessonResourceModel{
		conn:  conn,
		table: "`kn_lesson_resource`",
	}
}

func (m *defaultLessonResourceModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultLessonResourceModel) FindOne(ctx context.Context, id int64) (*LessonResource, error) {

	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", lessonResourceRows, m.table)

	var resp LessonResource
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultLessonResourceModel) Insert(ctx context.Context, data *LessonResource) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, lessonResourceRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.LessonId, data.QuestionId, data.Sequence)
	return ret, err
}

func (m *defaultLessonResourceModel) Update(ctx context.Context, data *LessonResource) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, lessonResourceRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.LessonId, data.QuestionId, data.Sequence, data.Id)
	return err
}

func (m *defaultLessonResourceModel) TableName() string {
	return m.table
}
