// Code generated by goctl. DO NOT EDIT.

package knowledge

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	lessonFieldNames          = builder.RawFieldNames(&Lesson{})
	lessonRows                = strings.Join(lessonFieldNames, ",")
	lessonRowsExpectAutoSet   = strings.Join(stringx.Remove(lessonFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	lessonRowsWithPlaceHolder = strings.Join(stringx.Remove(lessonFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	lessonModel interface {
		Insert(ctx context.Context, data *Lesson) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Lesson, error)
		Update(ctx context.Context, data *Lesson) error
		Delete(ctx context.Context, id int64) error
	}

	defaultLessonModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Lesson struct {
		Id            int64     `db:"id"`              // 主键ID
		LessonNo      string    `db:"lesson_no"`       // 课节来源编号
		LessonGroupNo string    `db:"lesson_group_no"` // 课程组编号
		NodeType      int64     `db:"node_type"`       // 导入数据时使用，节点类型 1.小灶课 2.小语文 3.大语文
		ParentId      int64     `db:"parent_id"`       // 导入数据时使用，只有大语文才会用到，用作关联父子级
		Level         int64     `db:"level"`           // 难度等级 只有小灶课才会使用，1-4个等级
		Name          string    `db:"name"`            // 课节名称
		LessonType    int64     `db:"lesson_type"`     // 课程类型 1.主线课 2.月考  3.小灶课
		ReviewStatus  int64     `db:"review_status"`   // 审核状态 1.初始录入 2.审核中 3.审核通过 4.审核未通过 5.下架
		Remark        string    `db:"remark"`          // 备注
		CreatedAt     time.Time `db:"created_at"`      // 创建时间
		UpdatedAt     time.Time `db:"updated_at"`      // 更新时间
	}
)

func newLessonModel(conn sqlx.SqlConn) *defaultLessonModel {
	return &defaultLessonModel{
		conn:  conn,
		table: "`kn_lesson`",
	}
}

func (m *defaultLessonModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultLessonModel) FindOne(ctx context.Context, id int64) (*Lesson, error) {

	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", lessonRows, m.table)

	var resp Lesson
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultLessonModel) Insert(ctx context.Context, data *Lesson) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, lessonRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.LessonNo, data.LessonGroupNo, data.NodeType, data.ParentId, data.Level, data.Name, data.LessonType, data.ReviewStatus, data.Remark)
	return ret, err
}

func (m *defaultLessonModel) Update(ctx context.Context, data *Lesson) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, lessonRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.LessonNo, data.LessonGroupNo, data.NodeType, data.ParentId, data.Level, data.Name, data.LessonType, data.ReviewStatus, data.Remark, data.Id)
	return err
}

func (m *defaultLessonModel) TableName() string {
	return m.table
}
