// Code generated by goctl. DO NOT EDIT.

package knowledge

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	lessonQuestionTtsFieldNames          = builder.RawFieldNames(&LessonQuestionTts{})
	lessonQuestionTtsRows                = strings.Join(lessonQuestionTtsFieldNames, ",")
	lessonQuestionTtsRowsExpectAutoSet   = strings.Join(stringx.Remove(lessonQuestionTtsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	lessonQuestionTtsRowsWithPlaceHolder = strings.Join(stringx.Remove(lessonQuestionTtsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	lessonQuestionTtsModel interface {
		Insert(ctx context.Context, data *LessonQuestionTts) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*LessonQuestionTts, error)
		Update(ctx context.Context, data *LessonQuestionTts) error
		Delete(ctx context.Context, id int64) error
	}

	defaultLessonQuestionTtsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	LessonQuestionTts struct {
		Id         int64     `db:"id"`          // 主键ID
		QuestionId int64     `db:"question_id"` // 题目ID
		Content    string    `db:"content"`     // TTS文本
		Url        string    `db:"url"`         // TTS音频地址
		ApplyType  int64     `db:"apply_type"`  // 用途类型：1.开场白
		CreatedAt  time.Time `db:"created_at"`  // 创建时间
		UpdatedAt  time.Time `db:"updated_at"`  // 更新时间
	}
)

func newLessonQuestionTtsModel(conn sqlx.SqlConn) *defaultLessonQuestionTtsModel {
	return &defaultLessonQuestionTtsModel{
		conn:  conn,
		table: "`kn_lesson_question_tts`",
	}
}

func (m *defaultLessonQuestionTtsModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultLessonQuestionTtsModel) FindOne(ctx context.Context, id int64) (*LessonQuestionTts, error) {

	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", lessonQuestionTtsRows, m.table)

	var resp LessonQuestionTts
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultLessonQuestionTtsModel) Insert(ctx context.Context, data *LessonQuestionTts) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, lessonQuestionTtsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.QuestionId, data.Content, data.Url, data.ApplyType)
	return ret, err
}

func (m *defaultLessonQuestionTtsModel) Update(ctx context.Context, data *LessonQuestionTts) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, lessonQuestionTtsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.QuestionId, data.Content, data.Url, data.ApplyType, data.Id)
	return err
}

func (m *defaultLessonQuestionTtsModel) TableName() string {
	return m.table
}
