// Code generated by goctl. DO NOT EDIT.

package knowledge

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	lessonQuestionOptionFieldNames          = builder.RawFieldNames(&LessonQuestionOption{})
	lessonQuestionOptionRows                = strings.Join(lessonQuestionOptionFieldNames, ",")
	lessonQuestionOptionRowsExpectAutoSet   = strings.Join(stringx.Remove(lessonQuestionOptionFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	lessonQuestionOptionRowsWithPlaceHolder = strings.Join(stringx.Remove(lessonQuestionOptionFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	lessonQuestionOptionModel interface {
		Insert(ctx context.Context, data *LessonQuestionOption) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*LessonQuestionOption, error)
		Update(ctx context.Context, data *LessonQuestionOption) error
		Delete(ctx context.Context, id int64) error
	}

	defaultLessonQuestionOptionModel struct {
		conn  sqlx.SqlConn
		table string
	}

	LessonQuestionOption struct {
		Id               int64     `db:"id"`
		LessonQuestionId int64     `db:"lesson_question_id"` // 题目ID
		Sequence         int64     `db:"sequence"`           // 选项展示顺序[正序]
		OptionLabel      string    `db:"option_label"`       // 选项标签[例.A、B、C、D等]
		Content          string    `db:"content"`            // 选项内容,描述性内容或词汇ID
		IsAnswer         int64     `db:"is_answer"`          // 是否为正确答案 1.是 2.否
		CreatedAt        time.Time `db:"created_at"`         // 添加时间
		UpdatedAt        time.Time `db:"updated_at"`         // 修改时间
	}
)

func newLessonQuestionOptionModel(conn sqlx.SqlConn) *defaultLessonQuestionOptionModel {
	return &defaultLessonQuestionOptionModel{
		conn:  conn,
		table: "`kn_lesson_question_option`",
	}
}

func (m *defaultLessonQuestionOptionModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultLessonQuestionOptionModel) FindOne(ctx context.Context, id int64) (*LessonQuestionOption, error) {

	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", lessonQuestionOptionRows, m.table)

	var resp LessonQuestionOption
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultLessonQuestionOptionModel) Insert(ctx context.Context, data *LessonQuestionOption) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, lessonQuestionOptionRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.LessonQuestionId, data.Sequence, data.OptionLabel, data.Content, data.IsAnswer)
	return ret, err
}

func (m *defaultLessonQuestionOptionModel) Update(ctx context.Context, data *LessonQuestionOption) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, lessonQuestionOptionRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.LessonQuestionId, data.Sequence, data.OptionLabel, data.Content, data.IsAnswer, data.Id)
	return err
}

func (m *defaultLessonQuestionOptionModel) TableName() string {
	return m.table
}
