// Code generated by goctl. DO NOT EDIT.

package knowledge

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	materialFieldNames          = builder.RawFieldNames(&Material{})
	materialRows                = strings.Join(materialFieldNames, ",")
	materialRowsExpectAutoSet   = strings.Join(stringx.Remove(materialFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	materialRowsWithPlaceHolder = strings.Join(stringx.Remove(materialFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	materialModel interface {
		Insert(ctx context.Context, data *Material) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Material, error)
		Update(ctx context.Context, data *Material) error
		Delete(ctx context.Context, id int64) error
	}

	defaultMaterialModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Material struct {
		Id          int64          `db:"id"`           // 主键ID
		Title       string         `db:"title"`        // 素材名称
		Author      string         `db:"author"`       // 作者
		Source      string         `db:"source"`       // 素材来源
		Content     sql.NullString `db:"content"`      // 素材内容，比如选取的阅读素材片段
		Background  sql.NullString `db:"background"`   // 写作背景
		AuthorIntro sql.NullString `db:"author_intro"` // 作者介绍
		CreatedAt   time.Time      `db:"created_at"`   // 创建时间
		UpdatedAt   time.Time      `db:"updated_at"`   // 更新时间
	}
)

func newMaterialModel(conn sqlx.SqlConn) *defaultMaterialModel {
	return &defaultMaterialModel{
		conn:  conn,
		table: "`kn_material`",
	}
}

func (m *defaultMaterialModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultMaterialModel) FindOne(ctx context.Context, id int64) (*Material, error) {

	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", materialRows, m.table)

	var resp Material
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMaterialModel) Insert(ctx context.Context, data *Material) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, materialRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Title, data.Author, data.Source, data.Content, data.Background, data.AuthorIntro)
	return ret, err
}

func (m *defaultMaterialModel) Update(ctx context.Context, data *Material) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, materialRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Title, data.Author, data.Source, data.Content, data.Background, data.AuthorIntro, data.Id)
	return err
}

func (m *defaultMaterialModel) TableName() string {
	return m.table
}
