// Code generated by goctl. DO NOT EDIT.

package knowledge

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	questionFieldNames          = builder.RawFieldNames(&Question{})
	questionRows                = strings.Join(questionFieldNames, ",")
	questionRowsExpectAutoSet   = strings.Join(stringx.Remove(questionFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	questionRowsWithPlaceHolder = strings.Join(stringx.Remove(questionFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	questionModel interface {
		Insert(ctx context.Context, data *Question) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Question, error)
		Update(ctx context.Context, data *Question) error
		Delete(ctx context.Context, id int64) error
	}

	defaultQuestionModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Question struct {
		Id             int64          `db:"id"`               // 主键ID
		QuestionNo     string         `db:"question_no"`      // 题目编号
		BizType        int64          `db:"biz_type"`         // 业务类型 1.深度探测 2.爬天梯
		Type           int64          `db:"type"`             // 题目类型，1：选择；2：简答；
		ReviewStatus   int64          `db:"review_status"`    // 审核状态 1.初始录入 2.审核中 3.审核通过 4.审核未通过 5.下架
		Level          int64          `db:"level"`            // 等级
		HighLadderId   int64          `db:"high_ladder_id"`   // 天梯ID
		PrimaryPointId int64          `db:"primary_point_id"` // 知识点ID
		Material       sql.NullString `db:"material"`         // 题目素材，比如选取的阅读素材片段
		Ask            string         `db:"ask"`              // 问题
		Answer         sql.NullString `db:"answer"`           // 答案，针对简答题，用于答案判别
		Analysis       sql.NullString `db:"analysis"`         // 题目解析，用于答案判别
		Version        int64          `db:"version"`          // 版本
		CreatedBy      int64          `db:"created_by"`       // 创建者，程序导入为0，其他为操作者ID
		UpdatedBy      int64          `db:"updated_by"`       // 更新者，程序导入为0，其他为操作者ID
		EffectiveTime  time.Time      `db:"effective_time"`   // 有效期起始时间
		ExpiryTime     time.Time      `db:"expiry_time"`      // 有效期截止时间
		CreatedAt      time.Time      `db:"created_at"`       // 创建时间
		UpdatedAt      time.Time      `db:"updated_at"`       // 更新时间
	}
)

func newQuestionModel(conn sqlx.SqlConn) *defaultQuestionModel {
	return &defaultQuestionModel{
		conn:  conn,
		table: "`kn_question`",
	}
}

func (m *defaultQuestionModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultQuestionModel) FindOne(ctx context.Context, id int64) (*Question, error) {

	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", questionRows, m.table)

	var resp Question
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultQuestionModel) Insert(ctx context.Context, data *Question) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, questionRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.QuestionNo, data.BizType, data.Type, data.ReviewStatus, data.Level, data.HighLadderId, data.PrimaryPointId, data.Material, data.Ask, data.Answer, data.Analysis, data.Version, data.CreatedBy, data.UpdatedBy, data.EffectiveTime, data.ExpiryTime)
	return ret, err
}

func (m *defaultQuestionModel) Update(ctx context.Context, data *Question) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, questionRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.QuestionNo, data.BizType, data.Type, data.ReviewStatus, data.Level, data.HighLadderId, data.PrimaryPointId, data.Material, data.Ask, data.Answer, data.Analysis, data.Version, data.CreatedBy, data.UpdatedBy, data.EffectiveTime, data.ExpiryTime, data.Id)
	return err
}

func (m *defaultQuestionModel) TableName() string {
	return m.table
}
