// Code generated by goctl. DO NOT EDIT.

package knowledge

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	questionOptionFieldNames          = builder.RawFieldNames(&QuestionOption{})
	questionOptionRows                = strings.Join(questionOptionFieldNames, ",")
	questionOptionRowsExpectAutoSet   = strings.Join(stringx.Remove(questionOptionFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	questionOptionRowsWithPlaceHolder = strings.Join(stringx.Remove(questionOptionFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	questionOptionModel interface {
		Insert(ctx context.Context, data *QuestionOption) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*QuestionOption, error)
		Update(ctx context.Context, data *QuestionOption) error
		Delete(ctx context.Context, id int64) error
	}

	defaultQuestionOptionModel struct {
		conn  sqlx.SqlConn
		table string
	}

	QuestionOption struct {
		Id          int64     `db:"id"`
		QuestionId  int64     `db:"question_id"`  // 题目ID
		Sequence    int64     `db:"sequence"`     // 选项展示顺序[正序]
		OptionLabel string    `db:"option_label"` // 选项标签 例：A、B、C、D等
		Content     string    `db:"content"`      // 选项内容，描述性内容或词汇ID
		IsAnswer    int64     `db:"is_answer"`    // 是否为正确答案 1.是 2.否
		Analysis    string    `db:"analysis"`     // 选项TTS分析文本
		CreatedAt   time.Time `db:"created_at"`   // 添加时间
		UpdatedAt   time.Time `db:"updated_at"`   // 修改时间
	}
)

func newQuestionOptionModel(conn sqlx.SqlConn) *defaultQuestionOptionModel {
	return &defaultQuestionOptionModel{
		conn:  conn,
		table: "`kn_question_option`",
	}
}

func (m *defaultQuestionOptionModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultQuestionOptionModel) FindOne(ctx context.Context, id int64) (*QuestionOption, error) {

	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", questionOptionRows, m.table)

	var resp QuestionOption
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultQuestionOptionModel) Insert(ctx context.Context, data *QuestionOption) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, questionOptionRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.QuestionId, data.Sequence, data.OptionLabel, data.Content, data.IsAnswer, data.Analysis)
	return ret, err
}

func (m *defaultQuestionOptionModel) Update(ctx context.Context, data *QuestionOption) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, questionOptionRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.QuestionId, data.Sequence, data.OptionLabel, data.Content, data.IsAnswer, data.Analysis, data.Id)
	return err
}

func (m *defaultQuestionOptionModel) TableName() string {
	return m.table
}
