// Code generated by goctl. DO NOT EDIT.

package knowledge

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	questionPointFieldNames          = builder.RawFieldNames(&QuestionPoint{})
	questionPointRows                = strings.Join(questionPointFieldNames, ",")
	questionPointRowsExpectAutoSet   = strings.Join(stringx.Remove(questionPointFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	questionPointRowsWithPlaceHolder = strings.Join(stringx.Remove(questionPointFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	questionPointModel interface {
		Insert(ctx context.Context, data *QuestionPoint) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*QuestionPoint, error)
		Update(ctx context.Context, data *QuestionPoint) error
		Delete(ctx context.Context, id int64) error
	}

	defaultQuestionPointModel struct {
		conn  sqlx.SqlConn
		table string
	}

	QuestionPoint struct {
		Id         int64     `db:"id"`          // 主键ID
		QuestionId int64     `db:"question_id"` // 问题ID
		PointId    int64     `db:"point_id"`    // 知识点ID
		IsPrimary  int64     `db:"is_primary"`  // 是否为主知识点 1.是 2.否
		CreatedAt  time.Time `db:"created_at"`  // 创建时间
		UpdatedAt  time.Time `db:"updated_at"`  // 更新时间
	}
)

func newQuestionPointModel(conn sqlx.SqlConn) *defaultQuestionPointModel {
	return &defaultQuestionPointModel{
		conn:  conn,
		table: "`kn_question_point`",
	}
}

func (m *defaultQuestionPointModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultQuestionPointModel) FindOne(ctx context.Context, id int64) (*QuestionPoint, error) {

	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", questionPointRows, m.table)

	var resp QuestionPoint
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultQuestionPointModel) Insert(ctx context.Context, data *QuestionPoint) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, questionPointRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.QuestionId, data.PointId, data.IsPrimary)
	return ret, err
}

func (m *defaultQuestionPointModel) Update(ctx context.Context, data *QuestionPoint) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, questionPointRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.QuestionId, data.PointId, data.IsPrimary, data.Id)
	return err
}

func (m *defaultQuestionPointModel) TableName() string {
	return m.table
}
