// Code generated by goctl. DO NOT EDIT.

package benefit

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	benefitsGroupFieldNames          = builder.RawFieldNames(&BenefitsGroup{})
	benefitsGroupRows                = strings.Join(benefitsGroupFieldNames, ",")
	benefitsGroupRowsExpectAutoSet   = strings.Join(stringx.Remove(benefitsGroupFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	benefitsGroupRowsWithPlaceHolder = strings.Join(stringx.Remove(benefitsGroupFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	benefitsGroupModel interface {
		Insert(ctx context.Context, data *BenefitsGroup) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*BenefitsGroup, error)
		Update(ctx context.Context, data *BenefitsGroup) error
		Delete(ctx context.Context, id int64) error
	}

	defaultBenefitsGroupModel struct {
		conn  sqlx.SqlConn
		table string
	}

	BenefitsGroup struct {
		Id        int64     `db:"id"`         // 主键ID
		Name      string    `db:"name"`       // 权益名称
		Code      string    `db:"code"`       // 编码
		UserType  int64     `db:"user_type"`  // 用户类型 1.单个子账号 2.主账号
		Type      int64     `db:"type"`       // 1.单品权益 2.组合权益
		Intro     string    `db:"intro"`      // 权益介绍
		CreatedAt time.Time `db:"created_at"` // 创建时间
		UpdatedAt time.Time `db:"updated_at"` // 更新时间
	}
)

func newBenefitsGroupModel(conn sqlx.SqlConn) *defaultBenefitsGroupModel {
	return &defaultBenefitsGroupModel{
		conn:  conn,
		table: "`bt_benefits_group`",
	}
}

func (m *defaultBenefitsGroupModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultBenefitsGroupModel) FindOne(ctx context.Context, id int64) (*BenefitsGroup, error) {

	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", benefitsGroupRows, m.table)

	var resp BenefitsGroup
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultBenefitsGroupModel) Insert(ctx context.Context, data *BenefitsGroup) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, benefitsGroupRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Name, data.Code, data.UserType, data.Type, data.Intro)
	return ret, err
}

func (m *defaultBenefitsGroupModel) Update(ctx context.Context, data *BenefitsGroup) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, benefitsGroupRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Name, data.Code, data.UserType, data.Type, data.Intro, data.Id)
	return err
}

func (m *defaultBenefitsGroupModel) TableName() string {
	return m.table
}
