// Code generated by goctl. DO NOT EDIT.

package benefit

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	benefitsGroupDetailFieldNames          = builder.RawFieldNames(&BenefitsGroupDetail{})
	benefitsGroupDetailRows                = strings.Join(benefitsGroupDetailFieldNames, ",")
	benefitsGroupDetailRowsExpectAutoSet   = strings.Join(stringx.Remove(benefitsGroupDetailFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	benefitsGroupDetailRowsWithPlaceHolder = strings.Join(stringx.Remove(benefitsGroupDetailFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	benefitsGroupDetailModel interface {
		Insert(ctx context.Context, data *BenefitsGroupDetail) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*BenefitsGroupDetail, error)
		Update(ctx context.Context, data *BenefitsGroupDetail) error
		Delete(ctx context.Context, id int64) error
	}

	defaultBenefitsGroupDetailModel struct {
		conn  sqlx.SqlConn
		table string
	}

	BenefitsGroupDetail struct {
		Id                 int64     `db:"id"`                   // 主键ID
		BenefitsGroupId    int64     `db:"benefits_group_id"`    // 权益组表ID
		BenefitsResourceId int64     `db:"benefits_resource_id"` // 权益资源表ID
		Kind               int64     `db:"kind"`                 // 权益类别，1.永久 2.时效的 3.时间段
		FromTime           time.Time `db:"from_time"`            // 开始时间
		Days               int64     `db:"days"`                 // 生效天数，-1 代表永久
		CreatedAt          time.Time `db:"created_at"`           // 创建时间
		UpdatedAt          time.Time `db:"updated_at"`           // 更新时间
	}
)

func newBenefitsGroupDetailModel(conn sqlx.SqlConn) *defaultBenefitsGroupDetailModel {
	return &defaultBenefitsGroupDetailModel{
		conn:  conn,
		table: "`bt_benefits_group_detail`",
	}
}

func (m *defaultBenefitsGroupDetailModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultBenefitsGroupDetailModel) FindOne(ctx context.Context, id int64) (*BenefitsGroupDetail, error) {

	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", benefitsGroupDetailRows, m.table)

	var resp BenefitsGroupDetail
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultBenefitsGroupDetailModel) Insert(ctx context.Context, data *BenefitsGroupDetail) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, benefitsGroupDetailRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.BenefitsGroupId, data.BenefitsResourceId, data.Kind, data.FromTime, data.Days)
	return ret, err
}

func (m *defaultBenefitsGroupDetailModel) Update(ctx context.Context, data *BenefitsGroupDetail) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, benefitsGroupDetailRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.BenefitsGroupId, data.BenefitsResourceId, data.Kind, data.FromTime, data.Days, data.Id)
	return err
}

func (m *defaultBenefitsGroupDetailModel) TableName() string {
	return m.table
}
