// Code generated by goctl. DO NOT EDIT.

package benefit

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	benefitsUserRecordFieldNames          = builder.RawFieldNames(&BenefitsUserRecord{})
	benefitsUserRecordRows                = strings.Join(benefitsUserRecordFieldNames, ",")
	benefitsUserRecordRowsExpectAutoSet   = strings.Join(stringx.Remove(benefitsUserRecordFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	benefitsUserRecordRowsWithPlaceHolder = strings.Join(stringx.Remove(benefitsUserRecordFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	benefitsUserRecordModel interface {
		Insert(ctx context.Context, data *BenefitsUserRecord) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*BenefitsUserRecord, error)
		Update(ctx context.Context, data *BenefitsUserRecord) error
		Delete(ctx context.Context, id int64) error
	}

	defaultBenefitsUserRecordModel struct {
		conn  sqlx.SqlConn
		table string
	}

	BenefitsUserRecord struct {
		Id                 int64     `db:"id"`                   // 主键ID
		UserId             int64     `db:"user_id"`              // 用户ID
		Type               int64     `db:"type"`                 // 权益变更类型 1: 发放 2: 回收
		OrderId            string    `db:"order_id"`             // 订单ID，已废弃
		OrderNo            string    `db:"order_no"`             // 订单号
		BenefitsResourceId int64     `db:"benefits_resource_id"` // 权益资源表ID
		UserBenefitsId     int64     `db:"user_benefits_id"`     // 用户权益表
		Source             int64     `db:"source"`               // 来源 1：内部员工；2：渠道三部 3：中台；4：蓝V企业店； 5：产品运营
		CreatedAt          time.Time `db:"created_at"`           // 创建时间
		UpdatedAt          time.Time `db:"updated_at"`           // 更新时间
	}
)

func newBenefitsUserRecordModel(conn sqlx.SqlConn) *defaultBenefitsUserRecordModel {
	return &defaultBenefitsUserRecordModel{
		conn:  conn,
		table: "`bt_benefits_user_record`",
	}
}

func (m *defaultBenefitsUserRecordModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultBenefitsUserRecordModel) FindOne(ctx context.Context, id int64) (*BenefitsUserRecord, error) {

	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", benefitsUserRecordRows, m.table)

	var resp BenefitsUserRecord
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultBenefitsUserRecordModel) Insert(ctx context.Context, data *BenefitsUserRecord) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, benefitsUserRecordRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.Type, data.OrderId, data.OrderNo, data.BenefitsResourceId, data.UserBenefitsId, data.Source)
	return ret, err
}

func (m *defaultBenefitsUserRecordModel) Update(ctx context.Context, data *BenefitsUserRecord) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, benefitsUserRecordRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserId, data.Type, data.OrderId, data.OrderNo, data.BenefitsResourceId, data.UserBenefitsId, data.Source, data.Id)
	return err
}

func (m *defaultBenefitsUserRecordModel) TableName() string {
	return m.table
}
