// Code generated by goctl. DO NOT EDIT.

package benefit

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	benefitsDetailFieldNames          = builder.RawFieldNames(&BenefitsDetail{})
	benefitsDetailRows                = strings.Join(benefitsDetailFieldNames, ",")
	benefitsDetailRowsExpectAutoSet   = strings.Join(stringx.Remove(benefitsDetailFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	benefitsDetailRowsWithPlaceHolder = strings.Join(stringx.Remove(benefitsDetailFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	benefitsDetailModel interface {
		Insert(ctx context.Context, data *BenefitsDetail) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*BenefitsDetail, error)
		Update(ctx context.Context, data *BenefitsDetail) error
		Delete(ctx context.Context, id int64) error
	}

	defaultBenefitsDetailModel struct {
		conn  sqlx.SqlConn
		table string
	}

	BenefitsDetail struct {
		Id                 int64     `db:"id"`                   // 主键ID
		BenefitsResourceId int64     `db:"benefits_resource_id"` // 权益资源表ID
		ResourceType       int64     `db:"resource_type"`        // 资源类型 11.快解知识点 12.快解题单元 13.快解全部 21.阅读理解关卡 22.阅读理解全部 31.风的颜色主题 32.风的颜色全部
		ResourceId         int64     `db:"resource_id"`          // 资源ID,仅对 resource_type = 1 有效
		Status             int64     `db:"status"`               // 权益状态 1.启用 2.禁用
		CreatedAt          time.Time `db:"created_at"`           // 创建时间
		UpdatedAt          time.Time `db:"updated_at"`           // 更新时间
	}
)

func newBenefitsDetailModel(conn sqlx.SqlConn) *defaultBenefitsDetailModel {
	return &defaultBenefitsDetailModel{
		conn:  conn,
		table: "`bt_benefits_detail`",
	}
}

func (m *defaultBenefitsDetailModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultBenefitsDetailModel) FindOne(ctx context.Context, id int64) (*BenefitsDetail, error) {

	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", benefitsDetailRows, m.table)

	var resp BenefitsDetail
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultBenefitsDetailModel) Insert(ctx context.Context, data *BenefitsDetail) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, benefitsDetailRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.BenefitsResourceId, data.ResourceType, data.ResourceId, data.Status)
	return ret, err
}

func (m *defaultBenefitsDetailModel) Update(ctx context.Context, data *BenefitsDetail) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, benefitsDetailRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.BenefitsResourceId, data.ResourceType, data.ResourceId, data.Status, data.Id)
	return err
}

func (m *defaultBenefitsDetailModel) TableName() string {
	return m.table
}
