// Code generated by goctl. DO NOT EDIT.

package benefit

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	benefitsNotifyLogFieldNames          = builder.RawFieldNames(&BenefitsNotifyLog{})
	benefitsNotifyLogRows                = strings.Join(benefitsNotifyLogFieldNames, ",")
	benefitsNotifyLogRowsExpectAutoSet   = strings.Join(stringx.Remove(benefitsNotifyLogFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	benefitsNotifyLogRowsWithPlaceHolder = strings.Join(stringx.Remove(benefitsNotifyLogFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	benefitsNotifyLogModel interface {
		Insert(ctx context.Context, data *BenefitsNotifyLog) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*BenefitsNotifyLog, error)
		Update(ctx context.Context, data *BenefitsNotifyLog) error
		Delete(ctx context.Context, id int64) error
	}

	defaultBenefitsNotifyLogModel struct {
		conn  sqlx.SqlConn
		table string
	}

	BenefitsNotifyLog struct {
		Id        int64          `db:"id"`         // 主键ID
		OrderNo   string         `db:"order_no"`   // 订单编号
		Source    int64          `db:"source"`     // 来源 1.豆伴匠
		Data      sql.NullString `db:"data"`       // 通知原始数据
		CreatedAt time.Time      `db:"created_at"` // 创建时间
		UpdatedAt time.Time      `db:"updated_at"` // 更新时间
	}
)

func newBenefitsNotifyLogModel(conn sqlx.SqlConn) *defaultBenefitsNotifyLogModel {
	return &defaultBenefitsNotifyLogModel{
		conn:  conn,
		table: "`bt_benefits_notify_log`",
	}
}

func (m *defaultBenefitsNotifyLogModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultBenefitsNotifyLogModel) FindOne(ctx context.Context, id int64) (*BenefitsNotifyLog, error) {

	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", benefitsNotifyLogRows, m.table)

	var resp BenefitsNotifyLog
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultBenefitsNotifyLogModel) Insert(ctx context.Context, data *BenefitsNotifyLog) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, benefitsNotifyLogRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.OrderNo, data.Source, data.Data)
	return ret, err
}

func (m *defaultBenefitsNotifyLogModel) Update(ctx context.Context, data *BenefitsNotifyLog) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, benefitsNotifyLogRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.OrderNo, data.Source, data.Data, data.Id)
	return err
}

func (m *defaultBenefitsNotifyLogModel) TableName() string {
	return m.table
}
