// Code generated by goctl. DO NOT EDIT.

package benefit

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	benefitsResourceFieldNames          = builder.RawFieldNames(&BenefitsResource{})
	benefitsResourceRows                = strings.Join(benefitsResourceFieldNames, ",")
	benefitsResourceRowsExpectAutoSet   = strings.Join(stringx.Remove(benefitsResourceFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	benefitsResourceRowsWithPlaceHolder = strings.Join(stringx.Remove(benefitsResourceFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	benefitsResourceModel interface {
		Insert(ctx context.Context, data *BenefitsResource) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*BenefitsResource, error)
		Update(ctx context.Context, data *BenefitsResource) error
		Delete(ctx context.Context, id int64) error
	}

	defaultBenefitsResourceModel struct {
		conn  sqlx.SqlConn
		table string
	}

	BenefitsResource struct {
		Id            int64          `db:"id"`              // 主键ID
		Name          string         `db:"name"`            // 权益名称
		Type          int64          `db:"type"`            // 权益类型 1.快解题 2.关卡 3.风的颜色 4.学习规划
		IsLimitedFree int64          `db:"is_limited_free"` // 是否限免，1.不是 2.是
		Description   sql.NullString `db:"description"`     // 权益描述
		Status        int64          `db:"status"`          // 权益状态 1.启用 2.禁用
		CreatedAt     time.Time      `db:"created_at"`      // 创建时间
		UpdatedAt     time.Time      `db:"updated_at"`      // 更新时间
	}
)

func newBenefitsResourceModel(conn sqlx.SqlConn) *defaultBenefitsResourceModel {
	return &defaultBenefitsResourceModel{
		conn:  conn,
		table: "`bt_benefits_resource`",
	}
}

func (m *defaultBenefitsResourceModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultBenefitsResourceModel) FindOne(ctx context.Context, id int64) (*BenefitsResource, error) {

	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", benefitsResourceRows, m.table)

	var resp BenefitsResource
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultBenefitsResourceModel) Insert(ctx context.Context, data *BenefitsResource) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, benefitsResourceRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Name, data.Type, data.IsLimitedFree, data.Description, data.Status)
	return ret, err
}

func (m *defaultBenefitsResourceModel) Update(ctx context.Context, data *BenefitsResource) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, benefitsResourceRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Name, data.Type, data.IsLimitedFree, data.Description, data.Status, data.Id)
	return err
}

func (m *defaultBenefitsResourceModel) TableName() string {
	return m.table
}
