// Code generated by goctl. DO NOT EDIT.

package benefit

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	channelOrderFieldNames          = builder.RawFieldNames(&ChannelOrder{})
	channelOrderRows                = strings.Join(channelOrderFieldNames, ",")
	channelOrderRowsExpectAutoSet   = strings.Join(stringx.Remove(channelOrderFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	channelOrderRowsWithPlaceHolder = strings.Join(stringx.Remove(channelOrderFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	channelOrderModel interface {
		Insert(ctx context.Context, data *ChannelOrder) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*ChannelOrder, error)
		Update(ctx context.Context, data *ChannelOrder) error
		Delete(ctx context.Context, id int64) error
	}

	defaultChannelOrderModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ChannelOrder struct {
		Id              int64     `db:"id"`                // 主键ID
		OrderNo         string    `db:"order_no"`          // 外部订单号
		BenefitsGroupId int64     `db:"benefits_group_id"` // 权益类别表ID
		MaskPhone       string    `db:"mask_phone"`        // 脱敏手机号
		UserType        int64     `db:"user_type"`         // 用户类型 1.单个子账号 2.主账号
		OrderType       int64     `db:"order_type"`        // 订单类型 1.发放 2.回收
		Source          int64     `db:"source"`            // 来源 1.内部员工 2.渠道三部 3.中台 4.蓝V企业店 5.产品运营
		CreatedAt       time.Time `db:"created_at"`        // 创建时间
		UpdatedAt       time.Time `db:"updated_at"`        // 更新时间
	}
)

func newChannelOrderModel(conn sqlx.SqlConn) *defaultChannelOrderModel {
	return &defaultChannelOrderModel{
		conn:  conn,
		table: "`bt_channel_order`",
	}
}

func (m *defaultChannelOrderModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultChannelOrderModel) FindOne(ctx context.Context, id int64) (*ChannelOrder, error) {

	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", channelOrderRows, m.table)

	var resp ChannelOrder
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultChannelOrderModel) Insert(ctx context.Context, data *ChannelOrder) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, channelOrderRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.OrderNo, data.BenefitsGroupId, data.MaskPhone, data.UserType, data.OrderType, data.Source)
	return ret, err
}

func (m *defaultChannelOrderModel) Update(ctx context.Context, data *ChannelOrder) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, channelOrderRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.OrderNo, data.BenefitsGroupId, data.MaskPhone, data.UserType, data.OrderType, data.Source, data.Id)
	return err
}

func (m *defaultChannelOrderModel) TableName() string {
	return m.table
}
