// Code generated by goctl. DO NOT EDIT.

package benefit

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	channelSubOrderFieldNames          = builder.RawFieldNames(&ChannelSubOrder{})
	channelSubOrderRows                = strings.Join(channelSubOrderFieldNames, ",")
	channelSubOrderRowsExpectAutoSet   = strings.Join(stringx.Remove(channelSubOrderFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	channelSubOrderRowsWithPlaceHolder = strings.Join(stringx.Remove(channelSubOrderFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	channelSubOrderModel interface {
		Insert(ctx context.Context, data *ChannelSubOrder) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*ChannelSubOrder, error)
		Update(ctx context.Context, data *ChannelSubOrder) error
		Delete(ctx context.Context, id int64) error
	}

	defaultChannelSubOrderModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ChannelSubOrder struct {
		Id                    int64     `db:"id"`                       // 主键ID
		ChannelOrderId        int64     `db:"channel_order_id"`         // 渠道订单表ID
		BaseUserId            int64     `db:"base_user_id"`             // 主用户ID
		UserId                int64     `db:"user_id"`                  // 子用户ID
		BenefitsResourceId    int64     `db:"benefits_resource_id"`     // 权益资源表ID
		BenefitsGroupDetailId int64     `db:"benefits_group_detail_id"` // 权益组详情表ID
		Status                int64     `db:"status"`                   // 订单状态.1.发放中 2.已发放 3.回收中 4.已回收
		CreatedAt             time.Time `db:"created_at"`               // 创建时间
		UpdatedAt             time.Time `db:"updated_at"`               // 更新时间
	}
)

func newChannelSubOrderModel(conn sqlx.SqlConn) *defaultChannelSubOrderModel {
	return &defaultChannelSubOrderModel{
		conn:  conn,
		table: "`bt_channel_sub_order`",
	}
}

func (m *defaultChannelSubOrderModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultChannelSubOrderModel) FindOne(ctx context.Context, id int64) (*ChannelSubOrder, error) {

	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", channelSubOrderRows, m.table)

	var resp ChannelSubOrder
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultChannelSubOrderModel) Insert(ctx context.Context, data *ChannelSubOrder) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, channelSubOrderRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ChannelOrderId, data.BaseUserId, data.UserId, data.BenefitsResourceId, data.BenefitsGroupDetailId, data.Status)
	return ret, err
}

func (m *defaultChannelSubOrderModel) Update(ctx context.Context, data *ChannelSubOrder) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, channelSubOrderRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.ChannelOrderId, data.BaseUserId, data.UserId, data.BenefitsResourceId, data.BenefitsGroupDetailId, data.Status, data.Id)
	return err
}

func (m *defaultChannelSubOrderModel) TableName() string {
	return m.table
}
