// Code generated by goctl. DO NOT EDIT.

package benefit

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userBenefitsDetailFieldNames          = builder.RawFieldNames(&UserBenefitsDetail{})
	userBenefitsDetailRows                = strings.Join(userBenefitsDetailFieldNames, ",")
	userBenefitsDetailRowsExpectAutoSet   = strings.Join(stringx.Remove(userBenefitsDetailFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userBenefitsDetailRowsWithPlaceHolder = strings.Join(stringx.Remove(userBenefitsDetailFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	userBenefitsDetailModel interface {
		Insert(ctx context.Context, data *UserBenefitsDetail) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*UserBenefitsDetail, error)
		FindOneByUserIdBenefitsResourceId(ctx context.Context, userId int64, benefitsResourceId int64) (*UserBenefitsDetail, error)
		Update(ctx context.Context, data *UserBenefitsDetail) error
		Delete(ctx context.Context, id int64) error
	}

	defaultUserBenefitsDetailModel struct {
		conn  sqlx.SqlConn
		table string
	}

	UserBenefitsDetail struct {
		Id                 int64     `db:"id"`                   // 主键ID
		UserId             int64     `db:"user_id"`              // 用户ID
		BenefitsResourceId int64     `db:"benefits_resource_id"` // 权益资源表ID
		Status             int64     `db:"status"`               // 权益状态 1: 启用 2: 禁用
		FromTime           time.Time `db:"from_time"`            // 创建时间
		EndTime            time.Time `db:"end_time"`             // 结束时间
		CreatedAt          time.Time `db:"created_at"`           // 创建时间
		UpdatedAt          time.Time `db:"updated_at"`           // 更新时间
	}
)

func newUserBenefitsDetailModel(conn sqlx.SqlConn) *defaultUserBenefitsDetailModel {
	return &defaultUserBenefitsDetailModel{
		conn:  conn,
		table: "`us_user_benefits_detail`",
	}
}

func (m *defaultUserBenefitsDetailModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUserBenefitsDetailModel) FindOne(ctx context.Context, id int64) (*UserBenefitsDetail, error) {

	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userBenefitsDetailRows, m.table)

	var resp UserBenefitsDetail
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserBenefitsDetailModel) FindOneByUserIdBenefitsResourceId(ctx context.Context, userId int64, benefitsResourceId int64) (*UserBenefitsDetail, error) {
	var resp UserBenefitsDetail

	query := fmt.Sprintf("select %s from %s where `user_id` = ? and `benefits_resource_id` = ? limit 1", userBenefitsDetailRows, m.table)

	err := m.conn.QueryRowCtx(ctx, &resp, query, userId, benefitsResourceId)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserBenefitsDetailModel) Insert(ctx context.Context, data *UserBenefitsDetail) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, userBenefitsDetailRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.BenefitsResourceId, data.Status, data.FromTime, data.EndTime)
	return ret, err
}

func (m *defaultUserBenefitsDetailModel) Update(ctx context.Context, newData *UserBenefitsDetail) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userBenefitsDetailRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.UserId, newData.BenefitsResourceId, newData.Status, newData.FromTime, newData.EndTime, newData.Id)
	return err
}

func (m *defaultUserBenefitsDetailModel) TableName() string {
	return m.table
}
