// Code generated by goctl. DO NOT EDIT.

package supertrain

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	chapterTaskFieldNames          = builder.RawFieldNames(&ChapterTask{})
	chapterTaskRows                = strings.Join(chapterTaskFieldNames, ",")
	chapterTaskRowsExpectAutoSet   = strings.Join(stringx.Remove(chapterTaskFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	chapterTaskRowsWithPlaceHolder = strings.Join(stringx.Remove(chapterTaskFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	chapterTaskModel interface {
		Insert(ctx context.Context, data *ChapterTask) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*ChapterTask, error)
		FindOneByTaskNo(ctx context.Context, taskNo string) (*ChapterTask, error)
		Update(ctx context.Context, data *ChapterTask) error
		Delete(ctx context.Context, id int64) error
	}

	defaultChapterTaskModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ChapterTask struct {
		Id              int64     `db:"id"`                // 主键
		TaskNo          string    `db:"task_no"`           // 任务编号
		Title           string    `db:"title"`             // 标题
		Subtitle        string    `db:"subtitle"`          // 子标题
		Description     string    `db:"description"`       // 描述
		CourseId        int64     `db:"course_id"`         // 课堂id
		CourseChapterId int64     `db:"course_chapter_id"` // 章节id
		ProgressPrefix  string    `db:"progress_prefix"`   // 进度前缀、时空稳定值、时空通道已建立等
		Extra           string    `db:"extra"`             // 拓展字段，用于存json
		Type            int64     `db:"type"`              // 类型：1.文章段落 2.身份卡 3.文章总结 4.时空长廊 200.主线任务 201.副本任务
		Sequence        float64   `db:"sequence"`          // 排序
		CreatedAt       time.Time `db:"created_at"`        // 创建时间
		UpdatedAt       time.Time `db:"updated_at"`        // 更新时间
		Deleted         int64     `db:"deleted"`           // 是否删除 1.未删除 2.已删除
	}
)

func newChapterTaskModel(conn sqlx.SqlConn) *defaultChapterTaskModel {
	return &defaultChapterTaskModel{
		conn:  conn,
		table: "`ac_chapter_task`",
	}
}

func (m *defaultChapterTaskModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultChapterTaskModel) FindOne(ctx context.Context, id int64) (*ChapterTask, error) {

	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", chapterTaskRows, m.table)

	var resp ChapterTask
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultChapterTaskModel) FindOneByTaskNo(ctx context.Context, taskNo string) (*ChapterTask, error) {
	var resp ChapterTask

	query := fmt.Sprintf("select %s from %s where `task_no` = ? limit 1", chapterTaskRows, m.table)

	err := m.conn.QueryRowCtx(ctx, &resp, query, taskNo)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultChapterTaskModel) Insert(ctx context.Context, data *ChapterTask) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, chapterTaskRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.TaskNo, data.Title, data.Subtitle, data.Description, data.CourseId, data.CourseChapterId, data.ProgressPrefix, data.Extra, data.Type, data.Sequence, data.Deleted)
	return ret, err
}

func (m *defaultChapterTaskModel) Update(ctx context.Context, newData *ChapterTask) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, chapterTaskRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.TaskNo, newData.Title, newData.Subtitle, newData.Description, newData.CourseId, newData.CourseChapterId, newData.ProgressPrefix, newData.Extra, newData.Type, newData.Sequence, newData.Deleted, newData.Id)
	return err
}

func (m *defaultChapterTaskModel) TableName() string {
	return m.table
}
