// Code generated by goctl. DO NOT EDIT.

package supertrain

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	courseChapterFieldNames          = builder.RawFieldNames(&CourseChapter{})
	courseChapterRows                = strings.Join(courseChapterFieldNames, ",")
	courseChapterRowsExpectAutoSet   = strings.Join(stringx.Remove(courseChapterFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	courseChapterRowsWithPlaceHolder = strings.Join(stringx.Remove(courseChapterFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	courseChapterModel interface {
		Insert(ctx context.Context, data *CourseChapter) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*CourseChapter, error)
		FindOneByChapterNo(ctx context.Context, chapterNo string) (*CourseChapter, error)
		Update(ctx context.Context, data *CourseChapter) error
		Delete(ctx context.Context, id int64) error
	}

	defaultCourseChapterModel struct {
		conn  sqlx.SqlConn
		table string
	}

	CourseChapter struct {
		Id         int64          `db:"id"`          // 主键
		ChapterNo  string         `db:"chapter_no"`  // 章节编号
		Type       int64          `db:"type"`        // 1 任务 2 文章
		CourseId   int64          `db:"course_id"`   // 课程ID
		Name       string         `db:"name"`        // 标题，后续不再维护
		Title      string         `db:"title"`       // 精简版标题
		Image      string         `db:"image"`       // 课程封面图
		Intro      string         `db:"intro"`       // 课程介绍
		Index      int64          `db:"index"`       // 圈数
		GuideVideo string         `db:"guide_video"` // 引导视频
		Sequence   float64        `db:"sequence"`    // 系列序号
		TeacherId  int64          `db:"teacher_id"`  // 老师id
		Status     int64          `db:"status"`      // 状态 1.初始录入 2.审核中 3.审核通过 4.审核未通过 5.下架
		CanLearn   int64          `db:"can_learn"`   // 是否能学 1.可以 2.不可以
		IsNew      int64          `db:"is_new"`      // 是否上新 1.否 2.是
		Extra      sql.NullString `db:"extra"`       // 拓展字段，用于存json
		CreatedAt  time.Time      `db:"created_at"`  // 创建时间
		UpdatedAt  time.Time      `db:"updated_at"`  // 更新时间
	}
)

func newCourseChapterModel(conn sqlx.SqlConn) *defaultCourseChapterModel {
	return &defaultCourseChapterModel{
		conn:  conn,
		table: "`ac_course_chapter`",
	}
}

func (m *defaultCourseChapterModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultCourseChapterModel) FindOne(ctx context.Context, id int64) (*CourseChapter, error) {

	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", courseChapterRows, m.table)

	var resp CourseChapter
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCourseChapterModel) FindOneByChapterNo(ctx context.Context, chapterNo string) (*CourseChapter, error) {
	var resp CourseChapter

	query := fmt.Sprintf("select %s from %s where `chapter_no` = ? limit 1", courseChapterRows, m.table)

	err := m.conn.QueryRowCtx(ctx, &resp, query, chapterNo)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCourseChapterModel) Insert(ctx context.Context, data *CourseChapter) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, courseChapterRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ChapterNo, data.Type, data.CourseId, data.Name, data.Title, data.Image, data.Intro, data.Index, data.GuideVideo, data.Sequence, data.TeacherId, data.Status, data.CanLearn, data.IsNew, data.Extra)
	return ret, err
}

func (m *defaultCourseChapterModel) Update(ctx context.Context, newData *CourseChapter) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, courseChapterRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.ChapterNo, newData.Type, newData.CourseId, newData.Name, newData.Title, newData.Image, newData.Intro, newData.Index, newData.GuideVideo, newData.Sequence, newData.TeacherId, newData.Status, newData.CanLearn, newData.IsNew, newData.Extra, newData.Id)
	return err
}

func (m *defaultCourseChapterModel) TableName() string {
	return m.table
}
