// Code generated by goctl. DO NOT EDIT.

package supertrain

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	courseFieldNames          = builder.RawFieldNames(&Course{})
	courseRows                = strings.Join(courseFieldNames, ",")
	courseRowsExpectAutoSet   = strings.Join(stringx.Remove(courseFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	courseRowsWithPlaceHolder = strings.Join(stringx.Remove(courseFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	courseModel interface {
		Insert(ctx context.Context, data *Course) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Course, error)
		Update(ctx context.Context, data *Course) error
		Delete(ctx context.Context, id int64) error
	}

	defaultCourseModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Course struct {
		Id         int64          `db:"id"`          // 主键
		CourseNo   string         `db:"course_no"`   // 课程编号
		UseCases   int64          `db:"use_cases"`   // 应用场景：1.练习 2.直播互动
		CourseType int64          `db:"course_type"` // 课程类型 1.超练作文慢练 2.超练作文快练 3.超练阅读
		Version    int64          `db:"version"`     // 版本号
		Name       string         `db:"name"`        // 课程名称
		LessonName string         `db:"lesson_name"` // 课节名称
		Subject    int64          `db:"subject"`     // 学科 1.语文
		Unit       string         `db:"unit"`        // 单元
		TeacherId  int64          `db:"teacher_id"`  // 老师名称
		Image      string         `db:"image"`       // 课程封面图
		Intro      string         `db:"intro"`       // 课程介绍
		OpenTime   time.Time      `db:"open_time"`   // 开放时间
		Type       int64          `db:"type"`        // 类型 1.试听课 2.付费课
		Status     int64          `db:"status"`      // 状态 1.初始录入 2.审核中 3.审核通过 4.审核未通过 5.下架
		Level      sql.NullString `db:"level"`       // 难度
		Remark     string         `db:"remark"`      // 备注
		Extra      sql.NullString `db:"extra"`       // 拓展字段，用于存json
		Sequence   float64        `db:"sequence"`    // 排序
		CreatedAt  time.Time      `db:"created_at"`  // 创建时间
		UpdatedAt  time.Time      `db:"updated_at"`  // 更新时间
	}
)

func newCourseModel(conn sqlx.SqlConn) *defaultCourseModel {
	return &defaultCourseModel{
		conn:  conn,
		table: "`ac_course`",
	}
}

func (m *defaultCourseModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultCourseModel) FindOne(ctx context.Context, id int64) (*Course, error) {

	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", courseRows, m.table)

	var resp Course
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCourseModel) Insert(ctx context.Context, data *Course) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, courseRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.CourseNo, data.UseCases, data.CourseType, data.Version, data.Name, data.LessonName, data.Subject, data.Unit, data.TeacherId, data.Image, data.Intro, data.OpenTime, data.Type, data.Status, data.Level, data.Remark, data.Extra, data.Sequence)
	return ret, err
}

func (m *defaultCourseModel) Update(ctx context.Context, data *Course) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, courseRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.CourseNo, data.UseCases, data.CourseType, data.Version, data.Name, data.LessonName, data.Subject, data.Unit, data.TeacherId, data.Image, data.Intro, data.OpenTime, data.Type, data.Status, data.Level, data.Remark, data.Extra, data.Sequence, data.Id)
	return err
}

func (m *defaultCourseModel) TableName() string {
	return m.table
}
