// Code generated by goctl. DO NOT EDIT.

package supertrain

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	medalFieldNames          = builder.RawFieldNames(&Medal{})
	medalRows                = strings.Join(medalFieldNames, ",")
	medalRowsExpectAutoSet   = strings.Join(stringx.Remove(medalFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	medalRowsWithPlaceHolder = strings.Join(stringx.Remove(medalFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	medalModel interface {
		Insert(ctx context.Context, data *Medal) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Medal, error)
		Update(ctx context.Context, data *Medal) error
		Delete(ctx context.Context, id int64) error
	}

	defaultMedalModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Medal struct {
		Id              int64     `db:"id"`               // 主键
		Name            string    `db:"name"`             // 名称
		Description     string    `db:"description"`      // 描述
		Type            int64     `db:"type"`             // 类型 1.金钥匙 2.银钥匙 3.铜钥匙
		PromptKnowledge string    `db:"prompt_knowledge"` // p工程类关联知识点
		CreatedAt       time.Time `db:"created_at"`       // 创建时间
		UpdatedAt       time.Time `db:"updated_at"`       // 更新时间
	}
)

func newMedalModel(conn sqlx.SqlConn) *defaultMedalModel {
	return &defaultMedalModel{
		conn:  conn,
		table: "`ac_medal`",
	}
}

func (m *defaultMedalModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultMedalModel) FindOne(ctx context.Context, id int64) (*Medal, error) {

	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", medalRows, m.table)

	var resp Medal
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMedalModel) Insert(ctx context.Context, data *Medal) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, medalRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Name, data.Description, data.Type, data.PromptKnowledge)
	return ret, err
}

func (m *defaultMedalModel) Update(ctx context.Context, data *Medal) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, medalRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Name, data.Description, data.Type, data.PromptKnowledge, data.Id)
	return err
}

func (m *defaultMedalModel) TableName() string {
	return m.table
}
