// Code generated by goctl. DO NOT EDIT.

package supertrain

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	subTaskMedalFieldNames          = builder.RawFieldNames(&SubTaskMedal{})
	subTaskMedalRows                = strings.Join(subTaskMedalFieldNames, ",")
	subTaskMedalRowsExpectAutoSet   = strings.Join(stringx.Remove(subTaskMedalFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	subTaskMedalRowsWithPlaceHolder = strings.Join(stringx.Remove(subTaskMedalFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	subTaskMedalModel interface {
		Insert(ctx context.Context, data *SubTaskMedal) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*SubTaskMedal, error)
		Update(ctx context.Context, data *SubTaskMedal) error
		Delete(ctx context.Context, id int64) error
	}

	defaultSubTaskMedalModel struct {
		conn  sqlx.SqlConn
		table string
	}

	SubTaskMedal struct {
		Id        int64     `db:"id"`          // 主键
		SubTaskId int64     `db:"sub_task_id"` // 子任务ID
		MedalId   int64     `db:"medal_id"`    // 任务奖牌ID
		CreatedAt time.Time `db:"created_at"`  // 创建时间
		UpdatedAt time.Time `db:"updated_at"`  // 更新时间
	}
)

func newSubTaskMedalModel(conn sqlx.SqlConn) *defaultSubTaskMedalModel {
	return &defaultSubTaskMedalModel{
		conn:  conn,
		table: "`ac_sub_task_medal`",
	}
}

func (m *defaultSubTaskMedalModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultSubTaskMedalModel) FindOne(ctx context.Context, id int64) (*SubTaskMedal, error) {

	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", subTaskMedalRows, m.table)

	var resp SubTaskMedal
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSubTaskMedalModel) Insert(ctx context.Context, data *SubTaskMedal) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, subTaskMedalRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.SubTaskId, data.MedalId)
	return ret, err
}

func (m *defaultSubTaskMedalModel) Update(ctx context.Context, data *SubTaskMedal) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, subTaskMedalRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.SubTaskId, data.MedalId, data.Id)
	return err
}

func (m *defaultSubTaskMedalModel) TableName() string {
	return m.table
}
