// Code generated by goctl. DO NOT EDIT.

package supertrain

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	subTaskFieldNames          = builder.RawFieldNames(&SubTask{})
	subTaskRows                = strings.Join(subTaskFieldNames, ",")
	subTaskRowsExpectAutoSet   = strings.Join(stringx.Remove(subTaskFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	subTaskRowsWithPlaceHolder = strings.Join(stringx.Remove(subTaskFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	subTaskModel interface {
		Insert(ctx context.Context, data *SubTask) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*SubTask, error)
		FindOneBySubTaskNo(ctx context.Context, subTaskNo string) (*SubTask, error)
		Update(ctx context.Context, data *SubTask) error
		Delete(ctx context.Context, id int64) error
	}

	defaultSubTaskModel struct {
		conn  sqlx.SqlConn
		table string
	}

	SubTask struct {
		Id            int64          `db:"id"`              // 主键
		Mode          int64          `db:"mode"`            // 子任务模式 1.普通模式 2. 困难模式
		SubTaskNo     string         `db:"sub_task_no"`     // 子任务编号
		ChapterTaskId int64          `db:"chapter_task_id"` // 章节任务ID
		Title         string         `db:"title"`           // 标题
		Article       sql.NullString `db:"article"`         // 原文资料
		Description   string         `db:"description"`     // 描述
		ImageUrl      string         `db:"image_url"`       // 图片地址
		Keywords      string         `db:"keywords"`        // 关键词列表(json格式)
		Extra         string         `db:"extra"`           // 拓展字段(json格式)
		Type          int64          `db:"type"`            // 类型 1.普通任务 2.身份卡 3.聊天
		Sequence      float64        `db:"sequence"`        // 排序
		Deleted       int64          `db:"deleted"`         // 是否删除 1.否 2.是
		CreatedAt     time.Time      `db:"created_at"`      // 创建时间
		UpdatedAt     time.Time      `db:"updated_at"`      // 更新时间
	}
)

func newSubTaskModel(conn sqlx.SqlConn) *defaultSubTaskModel {
	return &defaultSubTaskModel{
		conn:  conn,
		table: "`ac_sub_task`",
	}
}

func (m *defaultSubTaskModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultSubTaskModel) FindOne(ctx context.Context, id int64) (*SubTask, error) {

	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", subTaskRows, m.table)

	var resp SubTask
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSubTaskModel) FindOneBySubTaskNo(ctx context.Context, subTaskNo string) (*SubTask, error) {
	var resp SubTask

	query := fmt.Sprintf("select %s from %s where `sub_task_no` = ? limit 1", subTaskRows, m.table)

	err := m.conn.QueryRowCtx(ctx, &resp, query, subTaskNo)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSubTaskModel) Insert(ctx context.Context, data *SubTask) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, subTaskRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Mode, data.SubTaskNo, data.ChapterTaskId, data.Title, data.Article, data.Description, data.ImageUrl, data.Keywords, data.Extra, data.Type, data.Sequence, data.Deleted)
	return ret, err
}

func (m *defaultSubTaskModel) Update(ctx context.Context, newData *SubTask) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, subTaskRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Mode, newData.SubTaskNo, newData.ChapterTaskId, newData.Title, newData.Article, newData.Description, newData.ImageUrl, newData.Keywords, newData.Extra, newData.Type, newData.Sequence, newData.Deleted, newData.Id)
	return err
}

func (m *defaultSubTaskModel) TableName() string {
	return m.table
}
