// Code generated by goctl. DO NOT EDIT.

package member

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	doushenVipFieldNames          = builder.RawFieldNames(&DoushenVip{})
	doushenVipRows                = strings.Join(doushenVipFieldNames, ",")
	doushenVipRowsExpectAutoSet   = strings.Join(stringx.Remove(doushenVipFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	doushenVipRowsWithPlaceHolder = strings.Join(stringx.Remove(doushenVipFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	doushenVipModel interface {
		Insert(ctx context.Context, data *DoushenVip) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*DoushenVip, error)
		Update(ctx context.Context, data *DoushenVip) error
		Delete(ctx context.Context, id int64) error
	}

	defaultDoushenVipModel struct {
		conn  sqlx.SqlConn
		table string
	}

	DoushenVip struct {
		Id        int64     `db:"id"`         // 主键ID
		UserId    int64     `db:"user_id"`    // 用户ID
		VipType   int64     `db:"vip_type"`   // vip类型 1.豆神会员（基础版） 2.豆神会员（典藏版） 3.豆神超级会员 4.豆神会员（特别版）
		Level     int64     `db:"level"`      // 等级
		FromTime  time.Time `db:"from_time"`  // 权益开始时间
		EndTime   time.Time `db:"end_time"`   // 权益结束时间
		Status    int64     `db:"status"`     // 状态 1.有效 2.失效
		CreatedAt time.Time `db:"created_at"` // 创建时间
		UpdatedAt time.Time `db:"updated_at"` // 更新时间
	}
)

func newDoushenVipModel(conn sqlx.SqlConn) *defaultDoushenVipModel {
	return &defaultDoushenVipModel{
		conn:  conn,
		table: "`us_doushen_vip`",
	}
}

func (m *defaultDoushenVipModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultDoushenVipModel) FindOne(ctx context.Context, id int64) (*DoushenVip, error) {

	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", doushenVipRows, m.table)

	var resp DoushenVip
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultDoushenVipModel) Insert(ctx context.Context, data *DoushenVip) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, doushenVipRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.VipType, data.Level, data.FromTime, data.EndTime, data.Status)
	return ret, err
}

func (m *defaultDoushenVipModel) Update(ctx context.Context, data *DoushenVip) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, doushenVipRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserId, data.VipType, data.Level, data.FromTime, data.EndTime, data.Status, data.Id)
	return err
}

func (m *defaultDoushenVipModel) TableName() string {
	return m.table
}
