// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	auth "muse-admin/internal/handler/auth"
	behaviorsession "muse-admin/internal/handler/behavior/session"
	benefit "muse-admin/internal/handler/benefit"
	code "muse-admin/internal/handler/code"
	configdict "muse-admin/internal/handler/config/dict"
	dictionarymuse "muse-admin/internal/handler/dictionary/muse"
	hublesson "muse-admin/internal/handler/hub/lesson"
	hublive "muse-admin/internal/handler/hub/live"
	hubsupertrain "muse-admin/internal/handler/hub/supertrain"
	kingclubcourse "muse-admin/internal/handler/kingclub/course"
	lesson "muse-admin/internal/handler/lesson"
	live "muse-admin/internal/handler/live"
	loglogin "muse-admin/internal/handler/log/login"
	member "muse-admin/internal/handler/member"
	order "muse-admin/internal/handler/order"
	probe "muse-admin/internal/handler/probe"
	public "muse-admin/internal/handler/public"
	publictask "muse-admin/internal/handler/public/task"
	supervisor "muse-admin/internal/handler/supervisor"
	sysdept "muse-admin/internal/handler/sys/dept"
	sysjob "muse-admin/internal/handler/sys/job"
	sysmenu "muse-admin/internal/handler/sys/menu"
	sysprofession "muse-admin/internal/handler/sys/profession"
	sysrole "muse-admin/internal/handler/sys/role"
	sysuser "muse-admin/internal/handler/sys/user"
	user "muse-admin/internal/handler/user"
	"muse-admin/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/ping",
				Handler: probe.PingHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: user.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/login/captcha",
				Handler: user.GetLoginCaptchaHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/logout",
				Handler: user.LogoutHandler(serverCtx),
			},
		},
		rest.WithPrefix("/admin/user"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/info",
				Handler: user.GetUserInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/permmenu",
				Handler: user.GetUserPermMenuHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/profile/info",
				Handler: user.GetUserProfileInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/profile/update",
				Handler: user.UpdateUserProfileHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/password/update",
				Handler: user.UpdateUserPasswordHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/avatar/generate",
				Handler: user.GetGenerateAvatarHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/admin/user"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.PermMenuAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: sysmenu.GetSysPermMenuListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/add",
					Handler: sysmenu.AddSysPermMenuHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/delete",
					Handler: sysmenu.DeleteSysPermMenuHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/update",
					Handler: sysmenu.UpdateSysPermMenuHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/admin/sys/perm/menu"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.PermMenuAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: sysrole.GetSysRoleListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/add",
					Handler: sysrole.AddSysRoleHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/delete",
					Handler: sysrole.DeleteSysRoleHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/update",
					Handler: sysrole.UpdateSysRoleHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/admin/sys/role"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.PermMenuAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: sysdept.GetSysDeptListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/add",
					Handler: sysdept.AddSysDeptHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/delete",
					Handler: sysdept.DeleteSysDeptHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/update",
					Handler: sysdept.UpdateSysDeptHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/admin/sys/dept"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.PermMenuAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/page",
					Handler: sysjob.GetSysJobPageHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/add",
					Handler: sysjob.AddSysJobHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/delete",
					Handler: sysjob.DeleteSysJobHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/update",
					Handler: sysjob.UpdateSysJobHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/admin/sys/job"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.PermMenuAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/page",
					Handler: sysprofession.GetSysProfessionPageHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/add",
					Handler: sysprofession.AddSysProfessionHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/delete",
					Handler: sysprofession.DeleteSysProfessionHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/update",
					Handler: sysprofession.UpdateSysProfessionHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/admin/sys/profession"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.PermMenuAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/page",
					Handler: sysuser.GetSysUserPageHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/add",
					Handler: sysuser.AddSysUserHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/delete",
					Handler: sysuser.DeleteSysUserHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/update",
					Handler: sysuser.UpdateSysUserHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/password/update",
					Handler: sysuser.UpdateSysUserPasswordHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/rdpj/info",
					Handler: sysuser.GetSysUserRdpjInfoHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/admin/sys/user"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.PermMenuAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: configdict.GetConfigDictListHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/data/page",
					Handler: configdict.GetConfigDictPageHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/add",
					Handler: configdict.AddConfigDictHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/delete",
					Handler: configdict.DeleteConfigDictHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/update",
					Handler: configdict.UpdateConfigDictHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/admin/config/dict"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.PermMenuAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/page",
					Handler: loglogin.GetLogLoginPageHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/admin/log/login"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.PermMenuAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: member.MemberListHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/getPhone",
					Handler: member.GetPhoneHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/logOff",
					Handler: member.LogOffHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/export",
					Handler: member.ExportHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/getRoleList",
					Handler: member.GetRoleListHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/admin/member"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.PermMenuAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: member.WhiteListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/add",
					Handler: member.WhiteAddHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/edit",
					Handler: member.WhiteEditHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/delete",
					Handler: member.WhiteDeleteHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/admin/member/white"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.PermMenuAuth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/importFile",
					Handler: public.ImportFileHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/exportData",
					Handler: public.ExportDataHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/admin/public"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.PermMenuAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/taskList",
					Handler: publictask.TaskListHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/taskDetailList",
					Handler: publictask.TaskDetailListHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/admin/public"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.PermMenuAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/importBenefitList",
					Handler: benefit.ImportBenefitListHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/importBenefitDesc",
					Handler: benefit.ImportBenefitDescHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/admin/benefit"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.PermMenuAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/benefitList",
					Handler: benefit.BenefitListHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/userBenefitList",
					Handler: benefit.UserBenefitListHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/userBenefitDetailList",
					Handler: benefit.UserBenefitDetailListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/userPhoneModify",
					Handler: benefit.UserPhoneModifyHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/groupList",
					Handler: benefit.GroupListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/userBenefitAdd",
					Handler: benefit.UserBenefitAddHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/reissue",
					Handler: benefit.ReissueHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/changeBenefitUser",
					Handler: benefit.ChangeBenefitUserHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/admin/benefit"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.PermMenuAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: lesson.LessonListHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/example",
					Handler: lesson.LessonExampleHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/admin/lesson"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.PermMenuAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: lesson.SuperTrainListHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/admin/lesson/superTrain"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.PermMenuAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/getOrderList",
					Handler: order.GetOrderListHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/exportOrder",
					Handler: order.ExportOrderHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/orderWaitSend",
					Handler: order.OrderWaitSendHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/exportWaitSend",
					Handler: order.ExportWaitSendHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/getGoodsList",
					Handler: order.GetGoodsListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/orderExpress",
					Handler: order.OrderExpressHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/admin/order"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.PermMenuAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: hublesson.ListHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/detail",
					Handler: hublesson.DetailHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/inspect",
					Handler: hublesson.InspectHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/admin/hub/lesson"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/batchInspect",
				Handler: hublesson.BatchInspectHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/admin/hub/lesson"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.PermMenuAuth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/inspect",
					Handler: hublive.InspectHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/admin/hub/live"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.PermMenuAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: hubsupertrain.ListHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/detail",
					Handler: hubsupertrain.DetailHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/inspect",
					Handler: hubsupertrain.InspectHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/admin/hub/superTrain"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/batchInspect",
				Handler: hubsupertrain.BatchInspectHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/admin/hub/superTrain"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/sync",
				Handler: hubsupertrain.SyncHandler(serverCtx),
			},
		},
		rest.WithPrefix("/admin/hub/superTrain"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/whiteList",
				Handler: live.WhiteListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/inspect",
				Handler: live.InspectHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/admin/live"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/getActiveLives",
				Handler: live.GetActiveLivesHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/getLiveStudents",
				Handler: live.GetLiveStudentsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/mutePersonal",
				Handler: live.MutePersonalHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/admin/live"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.PermMenuAuth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/add",
					Handler: code.AddCodeHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: code.ListCodeHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/export",
					Handler: code.ExportCodeHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/admin/code"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.PermMenuAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/v1/userIdList",
					Handler: behaviorsession.UserIdListHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/v1/getListByUserId",
					Handler: behaviorsession.GetListByUserIdHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/v1/getListBySessionId",
					Handler: behaviorsession.GetListBySessionIdHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/admin/session"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/getCourseCommonData",
				Handler: kingclubcourse.GetCourseCommonDataHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/getCourseChapter",
				Handler: kingclubcourse.GetCourseChapterHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/getChapterTask",
				Handler: kingclubcourse.GetChapterTaskHandler(serverCtx),
			},
		},
		rest.WithPrefix("/admin/kingclub"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/v1/tencent",
				Handler: auth.TencentHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/v1/static/tencent",
				Handler: auth.StaticTencentHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/v1/azure",
				Handler: auth.AzureHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/admin/auth"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.PermMenuAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: dictionarymuse.GetMuseDictPageHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/add",
					Handler: dictionarymuse.AddMuseDictHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/delete",
					Handler: dictionarymuse.DeleteMuseDictHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/update",
					Handler: dictionarymuse.UpdateMuseDictHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/admin/dictionary/muse"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: supervisor.SupervisorScheduleListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/statusUpdate",
				Handler: supervisor.SupervisorScheduleStatusHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/add",
				Handler: supervisor.SupervisorScheduleAddHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/edit",
				Handler: supervisor.SupervisorScheduleEditHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/teacherList",
				Handler: supervisor.TeacherListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/interactionList",
				Handler: supervisor.InteractionListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/interactionAdd",
				Handler: supervisor.InteractionAddHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/interactionUpdate",
				Handler: supervisor.InteractionUpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/courseList",
				Handler: supervisor.CourseListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/admin/supervisor"),
	)
}
