// Code generated by goctl. DO NOT EDIT.

package nightstar

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	homeworkRecordsFieldNames          = builder.RawFieldNames(&HomeworkRecords{})
	homeworkRecordsRows                = strings.Join(homeworkRecordsFieldNames, ",")
	homeworkRecordsRowsExpectAutoSet   = strings.Join(stringx.Remove(homeworkRecordsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	homeworkRecordsRowsWithPlaceHolder = strings.Join(stringx.Remove(homeworkRecordsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	homeworkRecordsModel interface {
		Insert(ctx context.Context, data *HomeworkRecords) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*HomeworkRecords, error)
		Update(ctx context.Context, data *HomeworkRecords) error
		Delete(ctx context.Context, id int64) error
	}

	defaultHomeworkRecordsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	HomeworkRecords struct {
		Id             int64     `db:"id"`              // 主键ID
		LiveCourseId   int64     `db:"live_course_id"`  // 课堂ID
		UserId         int64     `db:"user_id"`         // 用户ID
		Status         int64     `db:"status"`          // 作业批改状态 1.批改中 2.批改完成 3.批改失败
		CorrectComment string    `db:"correct_comment"` // 批改内容
		CreatedAt      time.Time `db:"created_at"`      // 创建时间
		UpdatedAt      time.Time `db:"updated_at"`      // 更新时间
	}
)

func newHomeworkRecordsModel(conn sqlx.SqlConn) *defaultHomeworkRecordsModel {
	return &defaultHomeworkRecordsModel{
		conn:  conn,
		table: "`ns_homework_records`",
	}
}

func (m *defaultHomeworkRecordsModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultHomeworkRecordsModel) FindOne(ctx context.Context, id int64) (*HomeworkRecords, error) {

	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", homeworkRecordsRows, m.table)

	var resp HomeworkRecords
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultHomeworkRecordsModel) Insert(ctx context.Context, data *HomeworkRecords) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, homeworkRecordsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.LiveCourseId, data.UserId, data.Status, data.CorrectComment)
	return ret, err
}

func (m *defaultHomeworkRecordsModel) Update(ctx context.Context, data *HomeworkRecords) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, homeworkRecordsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.LiveCourseId, data.UserId, data.Status, data.CorrectComment, data.Id)
	return err
}

func (m *defaultHomeworkRecordsModel) TableName() string {
	return m.table
}
