// Code generated by goctl. DO NOT EDIT.

package nightstar

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	homeworkDetailFieldNames          = builder.RawFieldNames(&HomeworkDetail{})
	homeworkDetailRows                = strings.Join(homeworkDetailFieldNames, ",")
	homeworkDetailRowsExpectAutoSet   = strings.Join(stringx.Remove(homeworkDetailFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	homeworkDetailRowsWithPlaceHolder = strings.Join(stringx.Remove(homeworkDetailFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	homeworkDetailModel interface {
		Insert(ctx context.Context, data *HomeworkDetail) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*HomeworkDetail, error)
		Update(ctx context.Context, data *HomeworkDetail) error
		Delete(ctx context.Context, id int64) error
	}

	defaultHomeworkDetailModel struct {
		conn  sqlx.SqlConn
		table string
	}

	HomeworkDetail struct {
		Id                int64          `db:"id"`                  // ID
		HomeworkRecordsId int64          `db:"homework_records_id"` // 作业记录id
		Url               string         `db:"url"`                 // url
		Content           sql.NullString `db:"content"`             // 识别内容
		Status            int64          `db:"status"`              // 状态1.待识别 2.完成 3.失败
		CreatedAt         time.Time      `db:"created_at"`          // 创建时间
		UpdatedAt         time.Time      `db:"updated_at"`          // 修改时间
	}
)

func newHomeworkDetailModel(conn sqlx.SqlConn) *defaultHomeworkDetailModel {
	return &defaultHomeworkDetailModel{
		conn:  conn,
		table: "`ns_homework_detail`",
	}
}

func (m *defaultHomeworkDetailModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultHomeworkDetailModel) FindOne(ctx context.Context, id int64) (*HomeworkDetail, error) {

	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", homeworkDetailRows, m.table)

	var resp HomeworkDetail
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultHomeworkDetailModel) Insert(ctx context.Context, data *HomeworkDetail) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, homeworkDetailRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.HomeworkRecordsId, data.Url, data.Content, data.Status)
	return ret, err
}

func (m *defaultHomeworkDetailModel) Update(ctx context.Context, data *HomeworkDetail) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, homeworkDetailRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.HomeworkRecordsId, data.Url, data.Content, data.Status, data.Id)
	return err
}

func (m *defaultHomeworkDetailModel) TableName() string {
	return m.table
}
