// Code generated by goctl. DO NOT EDIT.

package nightstar

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	learnRecordsFieldNames          = builder.RawFieldNames(&LearnRecords{})
	learnRecordsRows                = strings.Join(learnRecordsFieldNames, ",")
	learnRecordsRowsExpectAutoSet   = strings.Join(stringx.Remove(learnRecordsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	learnRecordsRowsWithPlaceHolder = strings.Join(stringx.Remove(learnRecordsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	learnRecordsModel interface {
		Insert(ctx context.Context, data *LearnRecords) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*LearnRecords, error)
		Update(ctx context.Context, data *LearnRecords) error
		Delete(ctx context.Context, id int64) error
	}

	defaultLearnRecordsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	LearnRecords struct {
		Id             int64     `db:"id"`              // 主键ID
		CourseId       int64     `db:"course_id"`       // 课堂ID
		UserId         int64     `db:"user_id"`         // 用户ID
		CompletedTime  time.Time `db:"completed_time"`  // 第一次完成时间
		CompletedCount int64     `db:"completed_count"` // 累计完成次数
		CompletedSign  string    `db:"completed_sign"`  // 完成标记
		CreatedAt      time.Time `db:"created_at"`      // 创建时间
		UpdatedAt      time.Time `db:"updated_at"`      // 更新时间
	}
)

func newLearnRecordsModel(conn sqlx.SqlConn) *defaultLearnRecordsModel {
	return &defaultLearnRecordsModel{
		conn:  conn,
		table: "`ns_learn_records`",
	}
}

func (m *defaultLearnRecordsModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultLearnRecordsModel) FindOne(ctx context.Context, id int64) (*LearnRecords, error) {

	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", learnRecordsRows, m.table)

	var resp LearnRecords
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultLearnRecordsModel) Insert(ctx context.Context, data *LearnRecords) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, learnRecordsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.CourseId, data.UserId, data.CompletedTime, data.CompletedCount, data.CompletedSign)
	return ret, err
}

func (m *defaultLearnRecordsModel) Update(ctx context.Context, data *LearnRecords) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, learnRecordsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.CourseId, data.UserId, data.CompletedTime, data.CompletedCount, data.CompletedSign, data.Id)
	return err
}

func (m *defaultLearnRecordsModel) TableName() string {
	return m.table
}
