// Code generated by goctl. DO NOT EDIT.

package nightstar

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	liveTeacherFieldNames          = builder.RawFieldNames(&LiveTeacher{})
	liveTeacherRows                = strings.Join(liveTeacherFieldNames, ",")
	liveTeacherRowsExpectAutoSet   = strings.Join(stringx.Remove(liveTeacherFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	liveTeacherRowsWithPlaceHolder = strings.Join(stringx.Remove(liveTeacherFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	liveTeacherModel interface {
		Insert(ctx context.Context, data *LiveTeacher) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*LiveTeacher, error)
		Update(ctx context.Context, data *LiveTeacher) error
		Delete(ctx context.Context, id int64) error
	}

	defaultLiveTeacherModel struct {
		conn  sqlx.SqlConn
		table string
	}

	LiveTeacher struct {
		Id               int64     `db:"id"`                // 主键
		TeacherCode      string    `db:"teacher_code"`      // 数据源提供的老师ID
		TeacherName      string    `db:"teacher_name"`      // 老师名称
		TeacherNickname  string    `db:"teacher_nickname"`  // 老师昵称
		HandAudio        string    `db:"hand_audio"`        // 课中举手发声音频
		ToneType         int64     `db:"tone_type"`         // 音色类型 1.minimax 2.火山
		TeacherTone      string    `db:"teacher_tone"`      // 老师音色
		ToneModel        string    `db:"tone_model"`        // 音色模型
		TeacherIntroduce string    `db:"teacher_introduce"` // 老师简介
		TeacherGif       string    `db:"teacher_gif"`       // 老师讲课动图(兜底图)
		TeacherPng       string    `db:"teacher_png"`       // 老师讲课静图(兜底图)
		CreatedAt        time.Time `db:"created_at"`        // 创建时间
		UpdatedAt        time.Time `db:"updated_at"`        // 更新时间
	}
)

func newLiveTeacherModel(conn sqlx.SqlConn) *defaultLiveTeacherModel {
	return &defaultLiveTeacherModel{
		conn:  conn,
		table: "`ns_live_teacher`",
	}
}

func (m *defaultLiveTeacherModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultLiveTeacherModel) FindOne(ctx context.Context, id int64) (*LiveTeacher, error) {

	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", liveTeacherRows, m.table)

	var resp LiveTeacher
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultLiveTeacherModel) Insert(ctx context.Context, data *LiveTeacher) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, liveTeacherRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.TeacherCode, data.TeacherName, data.TeacherNickname, data.HandAudio, data.ToneType, data.TeacherTone, data.ToneModel, data.TeacherIntroduce, data.TeacherGif, data.TeacherPng)
	return ret, err
}

func (m *defaultLiveTeacherModel) Update(ctx context.Context, data *LiveTeacher) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, liveTeacherRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.TeacherCode, data.TeacherName, data.TeacherNickname, data.HandAudio, data.ToneType, data.TeacherTone, data.ToneModel, data.TeacherIntroduce, data.TeacherGif, data.TeacherPng, data.Id)
	return err
}

func (m *defaultLiveTeacherModel) TableName() string {
	return m.table
}
