// Code generated by goctl. DO NOT EDIT.

package nightstar

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	liveCourseFieldNames          = builder.RawFieldNames(&LiveCourse{})
	liveCourseRows                = strings.Join(liveCourseFieldNames, ",")
	liveCourseRowsExpectAutoSet   = strings.Join(stringx.Remove(liveCourseFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	liveCourseRowsWithPlaceHolder = strings.Join(stringx.Remove(liveCourseFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	liveCourseModel interface {
		Insert(ctx context.Context, data *LiveCourse) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*LiveCourse, error)
		Update(ctx context.Context, data *LiveCourse) error
		Delete(ctx context.Context, id int64) error
	}

	defaultLiveCourseModel struct {
		conn  sqlx.SqlConn
		table string
	}

	LiveCourse struct {
		Id        int64     `db:"id"`         // 主键
		LiveNo    string    `db:"live_no"`    // 课程编号
		Version   int64     `db:"version"`    // 版本号
		Name      string    `db:"name"`       // 课程名称
		TeacherId int64     `db:"teacher_id"` // 老师id
		Label     string    `db:"label"`      // 课程标签
		Image     string    `db:"image"`      // 课程封面图
		Intro     string    `db:"intro"`      // 课程介绍
		Keyword   string    `db:"keyword"`    // 关键知识点
		OpenTime  time.Time `db:"open_time"`  // 开放时间
		Type      int64     `db:"type"`       // 类型 1.试听课 2.付费课
		Status    int64     `db:"status"`     // 状态 1.初始录入 2.审核中 3.审核通过 4.审核未通过 5.下架
		Remark    string    `db:"remark"`     // 备注
		Sequence  float64   `db:"sequence"`   // 排序
		CreatedAt time.Time `db:"created_at"` // 创建时间
		UpdatedAt time.Time `db:"updated_at"` // 更新时间
	}
)

func newLiveCourseModel(conn sqlx.SqlConn) *defaultLiveCourseModel {
	return &defaultLiveCourseModel{
		conn:  conn,
		table: "`ns_live_course`",
	}
}

func (m *defaultLiveCourseModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultLiveCourseModel) FindOne(ctx context.Context, id int64) (*LiveCourse, error) {

	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", liveCourseRows, m.table)

	var resp LiveCourse
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultLiveCourseModel) Insert(ctx context.Context, data *LiveCourse) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, liveCourseRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.LiveNo, data.Version, data.Name, data.TeacherId, data.Label, data.Image, data.Intro, data.Keyword, data.OpenTime, data.Type, data.Status, data.Remark, data.Sequence)
	return ret, err
}

func (m *defaultLiveCourseModel) Update(ctx context.Context, data *LiveCourse) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, liveCourseRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.LiveNo, data.Version, data.Name, data.TeacherId, data.Label, data.Image, data.Intro, data.Keyword, data.OpenTime, data.Type, data.Status, data.Remark, data.Sequence, data.Id)
	return err
}

func (m *defaultLiveCourseModel) TableName() string {
	return m.table
}
