// Code generated by goctl. DO NOT EDIT.

package nightstar

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	liveCourseEventFieldNames          = builder.RawFieldNames(&LiveCourseEvent{})
	liveCourseEventRows                = strings.Join(liveCourseEventFieldNames, ",")
	liveCourseEventRowsExpectAutoSet   = strings.Join(stringx.Remove(liveCourseEventFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	liveCourseEventRowsWithPlaceHolder = strings.Join(stringx.Remove(liveCourseEventFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	liveCourseEventModel interface {
		Insert(ctx context.Context, data *LiveCourseEvent) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*LiveCourseEvent, error)
		Update(ctx context.Context, data *LiveCourseEvent) error
		Delete(ctx context.Context, id int64) error
	}

	defaultLiveCourseEventModel struct {
		conn  sqlx.SqlConn
		table string
	}

	LiveCourseEvent struct {
		Id                 int64        `db:"id"`                   // 主键
		LiveCourseId       int64        `db:"live_course_id"`       // 课堂ID
		StartId            float64      `db:"start_id"`             // 数据源唯一ID
		EventType          int64        `db:"event_type"`           // 事件类型 1.填空 2.选择
		Appearance         int64        `db:"appearance"`           // 题型风格 1.我说上句你来接 2.排序题 3.课前简答题 4.课后简答题 5.文本单选题 6.图片选择题 7.火眼金睛
		PromptCode         string       `db:"prompt_code"`          // LLM Code
		Title              string       `db:"title"`                // 标题
		Task               string       `db:"task"`                 // 题目描述
		Talk               string       `db:"talk"`                 // 交互过程中的会话
		WithoutAnswerImage string       `db:"without_answer_image"` // 无答案图片URL
		WithinAnswerImage  string       `db:"within_answer_image"`  // 有答案图片URL
		CreatedAt          time.Time    `db:"created_at"`           // 创建时间
		UpdatedAt          time.Time    `db:"updated_at"`           // 更新时间
		DeletedAt          sql.NullTime `db:"deleted_at"`           // 删除时间
	}
)

func newLiveCourseEventModel(conn sqlx.SqlConn) *defaultLiveCourseEventModel {
	return &defaultLiveCourseEventModel{
		conn:  conn,
		table: "`ns_live_course_event`",
	}
}

func (m *defaultLiveCourseEventModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("update %s set deleted_at = NOW() where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultLiveCourseEventModel) FindOne(ctx context.Context, id int64) (*LiveCourseEvent, error) {

	query := fmt.Sprintf("select %s from %s where deleted_at is null and `id` = ? limit 1", liveCourseEventRows, m.table)

	var resp LiveCourseEvent
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultLiveCourseEventModel) Insert(ctx context.Context, data *LiveCourseEvent) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, liveCourseEventRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.LiveCourseId, data.StartId, data.EventType, data.Appearance, data.PromptCode, data.Title, data.Task, data.Talk, data.WithoutAnswerImage, data.WithinAnswerImage)
	return ret, err
}

func (m *defaultLiveCourseEventModel) Update(ctx context.Context, data *LiveCourseEvent) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, liveCourseEventRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.LiveCourseId, data.StartId, data.EventType, data.Appearance, data.PromptCode, data.Title, data.Task, data.Talk, data.WithoutAnswerImage, data.WithinAnswerImage, data.Id)
	return err
}

func (m *defaultLiveCourseEventModel) TableName() string {
	return m.table
}
