// Code generated by goctl. DO NOT EDIT.

package nightstar

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	liveCourseQuestionFieldNames          = builder.RawFieldNames(&LiveCourseQuestion{})
	liveCourseQuestionRows                = strings.Join(liveCourseQuestionFieldNames, ",")
	liveCourseQuestionRowsExpectAutoSet   = strings.Join(stringx.Remove(liveCourseQuestionFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	liveCourseQuestionRowsWithPlaceHolder = strings.Join(stringx.Remove(liveCourseQuestionFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	liveCourseQuestionModel interface {
		Insert(ctx context.Context, data *LiveCourseQuestion) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*LiveCourseQuestion, error)
		Update(ctx context.Context, data *LiveCourseQuestion) error
		Delete(ctx context.Context, id int64) error
	}

	defaultLiveCourseQuestionModel struct {
		conn  sqlx.SqlConn
		table string
	}

	LiveCourseQuestion struct {
		Id                int64          `db:"id"`                   // 主键
		LiveCourseId      int64          `db:"live_course_id"`       // 课堂ID
		LiveCourseEventId int64          `db:"live_course_event_id"` // 互动事件ID
		QuestionType      int64          `db:"question_type"`        // 题目类型 1.填空题 2.选择题
		Question          string         `db:"question"`             // 问题
		AnswerAsk         string         `db:"answer_ask"`           // 答题要求
		Tips              string         `db:"tips"`                 // 提示
		Image             string         `db:"image"`                // 图片
		Answer            string         `db:"answer"`               // 题目答案
		Analysis          sql.NullString `db:"analysis"`             // 解析
		Sequence          float64        `db:"sequence"`             // 排序
		CreatedAt         time.Time      `db:"created_at"`           // 创建时间
		UpdatedAt         time.Time      `db:"updated_at"`           // 更新时间
		DeletedAt         sql.NullTime   `db:"deleted_at"`           // 删除时间
	}
)

func newLiveCourseQuestionModel(conn sqlx.SqlConn) *defaultLiveCourseQuestionModel {
	return &defaultLiveCourseQuestionModel{
		conn:  conn,
		table: "`ns_live_course_question`",
	}
}

func (m *defaultLiveCourseQuestionModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("update %s set deleted_at = NOW() where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultLiveCourseQuestionModel) FindOne(ctx context.Context, id int64) (*LiveCourseQuestion, error) {

	query := fmt.Sprintf("select %s from %s where deleted_at is null and `id` = ? limit 1", liveCourseQuestionRows, m.table)

	var resp LiveCourseQuestion
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultLiveCourseQuestionModel) Insert(ctx context.Context, data *LiveCourseQuestion) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, liveCourseQuestionRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.LiveCourseId, data.LiveCourseEventId, data.QuestionType, data.Question, data.AnswerAsk, data.Tips, data.Image, data.Answer, data.Analysis, data.Sequence)
	return ret, err
}

func (m *defaultLiveCourseQuestionModel) Update(ctx context.Context, data *LiveCourseQuestion) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, liveCourseQuestionRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.LiveCourseId, data.LiveCourseEventId, data.QuestionType, data.Question, data.AnswerAsk, data.Tips, data.Image, data.Answer, data.Analysis, data.Sequence, data.Id)
	return err
}

func (m *defaultLiveCourseQuestionModel) TableName() string {
	return m.table
}
