// Code generated by goctl. DO NOT EDIT.

package nightstar

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	liveAnswerFieldNames          = builder.RawFieldNames(&LiveAnswer{})
	liveAnswerRows                = strings.Join(liveAnswerFieldNames, ",")
	liveAnswerRowsExpectAutoSet   = strings.Join(stringx.Remove(liveAnswerFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	liveAnswerRowsWithPlaceHolder = strings.Join(stringx.Remove(liveAnswerFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	liveAnswerModel interface {
		Insert(ctx context.Context, data *LiveAnswer) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*LiveAnswer, error)
		Update(ctx context.Context, data *LiveAnswer) error
		Delete(ctx context.Context, id int64) error
	}

	defaultLiveAnswerModel struct {
		conn  sqlx.SqlConn
		table string
	}

	LiveAnswer struct {
		Id           int64     `db:"id"`             // 主键ID
		LiveRecordId int64     `db:"live_record_id"` // 直播记录ID
		UserId       int64     `db:"user_id"`        // 直播用户ID
		Code         string    `db:"code"`           // 业务类型
		GameId       int64     `db:"game_id"`        // 互动ID
		Content      string    `db:"content"`        // 内容
		Role         int64     `db:"role"`           // 角色：1 .模型 2.用户 3.虚拟用户
		Index        int64     `db:"index"`          // 视频播放时间戳
		CreatedAt    time.Time `db:"created_at"`     // 创建时间
	}
)

func newLiveAnswerModel(conn sqlx.SqlConn) *defaultLiveAnswerModel {
	return &defaultLiveAnswerModel{
		conn:  conn,
		table: "`ns_live_answer`",
	}
}

func (m *defaultLiveAnswerModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultLiveAnswerModel) FindOne(ctx context.Context, id int64) (*LiveAnswer, error) {

	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", liveAnswerRows, m.table)

	var resp LiveAnswer
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultLiveAnswerModel) Insert(ctx context.Context, data *LiveAnswer) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, liveAnswerRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.LiveRecordId, data.UserId, data.Code, data.GameId, data.Content, data.Role, data.Index)
	return ret, err
}

func (m *defaultLiveAnswerModel) Update(ctx context.Context, data *LiveAnswer) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, liveAnswerRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.LiveRecordId, data.UserId, data.Code, data.GameId, data.Content, data.Role, data.Index, data.Id)
	return err
}

func (m *defaultLiveAnswerModel) TableName() string {
	return m.table
}
