// Code generated by goctl. DO NOT EDIT.

package nightstar

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	liveSeriesCourseRelationFieldNames          = builder.RawFieldNames(&LiveSeriesCourseRelation{})
	liveSeriesCourseRelationRows                = strings.Join(liveSeriesCourseRelationFieldNames, ",")
	liveSeriesCourseRelationRowsExpectAutoSet   = strings.Join(stringx.Remove(liveSeriesCourseRelationFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	liveSeriesCourseRelationRowsWithPlaceHolder = strings.Join(stringx.Remove(liveSeriesCourseRelationFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	liveSeriesCourseRelationModel interface {
		Insert(ctx context.Context, data *LiveSeriesCourseRelation) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*LiveSeriesCourseRelation, error)
		Update(ctx context.Context, data *LiveSeriesCourseRelation) error
		Delete(ctx context.Context, id int64) error
	}

	defaultLiveSeriesCourseRelationModel struct {
		conn  sqlx.SqlConn
		table string
	}

	LiveSeriesCourseRelation struct {
		Id           int64     `db:"id"`             // 主键
		LiveSeriesId int64     `db:"live_series_id"` // 系列 id
		LiveCourseId int64     `db:"live_course_id"` // 课程 id
		CreatedAt    time.Time `db:"created_at"`     // 创建时间
		UpdatedAt    time.Time `db:"updated_at"`     // 更新时间
	}
)

func newLiveSeriesCourseRelationModel(conn sqlx.SqlConn) *defaultLiveSeriesCourseRelationModel {
	return &defaultLiveSeriesCourseRelationModel{
		conn:  conn,
		table: "`ns_live_series_course_relation`",
	}
}

func (m *defaultLiveSeriesCourseRelationModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultLiveSeriesCourseRelationModel) FindOne(ctx context.Context, id int64) (*LiveSeriesCourseRelation, error) {

	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", liveSeriesCourseRelationRows, m.table)

	var resp LiveSeriesCourseRelation
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultLiveSeriesCourseRelationModel) Insert(ctx context.Context, data *LiveSeriesCourseRelation) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, liveSeriesCourseRelationRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.LiveSeriesId, data.LiveCourseId)
	return ret, err
}

func (m *defaultLiveSeriesCourseRelationModel) Update(ctx context.Context, data *LiveSeriesCourseRelation) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, liveSeriesCourseRelationRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.LiveSeriesId, data.LiveCourseId, data.Id)
	return err
}

func (m *defaultLiveSeriesCourseRelationModel) TableName() string {
	return m.table
}
