// Code generated by goctl. DO NOT EDIT.

package nightstar

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	liveCourseTimelineFieldNames          = builder.RawFieldNames(&LiveCourseTimeline{})
	liveCourseTimelineRows                = strings.Join(liveCourseTimelineFieldNames, ",")
	liveCourseTimelineRowsExpectAutoSet   = strings.Join(stringx.Remove(liveCourseTimelineFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	liveCourseTimelineRowsWithPlaceHolder = strings.Join(stringx.Remove(liveCourseTimelineFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	liveCourseTimelineModel interface {
		Insert(ctx context.Context, data *LiveCourseTimeline) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*LiveCourseTimeline, error)
		Update(ctx context.Context, data *LiveCourseTimeline) error
		Delete(ctx context.Context, id int64) error
	}

	defaultLiveCourseTimelineModel struct {
		conn  sqlx.SqlConn
		table string
	}

	LiveCourseTimeline struct {
		Id               int64     `db:"id"`                 // 主键
		LiveCourseId     int64     `db:"live_course_id"`     // 课堂ID
		Navigate         string    `db:"navigate"`           // 导航进度条
		Draft            string    `db:"draft"`              // 字幕
		DraftRag         string    `db:"draft_rag"`          // 字幕纯文字
		SimpleDraft      string    `db:"simple_draft"`       // 提炼出的精简字幕
		BlockTime        string    `db:"block_time"`         // 停顿气口
		FrontEvent       string    `db:"front_event"`        // 班主任欢迎环节
		SmallTalkEvent   string    `db:"small_talk_event"`   // 寒暄环节
		SmallTalkPrecast string    `db:"small_talk_precast"` // 寒暄环节中的开场预制
		LearnEvent       string    `db:"learn_event"`        // 课中环节
		CreatedAt        time.Time `db:"created_at"`         // 创建时间
		UpdatedAt        time.Time `db:"updated_at"`         // 更新时间
	}
)

func newLiveCourseTimelineModel(conn sqlx.SqlConn) *defaultLiveCourseTimelineModel {
	return &defaultLiveCourseTimelineModel{
		conn:  conn,
		table: "`ns_live_course_timeline`",
	}
}

func (m *defaultLiveCourseTimelineModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultLiveCourseTimelineModel) FindOne(ctx context.Context, id int64) (*LiveCourseTimeline, error) {

	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", liveCourseTimelineRows, m.table)

	var resp LiveCourseTimeline
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultLiveCourseTimelineModel) Insert(ctx context.Context, data *LiveCourseTimeline) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, liveCourseTimelineRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.LiveCourseId, data.Navigate, data.Draft, data.DraftRag, data.SimpleDraft, data.BlockTime, data.FrontEvent, data.SmallTalkEvent, data.SmallTalkPrecast, data.LearnEvent)
	return ret, err
}

func (m *defaultLiveCourseTimelineModel) Update(ctx context.Context, data *LiveCourseTimeline) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, liveCourseTimelineRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.LiveCourseId, data.Navigate, data.Draft, data.DraftRag, data.SimpleDraft, data.BlockTime, data.FrontEvent, data.SmallTalkEvent, data.SmallTalkPrecast, data.LearnEvent, data.Id)
	return err
}

func (m *defaultLiveCourseTimelineModel) TableName() string {
	return m.table
}
