// Code generated by goctl. DO NOT EDIT.

package nightstar

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	liveRecordFieldNames          = builder.RawFieldNames(&LiveRecord{})
	liveRecordRows                = strings.Join(liveRecordFieldNames, ",")
	liveRecordRowsExpectAutoSet   = strings.Join(stringx.Remove(liveRecordFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	liveRecordRowsWithPlaceHolder = strings.Join(stringx.Remove(liveRecordFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	liveRecordModel interface {
		Insert(ctx context.Context, data *LiveRecord) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*LiveRecord, error)
		Update(ctx context.Context, data *LiveRecord) error
		Delete(ctx context.Context, id int64) error
	}

	defaultLiveRecordModel struct {
		conn  sqlx.SqlConn
		table string
	}

	LiveRecord struct {
		Id            int64     `db:"id"`             // ID
		UserId        int64     `db:"user_id"`        // 用户id
		AppointmentId int64     `db:"appointment_id"` // 预约id
		LiveCourseId  int64     `db:"live_course_id"` // 课程id
		Status        int64     `db:"status"`         // 状态1.进行中 2.结束
		CompletedTime time.Time `db:"completed_time"` // 完成时间
		CreatedAt     time.Time `db:"created_at"`     // 创建时间
		UpdatedAt     time.Time `db:"updated_at"`     // 修改时间
	}
)

func newLiveRecordModel(conn sqlx.SqlConn) *defaultLiveRecordModel {
	return &defaultLiveRecordModel{
		conn:  conn,
		table: "`ns_live_record`",
	}
}

func (m *defaultLiveRecordModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultLiveRecordModel) FindOne(ctx context.Context, id int64) (*LiveRecord, error) {

	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", liveRecordRows, m.table)

	var resp LiveRecord
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultLiveRecordModel) Insert(ctx context.Context, data *LiveRecord) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, liveRecordRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.AppointmentId, data.LiveCourseId, data.Status, data.CompletedTime)
	return ret, err
}

func (m *defaultLiveRecordModel) Update(ctx context.Context, data *LiveRecord) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, liveRecordRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserId, data.AppointmentId, data.LiveCourseId, data.Status, data.CompletedTime, data.Id)
	return err
}

func (m *defaultLiveRecordModel) TableName() string {
	return m.table
}
