// Code generated by goctl. DO NOT EDIT.

package nightstar

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	liveVirtualUserFieldNames          = builder.RawFieldNames(&LiveVirtualUser{})
	liveVirtualUserRows                = strings.Join(liveVirtualUserFieldNames, ",")
	liveVirtualUserRowsExpectAutoSet   = strings.Join(stringx.Remove(liveVirtualUserFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	liveVirtualUserRowsWithPlaceHolder = strings.Join(stringx.Remove(liveVirtualUserFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	liveVirtualUserModel interface {
		Insert(ctx context.Context, data *LiveVirtualUser) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*LiveVirtualUser, error)
		Update(ctx context.Context, data *LiveVirtualUser) error
		Delete(ctx context.Context, id int64) error
	}

	defaultLiveVirtualUserModel struct {
		conn  sqlx.SqlConn
		table string
	}

	LiveVirtualUser struct {
		Id          int64     `db:"id"`          // 主键ID
		Name        string    `db:"name"`        // 姓名
		Gif         string    `db:"gif"`         // 动态头像URL
		RoleId      int64     `db:"role_id"`     // 角色性格类型
		RoleType    int64     `db:"role_type"`   // 角色类型：1.学生 2.助教老师
		Description string    `db:"description"` // 人物描述、性格、特长
		Sex         int64     `db:"sex"`         // 性别：1.男 2.女
		Status      int64     `db:"status"`      // 状态：1.有效 2.无效
		CreatedAt   time.Time `db:"created_at"`  // 创建时间
		UpdatedAt   time.Time `db:"updated_at"`  // 更新时间
	}
)

func newLiveVirtualUserModel(conn sqlx.SqlConn) *defaultLiveVirtualUserModel {
	return &defaultLiveVirtualUserModel{
		conn:  conn,
		table: "`ns_live_virtual_user`",
	}
}

func (m *defaultLiveVirtualUserModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultLiveVirtualUserModel) FindOne(ctx context.Context, id int64) (*LiveVirtualUser, error) {

	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", liveVirtualUserRows, m.table)

	var resp LiveVirtualUser
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultLiveVirtualUserModel) Insert(ctx context.Context, data *LiveVirtualUser) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, liveVirtualUserRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Name, data.Gif, data.RoleId, data.RoleType, data.Description, data.Sex, data.Status)
	return ret, err
}

func (m *defaultLiveVirtualUserModel) Update(ctx context.Context, data *LiveVirtualUser) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, liveVirtualUserRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Name, data.Gif, data.RoleId, data.RoleType, data.Description, data.Sex, data.Status, data.Id)
	return err
}

func (m *defaultLiveVirtualUserModel) TableName() string {
	return m.table
}
