// Code generated by goctl. DO NOT EDIT.

package nightstar

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	liveSeriesGradeFieldNames          = builder.RawFieldNames(&LiveSeriesGrade{})
	liveSeriesGradeRows                = strings.Join(liveSeriesGradeFieldNames, ",")
	liveSeriesGradeRowsExpectAutoSet   = strings.Join(stringx.Remove(liveSeriesGradeFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	liveSeriesGradeRowsWithPlaceHolder = strings.Join(stringx.Remove(liveSeriesGradeFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	liveSeriesGradeModel interface {
		Insert(ctx context.Context, data *LiveSeriesGrade) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*LiveSeriesGrade, error)
		Update(ctx context.Context, data *LiveSeriesGrade) error
		Delete(ctx context.Context, id int64) error
	}

	defaultLiveSeriesGradeModel struct {
		conn  sqlx.SqlConn
		table string
	}

	LiveSeriesGrade struct {
		Id           int64     `db:"id"`             // 主键
		LiveSeriesId int64     `db:"live_series_id"` // 系列id
		Grade        int64     `db:"grade"`          // 适用年级
		CreatedAt    time.Time `db:"created_at"`     // 创建时间
		UpdatedAt    time.Time `db:"updated_at"`     // 更新时间
	}
)

func newLiveSeriesGradeModel(conn sqlx.SqlConn) *defaultLiveSeriesGradeModel {
	return &defaultLiveSeriesGradeModel{
		conn:  conn,
		table: "`ns_live_series_grade`",
	}
}

func (m *defaultLiveSeriesGradeModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultLiveSeriesGradeModel) FindOne(ctx context.Context, id int64) (*LiveSeriesGrade, error) {

	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", liveSeriesGradeRows, m.table)

	var resp LiveSeriesGrade
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultLiveSeriesGradeModel) Insert(ctx context.Context, data *LiveSeriesGrade) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, liveSeriesGradeRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.LiveSeriesId, data.Grade)
	return ret, err
}

func (m *defaultLiveSeriesGradeModel) Update(ctx context.Context, data *LiveSeriesGrade) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, liveSeriesGradeRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.LiveSeriesId, data.Grade, data.Id)
	return err
}

func (m *defaultLiveSeriesGradeModel) TableName() string {
	return m.table
}
