// Code generated by goctl. DO NOT EDIT.

package nightstar

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	liveCourseDetailFieldNames          = builder.RawFieldNames(&LiveCourseDetail{})
	liveCourseDetailRows                = strings.Join(liveCourseDetailFieldNames, ",")
	liveCourseDetailRowsExpectAutoSet   = strings.Join(stringx.Remove(liveCourseDetailFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	liveCourseDetailRowsWithPlaceHolder = strings.Join(stringx.Remove(liveCourseDetailFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	liveCourseDetailModel interface {
		Insert(ctx context.Context, data *LiveCourseDetail) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*LiveCourseDetail, error)
		Update(ctx context.Context, data *LiveCourseDetail) error
		Delete(ctx context.Context, id int64) error
	}

	defaultLiveCourseDetailModel struct {
		conn  sqlx.SqlConn
		table string
	}

	LiveCourseDetail struct {
		Id           int64     `db:"id"`             // 主键
		LiveCourseId int64     `db:"live_course_id"` // 课堂ID
		TeacherId    int64     `db:"teacher_id"`     // 老师ID
		TeacherGif   string    `db:"teacher_gif"`    // 老师讲课动图
		TeacherPng   string    `db:"teacher_png"`    // 老师讲课静图
		TeacherVideo string    `db:"teacher_video"`  // 老师讲课视频URL
		Duration     int64     `db:"duration"`       // 视频总时长，单位毫秒
		Topic        string    `db:"topic"`          // 课堂开始时的寒暄主题
		PptVideo     string    `db:"ppt_video"`      // PPT视频URL
		FullImage    string    `db:"full_image"`     // 全屏背景URL
		PosterImage  string    `db:"poster_image"`   // 视频开场背景URL
		Note         string    `db:"note"`           // 课堂笔记
		Homework     string    `db:"homework"`       // 课后作业
		CreatedAt    time.Time `db:"created_at"`     // 创建时间
		UpdatedAt    time.Time `db:"updated_at"`     // 更新时间
	}
)

func newLiveCourseDetailModel(conn sqlx.SqlConn) *defaultLiveCourseDetailModel {
	return &defaultLiveCourseDetailModel{
		conn:  conn,
		table: "`ns_live_course_detail`",
	}
}

func (m *defaultLiveCourseDetailModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultLiveCourseDetailModel) FindOne(ctx context.Context, id int64) (*LiveCourseDetail, error) {

	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", liveCourseDetailRows, m.table)

	var resp LiveCourseDetail
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultLiveCourseDetailModel) Insert(ctx context.Context, data *LiveCourseDetail) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, liveCourseDetailRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.LiveCourseId, data.TeacherId, data.TeacherGif, data.TeacherPng, data.TeacherVideo, data.Duration, data.Topic, data.PptVideo, data.FullImage, data.PosterImage, data.Note, data.Homework)
	return ret, err
}

func (m *defaultLiveCourseDetailModel) Update(ctx context.Context, data *LiveCourseDetail) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, liveCourseDetailRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.LiveCourseId, data.TeacherId, data.TeacherGif, data.TeacherPng, data.TeacherVideo, data.Duration, data.Topic, data.PptVideo, data.FullImage, data.PosterImage, data.Note, data.Homework, data.Id)
	return err
}

func (m *defaultLiveCourseDetailModel) TableName() string {
	return m.table
}
