// Code generated by goctl. DO NOT EDIT.

package nightstar

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	liveCourseQuestionOptionFieldNames          = builder.RawFieldNames(&LiveCourseQuestionOption{})
	liveCourseQuestionOptionRows                = strings.Join(liveCourseQuestionOptionFieldNames, ",")
	liveCourseQuestionOptionRowsExpectAutoSet   = strings.Join(stringx.Remove(liveCourseQuestionOptionFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	liveCourseQuestionOptionRowsWithPlaceHolder = strings.Join(stringx.Remove(liveCourseQuestionOptionFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	liveCourseQuestionOptionModel interface {
		Insert(ctx context.Context, data *LiveCourseQuestionOption) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*LiveCourseQuestionOption, error)
		Update(ctx context.Context, data *LiveCourseQuestionOption) error
		Delete(ctx context.Context, id int64) error
	}

	defaultLiveCourseQuestionOptionModel struct {
		conn  sqlx.SqlConn
		table string
	}

	LiveCourseQuestionOption struct {
		Id                   int64        `db:"id"`                      // 主键
		LiveCourseQuestionId int64        `db:"live_course_question_id"` // 题目ID
		Tag                  string       `db:"tag"`                     // 选项名称
		Content              string       `db:"content"`                 // 选项内容
		Tips                 string       `db:"tips"`                    // 提示
		Image                string       `db:"image"`                   // 图片
		Sequence             float64      `db:"sequence"`                // 排序
		CreatedAt            time.Time    `db:"created_at"`              // 创建时间
		UpdatedAt            time.Time    `db:"updated_at"`              // 更新时间
		DeletedAt            sql.NullTime `db:"deleted_at"`              // 删除时间
	}
)

func newLiveCourseQuestionOptionModel(conn sqlx.SqlConn) *defaultLiveCourseQuestionOptionModel {
	return &defaultLiveCourseQuestionOptionModel{
		conn:  conn,
		table: "`ns_live_course_question_option`",
	}
}

func (m *defaultLiveCourseQuestionOptionModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("update %s set deleted_at = NOW() where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultLiveCourseQuestionOptionModel) FindOne(ctx context.Context, id int64) (*LiveCourseQuestionOption, error) {

	query := fmt.Sprintf("select %s from %s where deleted_at is null and `id` = ? limit 1", liveCourseQuestionOptionRows, m.table)

	var resp LiveCourseQuestionOption
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultLiveCourseQuestionOptionModel) Insert(ctx context.Context, data *LiveCourseQuestionOption) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, liveCourseQuestionOptionRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.LiveCourseQuestionId, data.Tag, data.Content, data.Tips, data.Image, data.Sequence)
	return ret, err
}

func (m *defaultLiveCourseQuestionOptionModel) Update(ctx context.Context, data *LiveCourseQuestionOption) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, liveCourseQuestionOptionRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.LiveCourseQuestionId, data.Tag, data.Content, data.Tips, data.Image, data.Sequence, data.Id)
	return err
}

func (m *defaultLiveCourseQuestionOptionModel) TableName() string {
	return m.table
}
