// Code generated by goctl. DO NOT EDIT.

package nightstar

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	liveSeriesFieldNames          = builder.RawFieldNames(&LiveSeries{})
	liveSeriesRows                = strings.Join(liveSeriesFieldNames, ",")
	liveSeriesRowsExpectAutoSet   = strings.Join(stringx.Remove(liveSeriesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	liveSeriesRowsWithPlaceHolder = strings.Join(stringx.Remove(liveSeriesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	liveSeriesModel interface {
		Insert(ctx context.Context, data *LiveSeries) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*LiveSeries, error)
		Update(ctx context.Context, data *LiveSeries) error
		Delete(ctx context.Context, id int64) error
	}

	defaultLiveSeriesModel struct {
		conn  sqlx.SqlConn
		table string
	}

	LiveSeries struct {
		Id         int64     `db:"id"`          // 主键
		Name       string    `db:"name"`        // 系列名
		CoverImage string    `db:"cover_image"` // 课程系列封面
		Intro      string    `db:"intro"`       // 课程系列介绍
		Type       int64     `db:"type"`        // 系列类型 1.试听系列 2.付费系列
		Status     int64     `db:"status"`      // 状态 1.正常 2.禁用
		Remark     string    `db:"remark"`      // 备注
		CreatedAt  time.Time `db:"created_at"`  // 创建时间
		UpdatedAt  time.Time `db:"updated_at"`  // 更新时间
	}
)

func newLiveSeriesModel(conn sqlx.SqlConn) *defaultLiveSeriesModel {
	return &defaultLiveSeriesModel{
		conn:  conn,
		table: "`ns_live_series`",
	}
}

func (m *defaultLiveSeriesModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultLiveSeriesModel) FindOne(ctx context.Context, id int64) (*LiveSeries, error) {

	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", liveSeriesRows, m.table)

	var resp LiveSeries
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultLiveSeriesModel) Insert(ctx context.Context, data *LiveSeries) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, liveSeriesRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Name, data.CoverImage, data.Intro, data.Type, data.Status, data.Remark)
	return ret, err
}

func (m *defaultLiveSeriesModel) Update(ctx context.Context, data *LiveSeries) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, liveSeriesRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Name, data.CoverImage, data.Intro, data.Type, data.Status, data.Remark, data.Id)
	return err
}

func (m *defaultLiveSeriesModel) TableName() string {
	return m.table
}
