// Code generated by goctl. DO NOT EDIT.

package nightstar

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	liveUserFieldNames          = builder.RawFieldNames(&LiveUser{})
	liveUserRows                = strings.Join(liveUserFieldNames, ",")
	liveUserRowsExpectAutoSet   = strings.Join(stringx.Remove(liveUserFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	liveUserRowsWithPlaceHolder = strings.Join(stringx.Remove(liveUserFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	liveUserModel interface {
		Insert(ctx context.Context, data *LiveUser) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*LiveUser, error)
		Update(ctx context.Context, data *LiveUser) error
		Delete(ctx context.Context, id int64) error
	}

	defaultLiveUserModel struct {
		conn  sqlx.SqlConn
		table string
	}

	LiveUser struct {
		Id           int64     `db:"id"`             // 主键ID
		LiveRecordId int64     `db:"live_record_id"` // 直播记录ID
		UserId       int64     `db:"user_id"`        // 用户ID
		UserType     int64     `db:"user_type"`      // 用户类型：1.真人 2.虚拟人
		RoleId       int64     `db:"role_id"`        // 预制数据源的角色ID
		CreatedAt    time.Time `db:"created_at"`     // 创建时间
		UpdatedAt    time.Time `db:"updated_at"`     // 更新时间
	}
)

func newLiveUserModel(conn sqlx.SqlConn) *defaultLiveUserModel {
	return &defaultLiveUserModel{
		conn:  conn,
		table: "`ns_live_user`",
	}
}

func (m *defaultLiveUserModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultLiveUserModel) FindOne(ctx context.Context, id int64) (*LiveUser, error) {

	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", liveUserRows, m.table)

	var resp LiveUser
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultLiveUserModel) Insert(ctx context.Context, data *LiveUser) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, liveUserRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.LiveRecordId, data.UserId, data.UserType, data.RoleId)
	return ret, err
}

func (m *defaultLiveUserModel) Update(ctx context.Context, data *LiveUser) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, liveUserRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.LiveRecordId, data.UserId, data.UserType, data.RoleId, data.Id)
	return err
}

func (m *defaultLiveUserModel) TableName() string {
	return m.table
}
