// Code generated by goctl. DO NOT EDIT.

package nightstar

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	liveAppointmentFieldNames          = builder.RawFieldNames(&LiveAppointment{})
	liveAppointmentRows                = strings.Join(liveAppointmentFieldNames, ",")
	liveAppointmentRowsExpectAutoSet   = strings.Join(stringx.Remove(liveAppointmentFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	liveAppointmentRowsWithPlaceHolder = strings.Join(stringx.Remove(liveAppointmentFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	liveAppointmentModel interface {
		Insert(ctx context.Context, data *LiveAppointment) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*LiveAppointment, error)
		Update(ctx context.Context, data *LiveAppointment) error
		Delete(ctx context.Context, id int64) error
	}

	defaultLiveAppointmentModel struct {
		conn  sqlx.SqlConn
		table string
	}

	LiveAppointment struct {
		Id              int64     `db:"id"`               // 主键
		UserId          int64     `db:"user_id"`          // 用户id
		LiveSeriesId    int64     `db:"live_series_id"`   // 系列id
		LiveCourseId    int64     `db:"live_course_id"`   // 课堂ID
		AppointmentTime time.Time `db:"appointment_time"` // 预约时间
		Status          int64     `db:"status"`           // 状态 1.未学习 2.学习中 3.已完成
		HomeWorkStatus  int64     `db:"home_work_status"` // 课后作业状态 1.未完成 2.已完成
		CreatedAt       time.Time `db:"created_at"`       // 创建时间
		UpdatedAt       time.Time `db:"updated_at"`       // 更新时间
	}
)

func newLiveAppointmentModel(conn sqlx.SqlConn) *defaultLiveAppointmentModel {
	return &defaultLiveAppointmentModel{
		conn:  conn,
		table: "`ns_live_appointment`",
	}
}

func (m *defaultLiveAppointmentModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultLiveAppointmentModel) FindOne(ctx context.Context, id int64) (*LiveAppointment, error) {

	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", liveAppointmentRows, m.table)

	var resp LiveAppointment
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultLiveAppointmentModel) Insert(ctx context.Context, data *LiveAppointment) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, liveAppointmentRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.LiveSeriesId, data.LiveCourseId, data.AppointmentTime, data.Status, data.HomeWorkStatus)
	return ret, err
}

func (m *defaultLiveAppointmentModel) Update(ctx context.Context, data *LiveAppointment) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, liveAppointmentRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserId, data.LiveSeriesId, data.LiveCourseId, data.AppointmentTime, data.Status, data.HomeWorkStatus, data.Id)
	return err
}

func (m *defaultLiveAppointmentModel) TableName() string {
	return m.table
}
