// Code generated by goctl. DO NOT EDIT.

package task

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	scheduleLogFieldNames          = builder.RawFieldNames(&ScheduleLog{})
	scheduleLogRows                = strings.Join(scheduleLogFieldNames, ",")
	scheduleLogRowsExpectAutoSet   = strings.Join(stringx.Remove(scheduleLogFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	scheduleLogRowsWithPlaceHolder = strings.Join(stringx.Remove(scheduleLogFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	scheduleLogModel interface {
		Insert(ctx context.Context, data *ScheduleLog) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*ScheduleLog, error)
		Update(ctx context.Context, data *ScheduleLog) error
		Delete(ctx context.Context, id int64) error
	}

	defaultScheduleLogModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ScheduleLog struct {
		Id     int64  `db:"id"`
		Data   string `db:"data"`   // 原始数据
		Status int64  `db:"status"` // 状态 0:未推送 1.已推送
	}
)

func newScheduleLogModel(conn sqlx.SqlConn) *defaultScheduleLogModel {
	return &defaultScheduleLogModel{
		conn:  conn,
		table: "`bk_schedule_log`",
	}
}

func (m *defaultScheduleLogModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultScheduleLogModel) FindOne(ctx context.Context, id int64) (*ScheduleLog, error) {

	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", scheduleLogRows, m.table)

	var resp ScheduleLog
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultScheduleLogModel) Insert(ctx context.Context, data *ScheduleLog) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, scheduleLogRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Data, data.Status)
	return ret, err
}

func (m *defaultScheduleLogModel) Update(ctx context.Context, data *ScheduleLog) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, scheduleLogRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Data, data.Status, data.Id)
	return err
}

func (m *defaultScheduleLogModel) TableName() string {
	return m.table
}
