// Code generated by goctl. DO NOT EDIT.

package task

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	syncTaskLogFieldNames          = builder.RawFieldNames(&SyncTaskLog{})
	syncTaskLogRows                = strings.Join(syncTaskLogFieldNames, ",")
	syncTaskLogRowsExpectAutoSet   = strings.Join(stringx.Remove(syncTaskLogFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	syncTaskLogRowsWithPlaceHolder = strings.Join(stringx.Remove(syncTaskLogFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	syncTaskLogModel interface {
		Insert(ctx context.Context, data *SyncTaskLog) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*SyncTaskLog, error)
		Update(ctx context.Context, data *SyncTaskLog) error
		Delete(ctx context.Context, id int64) error
	}

	defaultSyncTaskLogModel struct {
		conn  sqlx.SqlConn
		table string
	}

	SyncTaskLog struct {
		Id        int64  `db:"id"`
		TaskId    int64  `db:"task_id"`    // 任务id
		Index     int64  `db:"index"`      // 当前任务的数据下标
		Data      string `db:"data"`       // 原始数据
		Md5       string `db:"md5"`        // data字段进行md5,去重使用
		Status    int64  `db:"status"`     // 状态 0.未开始 1.进行中 2.已完成 3.失败
		ErrorsMsg string `db:"errors_msg"` // 错误原因
	}
)

func newSyncTaskLogModel(conn sqlx.SqlConn) *defaultSyncTaskLogModel {
	return &defaultSyncTaskLogModel{
		conn:  conn,
		table: "`bk_sync_task_log`",
	}
}

func (m *defaultSyncTaskLogModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultSyncTaskLogModel) FindOne(ctx context.Context, id int64) (*SyncTaskLog, error) {

	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", syncTaskLogRows, m.table)

	var resp SyncTaskLog
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSyncTaskLogModel) Insert(ctx context.Context, data *SyncTaskLog) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, syncTaskLogRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.TaskId, data.Index, data.Data, data.Md5, data.Status, data.ErrorsMsg)
	return ret, err
}

func (m *defaultSyncTaskLogModel) Update(ctx context.Context, data *SyncTaskLog) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, syncTaskLogRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.TaskId, data.Index, data.Data, data.Md5, data.Status, data.ErrorsMsg, data.Id)
	return err
}

func (m *defaultSyncTaskLogModel) TableName() string {
	return m.table
}
