// Code generated by goctl. DO NOT EDIT.

package task

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	syncTaskFieldNames          = builder.RawFieldNames(&SyncTask{})
	syncTaskRows                = strings.Join(syncTaskFieldNames, ",")
	syncTaskRowsExpectAutoSet   = strings.Join(stringx.Remove(syncTaskFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	syncTaskRowsWithPlaceHolder = strings.Join(stringx.Remove(syncTaskFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	syncTaskModel interface {
		Insert(ctx context.Context, data *SyncTask) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*SyncTask, error)
		Update(ctx context.Context, data *SyncTask) error
		Delete(ctx context.Context, id int64) error
	}

	defaultSyncTaskModel struct {
		conn  sqlx.SqlConn
		table string
	}

	SyncTask struct {
		Id            int64          `db:"id"`
		OperateId     int64          `db:"operate_id"`      // 操作人id
		Type          int64          `db:"type"`            // 1:导入
		Status        int64          `db:"status"`          // 0:未开始 1:进行中 2:已完成 3:失败
		Param         sql.NullString `db:"param"`           // 排序
		FileId        string         `db:"file_id"`         // 文件id
		FileName      string         `db:"file_name"`       // 文件名称
		FileSheet     int64          `db:"file_sheet"`      // 文件表对象
		FileSheetName string         `db:"file_sheet_name"` // 文件表对象名称
		StartTime     string         `db:"start_time"`      // 开始时间
		EndTime       string         `db:"end_time"`        // 结束时间
		ErrorMsg      sql.NullString `db:"error_msg"`       // 错误信息
		Total         int64          `db:"total"`           // 总条数
		FilterNum     int64          `db:"filter_num"`      // 过滤条数
		PreNum        int64          `db:"pre_num"`         // 预处理条数
		SuccessNum    int64          `db:"success_num"`     // 成功条数
		FailNum       int64          `db:"fail_num"`        // 失败条数
		CreatedAt     time.Time      `db:"created_at"`
		UpdatedAt     time.Time      `db:"updated_at"`
	}
)

func newSyncTaskModel(conn sqlx.SqlConn) *defaultSyncTaskModel {
	return &defaultSyncTaskModel{
		conn:  conn,
		table: "`bk_sync_task`",
	}
}

func (m *defaultSyncTaskModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultSyncTaskModel) FindOne(ctx context.Context, id int64) (*SyncTask, error) {

	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", syncTaskRows, m.table)

	var resp SyncTask
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSyncTaskModel) Insert(ctx context.Context, data *SyncTask) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, syncTaskRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.OperateId, data.Type, data.Status, data.Param, data.FileId, data.FileName, data.FileSheet, data.FileSheetName, data.StartTime, data.EndTime, data.ErrorMsg, data.Total, data.FilterNum, data.PreNum, data.SuccessNum, data.FailNum)
	return ret, err
}

func (m *defaultSyncTaskModel) Update(ctx context.Context, data *SyncTask) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, syncTaskRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.OperateId, data.Type, data.Status, data.Param, data.FileId, data.FileName, data.FileSheet, data.FileSheetName, data.StartTime, data.EndTime, data.ErrorMsg, data.Total, data.FilterNum, data.PreNum, data.SuccessNum, data.FailNum, data.Id)
	return err
}

func (m *defaultSyncTaskModel) TableName() string {
	return m.table
}
