// Code generated by goctl. DO NOT EDIT.

package conversation

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	conversationRecordFieldNames          = builder.RawFieldNames(&ConversationRecord{})
	conversationRecordRows                = strings.Join(conversationRecordFieldNames, ",")
	conversationRecordRowsExpectAutoSet   = strings.Join(stringx.Remove(conversationRecordFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	conversationRecordRowsWithPlaceHolder = strings.Join(stringx.Remove(conversationRecordFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	conversationRecordModel interface {
		Insert(ctx context.Context, data *ConversationRecord) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*ConversationRecord, error)
		Update(ctx context.Context, data *ConversationRecord) error
		Delete(ctx context.Context, id int64) error
	}

	defaultConversationRecordModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ConversationRecord struct {
		Id             int64          `db:"id"`
		ConversationId int64          `db:"conversation_id"` // AI会话ID
		Content        string         `db:"content"`         // 消息内容
		Source         int64          `db:"source"`          // 消息来源 1 系统 2 GPT 3 用户
		Type           int64          `db:"type"`            // 消息类型  1 文字 2 语音
		AudioUrl       sql.NullString `db:"audio_url"`       // 语音文件地址
		MessageId      sql.NullString `db:"message_id"`      // dify返回的消息id
		CreatedAt      time.Time      `db:"created_at"`      // 创建时间
	}
)

func newConversationRecordModel(conn sqlx.SqlConn) *defaultConversationRecordModel {
	return &defaultConversationRecordModel{
		conn:  conn,
		table: "`c_conversation_record`",
	}
}

func (m *defaultConversationRecordModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultConversationRecordModel) FindOne(ctx context.Context, id int64) (*ConversationRecord, error) {

	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", conversationRecordRows, m.table)

	var resp ConversationRecord
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultConversationRecordModel) Insert(ctx context.Context, data *ConversationRecord) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, conversationRecordRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ConversationId, data.Content, data.Source, data.Type, data.AudioUrl, data.MessageId)
	return ret, err
}

func (m *defaultConversationRecordModel) Update(ctx context.Context, data *ConversationRecord) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, conversationRecordRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.ConversationId, data.Content, data.Source, data.Type, data.AudioUrl, data.MessageId, data.Id)
	return err
}

func (m *defaultConversationRecordModel) TableName() string {
	return m.table
}
