// Code generated by goctl. DO NOT EDIT.

package conversation

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	conversationFieldNames          = builder.RawFieldNames(&Conversation{})
	conversationRows                = strings.Join(conversationFieldNames, ",")
	conversationRowsExpectAutoSet   = strings.Join(stringx.Remove(conversationFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	conversationRowsWithPlaceHolder = strings.Join(stringx.Remove(conversationFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	conversationModel interface {
		Insert(ctx context.Context, data *Conversation) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Conversation, error)
		Update(ctx context.Context, data *Conversation) error
		Delete(ctx context.Context, id int64) error
	}

	defaultConversationModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Conversation struct {
		Id             int64     `db:"id"`              // 主键
		UserId         int64     `db:"user_id"`         // 用户ID
		ConversationId string    `db:"conversation_id"` // dify会话id
		PromptId       int64     `db:"prompt_id"`       // P工程ID
		Title          string    `db:"title"`           // 会话标题
		CreatedAt      time.Time `db:"created_at"`      // 创建时间
	}
)

func newConversationModel(conn sqlx.SqlConn) *defaultConversationModel {
	return &defaultConversationModel{
		conn:  conn,
		table: "`c_conversation`",
	}
}

func (m *defaultConversationModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultConversationModel) FindOne(ctx context.Context, id int64) (*Conversation, error) {

	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", conversationRows, m.table)

	var resp Conversation
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultConversationModel) Insert(ctx context.Context, data *Conversation) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, conversationRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.ConversationId, data.PromptId, data.Title)
	return ret, err
}

func (m *defaultConversationModel) Update(ctx context.Context, data *Conversation) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, conversationRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserId, data.ConversationId, data.PromptId, data.Title, data.Id)
	return err
}

func (m *defaultConversationModel) TableName() string {
	return m.table
}
