// Code generated by goctl. DO NOT EDIT.

package behavior

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sessionFieldNames          = builder.RawFieldNames(&Session{})
	sessionRows                = strings.Join(sessionFieldNames, ",")
	sessionRowsExpectAutoSet   = strings.Join(stringx.Remove(sessionFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	sessionRowsWithPlaceHolder = strings.Join(stringx.Remove(sessionFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	sessionModel interface {
		Insert(ctx context.Context, data *Session) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Session, error)
		Update(ctx context.Context, data *Session) error
		Delete(ctx context.Context, id int64) error
	}

	defaultSessionModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Session struct {
		Id        int64     `db:"id"`         // 主键
		Session   string    `db:"session"`    // 会话
		StartTime time.Time `db:"start_time"` // 开始时间
		EndTime   time.Time `db:"end_time"`   // 结束时间
		CreatedAt time.Time `db:"created_at"` // 创建时间
		UpdatedAt time.Time `db:"updated_at"` // 更新时间
	}
)

func newSessionModel(conn sqlx.SqlConn) *defaultSessionModel {
	return &defaultSessionModel{
		conn:  conn,
		table: "`us_session`",
	}
}

func (m *defaultSessionModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultSessionModel) FindOne(ctx context.Context, id int64) (*Session, error) {

	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", sessionRows, m.table)

	var resp Session
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSessionModel) Insert(ctx context.Context, data *Session) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, sessionRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Session, data.StartTime, data.EndTime)
	return ret, err
}

func (m *defaultSessionModel) Update(ctx context.Context, data *Session) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, sessionRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Session, data.StartTime, data.EndTime, data.Id)
	return err
}

func (m *defaultSessionModel) TableName() string {
	return m.table
}
