// Code generated by goctl. DO NOT EDIT.

package behavior

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sessionUserFieldNames          = builder.RawFieldNames(&SessionUser{})
	sessionUserRows                = strings.Join(sessionUserFieldNames, ",")
	sessionUserRowsExpectAutoSet   = strings.Join(stringx.Remove(sessionUserFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	sessionUserRowsWithPlaceHolder = strings.Join(stringx.Remove(sessionUserFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	sessionUserModel interface {
		Insert(ctx context.Context, data *SessionUser) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*SessionUser, error)
		Update(ctx context.Context, data *SessionUser) error
		Delete(ctx context.Context, id int64) error
	}

	defaultSessionUserModel struct {
		conn  sqlx.SqlConn
		table string
	}

	SessionUser struct {
		Id        int64     `db:"id"`         // 主键
		UserId    int64     `db:"user_id"`    // 用户ID
		SessionId int64     `db:"session_id"` // 会话ID
		CreatedAt time.Time `db:"created_at"` // 创建时间
		UpdatedAt time.Time `db:"updated_at"` // 更新时间
	}
)

func newSessionUserModel(conn sqlx.SqlConn) *defaultSessionUserModel {
	return &defaultSessionUserModel{
		conn:  conn,
		table: "`us_session_user`",
	}
}

func (m *defaultSessionUserModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultSessionUserModel) FindOne(ctx context.Context, id int64) (*SessionUser, error) {

	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", sessionUserRows, m.table)

	var resp SessionUser
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSessionUserModel) Insert(ctx context.Context, data *SessionUser) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, sessionUserRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.SessionId)
	return ret, err
}

func (m *defaultSessionUserModel) Update(ctx context.Context, data *SessionUser) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, sessionUserRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserId, data.SessionId, data.Id)
	return err
}

func (m *defaultSessionUserModel) TableName() string {
	return m.table
}
