// Code generated by goctl. DO NOT EDIT.

package behavior

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sessionRecordFieldNames          = builder.RawFieldNames(&SessionRecord{})
	sessionRecordRows                = strings.Join(sessionRecordFieldNames, ",")
	sessionRecordRowsExpectAutoSet   = strings.Join(stringx.Remove(sessionRecordFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	sessionRecordRowsWithPlaceHolder = strings.Join(stringx.Remove(sessionRecordFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	sessionRecordModel interface {
		Insert(ctx context.Context, data *SessionRecord) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*SessionRecord, error)
		Update(ctx context.Context, data *SessionRecord) error
		Delete(ctx context.Context, id int64) error
	}

	defaultSessionRecordModel struct {
		conn  sqlx.SqlConn
		table string
	}

	SessionRecord struct {
		Id        int64          `db:"id"`         // 主键
		SessionId int64          `db:"session_id"` // 会话ID
		EventId   string         `db:"event_id"`   // 事件id
		EventType string         `db:"event_type"` // 事件类型
		EventTime int64          `db:"event_time"` // 事件时间戳
		Page      string         `db:"page"`       // 事件页面
		Appid     string         `db:"appid"`      // 应用ID
		Phone     string         `db:"phone"`      // 手机号
		UserAgent sql.NullString `db:"user_agent"` // 浏览器信息
		Screen    string         `db:"screen"`     // 分辨率
		Language  string         `db:"language"`   // 语言
		Data      sql.NullString `db:"data"`       // 携带数据
		CreatedAt time.Time      `db:"created_at"` // 创建时间
		UpdatedAt time.Time      `db:"updated_at"` // 更新时间
	}
)

func newSessionRecordModel(conn sqlx.SqlConn) *defaultSessionRecordModel {
	return &defaultSessionRecordModel{
		conn:  conn,
		table: "`us_session_record`",
	}
}

func (m *defaultSessionRecordModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultSessionRecordModel) FindOne(ctx context.Context, id int64) (*SessionRecord, error) {

	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", sessionRecordRows, m.table)

	var resp SessionRecord
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSessionRecordModel) Insert(ctx context.Context, data *SessionRecord) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, sessionRecordRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.SessionId, data.EventId, data.EventType, data.EventTime, data.Page, data.Appid, data.Phone, data.UserAgent, data.Screen, data.Language, data.Data)
	return ret, err
}

func (m *defaultSessionRecordModel) Update(ctx context.Context, data *SessionRecord) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, sessionRecordRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.SessionId, data.EventId, data.EventType, data.EventTime, data.Page, data.Appid, data.Phone, data.UserAgent, data.Screen, data.Language, data.Data, data.Id)
	return err
}

func (m *defaultSessionRecordModel) TableName() string {
	return m.table
}
