// Code generated by goctl. DO NOT EDIT.

package code

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	redeemCodeFieldNames          = builder.RawFieldNames(&RedeemCode{})
	redeemCodeRows                = strings.Join(redeemCodeFieldNames, ",")
	redeemCodeRowsExpectAutoSet   = strings.Join(stringx.Remove(redeemCodeFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	redeemCodeRowsWithPlaceHolder = strings.Join(stringx.Remove(redeemCodeFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	redeemCodeModel interface {
		Insert(ctx context.Context, data *RedeemCode) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*RedeemCode, error)
		FindOneByCode(ctx context.Context, code string) (*RedeemCode, error)
		Update(ctx context.Context, data *RedeemCode) error
		Delete(ctx context.Context, id int64) error
	}

	defaultRedeemCodeModel struct {
		conn  sqlx.SqlConn
		table string
	}

	RedeemCode struct {
		Id              int64     `db:"id"`
		Code            string    `db:"code"`              // 兑换码
		Status          int64     `db:"status"`            // 状态 1.未兑换 2.已兑换
		BenefitsGroupId int64     `db:"benefits_group_id"` // 权益组表ID
		Batch           int64     `db:"batch"`             // 批次 格式20240101 当天多个批次就以此类推 202401011
		ValidDate       time.Time `db:"valid_date"`        // 兑换有效期
		Source          int64     `db:"source"`            // 来源 1.外部导入 2.内容生成
		Remark          string    `db:"remark"`            // 备注
		CreatedAt       time.Time `db:"created_at"`        // 添加时间
		UpdatedAt       time.Time `db:"updated_at"`        // 修改时间
	}
)

func newRedeemCodeModel(conn sqlx.SqlConn) *defaultRedeemCodeModel {
	return &defaultRedeemCodeModel{
		conn:  conn,
		table: "`rc_redeem_code`",
	}
}

func (m *defaultRedeemCodeModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultRedeemCodeModel) FindOne(ctx context.Context, id int64) (*RedeemCode, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", redeemCodeRows, m.table)
	var resp RedeemCode
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultRedeemCodeModel) FindOneByCode(ctx context.Context, code string) (*RedeemCode, error) {
	var resp RedeemCode
	query := fmt.Sprintf("select %s from %s where `code` = ? limit 1", redeemCodeRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, code)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultRedeemCodeModel) Insert(ctx context.Context, data *RedeemCode) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, redeemCodeRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Code, data.Status, data.BenefitsGroupId, data.Batch, data.ValidDate, data.Source, data.Remark)
	return ret, err
}

func (m *defaultRedeemCodeModel) Update(ctx context.Context, newData *RedeemCode) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, redeemCodeRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Code, newData.Status, newData.BenefitsGroupId, newData.Batch, newData.ValidDate, newData.Source, newData.Remark, newData.Id)
	return err
}

func (m *defaultRedeemCodeModel) TableName() string {
	return m.table
}
