// Code generated by goctl. DO NOT EDIT.

package live

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	courseFieldNames          = builder.RawFieldNames(&Course{})
	courseRows                = strings.Join(courseFieldNames, ",")
	courseRowsExpectAutoSet   = strings.Join(stringx.Remove(courseFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	courseRowsWithPlaceHolder = strings.Join(stringx.Remove(courseFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	courseModel interface {
		Insert(ctx context.Context, data *Course) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Course, error)
		Update(ctx context.Context, data *Course) error
		Delete(ctx context.Context, id int64) error
	}

	defaultCourseModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Course struct {
		Id          int64     `db:"id"`           // 主键
		CourseNo    int64     `db:"course_no"`    // 来源编号，导数据时使用
		Name        string    `db:"name"`         // 课程名称
		Description string    `db:"description"`  // 课程简介
		TeacherName string    `db:"teacher_name"` // 主讲老师
		PreStep     string    `db:"pre_step"`     // 预制课程步骤
		Homework    string    `db:"homework"`     // 作业要求
		Evaluate    string    `db:"evaluate"`     // 评分标准
		Status      int64     `db:"status"`       // 状态(0.待上架 1.正常 2.已下架)
		Remark      string    `db:"remark"`       // 备注
		CreatedAt   time.Time `db:"created_at"`   // 创建时间
		UpdatedAt   time.Time `db:"updated_at"`   // 更新时间
	}
)

func newCourseModel(conn sqlx.SqlConn) *defaultCourseModel {
	return &defaultCourseModel{
		conn:  conn,
		table: "`ai_course`",
	}
}

func (m *defaultCourseModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultCourseModel) FindOne(ctx context.Context, id int64) (*Course, error) {

	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", courseRows, m.table)

	var resp Course
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCourseModel) Insert(ctx context.Context, data *Course) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, courseRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.CourseNo, data.Name, data.Description, data.TeacherName, data.PreStep, data.Homework, data.Evaluate, data.Status, data.Remark)
	return ret, err
}

func (m *defaultCourseModel) Update(ctx context.Context, data *Course) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, courseRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.CourseNo, data.Name, data.Description, data.TeacherName, data.PreStep, data.Homework, data.Evaluate, data.Status, data.Remark, data.Id)
	return err
}

func (m *defaultCourseModel) TableName() string {
	return m.table
}
