// Code generated by goctl. DO NOT EDIT.

package live

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	liveRoleFieldNames          = builder.RawFieldNames(&LiveRole{})
	liveRoleRows                = strings.Join(liveRoleFieldNames, ",")
	liveRoleRowsExpectAutoSet   = strings.Join(stringx.Remove(liveRoleFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	liveRoleRowsWithPlaceHolder = strings.Join(stringx.Remove(liveRoleFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	liveRoleModel interface {
		Insert(ctx context.Context, data *LiveRole) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*LiveRole, error)
		Update(ctx context.Context, data *LiveRole) error
		Delete(ctx context.Context, id int64) error
	}

	defaultLiveRoleModel struct {
		conn  sqlx.SqlConn
		table string
	}

	LiveRole struct {
		Id        int64     `db:"id"`         // 主键
		RoleNo    int64     `db:"role_no"`    // 数据源角色编号，导数据时使用
		RoleType  string    `db:"role_type"`  // 角色类型 "teacher":教师 | "assistant":助教 | "student":学生
		Name      string    `db:"name"`       // 名称
		Feature   string    `db:"feature"`    // 特点
		CreatedAt time.Time `db:"created_at"` // 创建时间
		UpdatedAt time.Time `db:"updated_at"` // 更新时间
	}
)

func newLiveRoleModel(conn sqlx.SqlConn) *defaultLiveRoleModel {
	return &defaultLiveRoleModel{
		conn:  conn,
		table: "`ai_live_role`",
	}
}

func (m *defaultLiveRoleModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultLiveRoleModel) FindOne(ctx context.Context, id int64) (*LiveRole, error) {

	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", liveRoleRows, m.table)

	var resp LiveRole
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultLiveRoleModel) Insert(ctx context.Context, data *LiveRole) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, liveRoleRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.RoleNo, data.RoleType, data.Name, data.Feature)
	return ret, err
}

func (m *defaultLiveRoleModel) Update(ctx context.Context, data *LiveRole) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, liveRoleRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.RoleNo, data.RoleType, data.Name, data.Feature, data.Id)
	return err
}

func (m *defaultLiveRoleModel) TableName() string {
	return m.table
}
