// Code generated by goctl. DO NOT EDIT.

package live

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	liveBetaRecordsFieldNames          = builder.RawFieldNames(&LiveBetaRecords{})
	liveBetaRecordsRows                = strings.Join(liveBetaRecordsFieldNames, ",")
	liveBetaRecordsRowsExpectAutoSet   = strings.Join(stringx.Remove(liveBetaRecordsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	liveBetaRecordsRowsWithPlaceHolder = strings.Join(stringx.Remove(liveBetaRecordsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	liveBetaRecordsModel interface {
		Insert(ctx context.Context, data *LiveBetaRecords) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*LiveBetaRecords, error)
		Update(ctx context.Context, data *LiveBetaRecords) error
		Delete(ctx context.Context, id int64) error
	}

	defaultLiveBetaRecordsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	LiveBetaRecords struct {
		Id        int64     `db:"id"`
		Phone     string    `db:"phone"`      // 用户手机号
		UserName  string    `db:"user_name"`  // 用户名
		Company   string    `db:"company"`    // 公司名
		Status    int64     `db:"status"`     // 审核状态 1.审核中 2.审核通过 3.审核不通过
		Remark    string    `db:"remark"`     // 备注信息
		OperateId int64     `db:"operate_id"` // 操作人id
		OperateAt int64     `db:"operate_at"` // 操作时间戳
		CreatedAt time.Time `db:"created_at"` // 创建时间
		UpdatedAt time.Time `db:"updated_at"` // 更新时间
	}
)

func newLiveBetaRecordsModel(conn sqlx.SqlConn) *defaultLiveBetaRecordsModel {
	return &defaultLiveBetaRecordsModel{
		conn:  conn,
		table: "`ai_live_beta_records`",
	}
}

func (m *defaultLiveBetaRecordsModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultLiveBetaRecordsModel) FindOne(ctx context.Context, id int64) (*LiveBetaRecords, error) {

	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", liveBetaRecordsRows, m.table)

	var resp LiveBetaRecords
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultLiveBetaRecordsModel) Insert(ctx context.Context, data *LiveBetaRecords) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, liveBetaRecordsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Phone, data.UserName, data.Company, data.Status, data.Remark, data.OperateId, data.OperateAt)
	return ret, err
}

func (m *defaultLiveBetaRecordsModel) Update(ctx context.Context, data *LiveBetaRecords) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, liveBetaRecordsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Phone, data.UserName, data.Company, data.Status, data.Remark, data.OperateId, data.OperateAt, data.Id)
	return err
}

func (m *defaultLiveBetaRecordsModel) TableName() string {
	return m.table
}
