// Code generated by goctl. DO NOT EDIT.

package system

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	dictWhiteFieldNames          = builder.RawFieldNames(&DictWhite{})
	dictWhiteRows                = strings.Join(dictWhiteFieldNames, ",")
	dictWhiteRowsExpectAutoSet   = strings.Join(stringx.Remove(dictWhiteFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	dictWhiteRowsWithPlaceHolder = strings.Join(stringx.Remove(dictWhiteFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	dictWhiteModel interface {
		Insert(ctx context.Context, data *DictWhite) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*DictWhite, error)
		Update(ctx context.Context, data *DictWhite) error
		Delete(ctx context.Context, id int64) error
	}

	defaultDictWhiteModel struct {
		conn  sqlx.SqlConn
		table string
	}

	DictWhite struct {
		Id        int64     `db:"id"`         // 主键
		Key       string    `db:"key"`        // 字典Key
		Remark    string    `db:"remark"`     // 备注
		CreatedAt time.Time `db:"created_at"` // 修改时间
		UpdatedAt time.Time `db:"updated_at"` // 修改时间
	}
)

func newDictWhiteModel(conn sqlx.SqlConn) *defaultDictWhiteModel {
	return &defaultDictWhiteModel{
		conn:  conn,
		table: "`sys_dict_white`",
	}
}

func (m *defaultDictWhiteModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultDictWhiteModel) FindOne(ctx context.Context, id int64) (*DictWhite, error) {

	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", dictWhiteRows, m.table)

	var resp DictWhite
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultDictWhiteModel) Insert(ctx context.Context, data *DictWhite) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, dictWhiteRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Key, data.Remark)
	return ret, err
}

func (m *defaultDictWhiteModel) Update(ctx context.Context, data *DictWhite) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, dictWhiteRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Key, data.Remark, data.Id)
	return err
}

func (m *defaultDictWhiteModel) TableName() string {
	return m.table
}
