// Code generated by goctl. DO NOT EDIT.

package live_course

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	chatRoomFieldNames          = builder.RawFieldNames(&ChatRoom{})
	chatRoomRows                = strings.Join(chatRoomFieldNames, ",")
	chatRoomRowsExpectAutoSet   = strings.Join(stringx.Remove(chatRoomFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	chatRoomRowsWithPlaceHolder = strings.Join(stringx.Remove(chatRoomFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	chatRoomModel interface {
		Insert(ctx context.Context, data *ChatRoom) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*ChatRoom, error)
		Update(ctx context.Context, data *ChatRoom) error
		Delete(ctx context.Context, id int64) error
	}

	defaultChatRoomModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ChatRoom struct {
		Id        int64     `db:"id"`         // 主键 Id
		StreamId  int64     `db:"stream_id"`  // 直播ID
		RoomId    string    `db:"room_id"`    // 聊天房间号
		RoomName  string    `db:"room_name"`  // 聊天室名称
		Type      int64     `db:"type"`       // 类型：1.主聊天室 2.讲师聊天室
		Status    int64     `db:"status"`     // 聊天室状态：1.正常 2.关闭
		CreatedAt time.Time `db:"created_at"` // 创建时间
		UpdatedAt time.Time `db:"updated_at"` // 更新时间
	}
)

func newChatRoomModel(conn sqlx.SqlConn) *defaultChatRoomModel {
	return &defaultChatRoomModel{
		conn:  conn,
		table: "`lv_chat_room`",
	}
}

func (m *defaultChatRoomModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultChatRoomModel) FindOne(ctx context.Context, id int64) (*ChatRoom, error) {

	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", chatRoomRows, m.table)

	var resp ChatRoom
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultChatRoomModel) Insert(ctx context.Context, data *ChatRoom) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, chatRoomRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.StreamId, data.RoomId, data.RoomName, data.Type, data.Status)
	return ret, err
}

func (m *defaultChatRoomModel) Update(ctx context.Context, data *ChatRoom) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, chatRoomRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.StreamId, data.RoomId, data.RoomName, data.Type, data.Status, data.Id)
	return err
}

func (m *defaultChatRoomModel) TableName() string {
	return m.table
}
