// Code generated by goctl. DO NOT EDIT.

package live_course

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	signalLogFieldNames          = builder.RawFieldNames(&SignalLog{})
	signalLogRows                = strings.Join(signalLogFieldNames, ",")
	signalLogRowsExpectAutoSet   = strings.Join(stringx.Remove(signalLogFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	signalLogRowsWithPlaceHolder = strings.Join(stringx.Remove(signalLogFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	signalLogModel interface {
		Insert(ctx context.Context, data *SignalLog) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*SignalLog, error)
		Update(ctx context.Context, data *SignalLog) error
		Delete(ctx context.Context, id int64) error
	}

	defaultSignalLogModel struct {
		conn  sqlx.SqlConn
		table string
	}

	SignalLog struct {
		Id         int64     `db:"id"`           // 主键 Id
		StreamId   int64     `db:"stream_id"`    // 直播ID
		ChatRoomId int64     `db:"chat_room_id"` // 聊天室ID
		Event      string    `db:"event"`        // 事件名称
		EventType  string    `db:"event_type"`   // 事件细分分类
		RecvType   int64     `db:"recv_type"`    // 信令接收方：1.全员 2.个人
		ToAccount  string    `db:"to_account"`   // 信令接收方账号
		Content    string    `db:"content"`      // 信令内容（JSON 格式）
		CreatedAt  time.Time `db:"created_at"`   // 创建时间
		UpdatedAt  time.Time `db:"updated_at"`   // 更新时间
	}
)

func newSignalLogModel(conn sqlx.SqlConn) *defaultSignalLogModel {
	return &defaultSignalLogModel{
		conn:  conn,
		table: "`lv_signal_log`",
	}
}

func (m *defaultSignalLogModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultSignalLogModel) FindOne(ctx context.Context, id int64) (*SignalLog, error) {

	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", signalLogRows, m.table)

	var resp SignalLog
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSignalLogModel) Insert(ctx context.Context, data *SignalLog) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, signalLogRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.StreamId, data.ChatRoomId, data.Event, data.EventType, data.RecvType, data.ToAccount, data.Content)
	return ret, err
}

func (m *defaultSignalLogModel) Update(ctx context.Context, data *SignalLog) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, signalLogRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.StreamId, data.ChatRoomId, data.Event, data.EventType, data.RecvType, data.ToAccount, data.Content, data.Id)
	return err
}

func (m *defaultSignalLogModel) TableName() string {
	return m.table
}
