// Code generated by goctl. DO NOT EDIT.

package live_course

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userFieldNames          = builder.RawFieldNames(&User{})
	userRows                = strings.Join(userFieldNames, ",")
	userRowsExpectAutoSet   = strings.Join(stringx.Remove(userFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userRowsWithPlaceHolder = strings.Join(stringx.Remove(userFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	userModel interface {
		Insert(ctx context.Context, data *User) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*User, error)
		FindOneByStreamIdUserId(ctx context.Context, streamId int64, userId int64) (*User, error)
		Update(ctx context.Context, data *User) error
		Delete(ctx context.Context, id int64) error
	}

	defaultUserModel struct {
		conn  sqlx.SqlConn
		table string
	}

	User struct {
		Id        int64     `db:"id"`          // 主键 Id
		StreamId  int64     `db:"stream_id"`   // 直播ID
		UserId    int64     `db:"user_id"`     // 用户ID
		UserName  string    `db:"user_name"`   // 用户名
		ImUserId  string    `db:"im_user_id"`  // IM用户ID
		RoleType  int64     `db:"role_type"`   // 用户角色类型：1 主讲 2 学生
		IsMute    int64     `db:"is_mute"`     // 是否禁言（1是，2否）
		MuteEndAt int64     `db:"mute_end_at"` // 禁言结束时间戳
		CreatedAt time.Time `db:"created_at"`  // 创建时间
		UpdatedAt time.Time `db:"updated_at"`  // 更新时间
	}
)

func newUserModel(conn sqlx.SqlConn) *defaultUserModel {
	return &defaultUserModel{
		conn:  conn,
		table: "`lv_user`",
	}
}

func (m *defaultUserModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUserModel) FindOne(ctx context.Context, id int64) (*User, error) {

	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userRows, m.table)

	var resp User
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserModel) FindOneByStreamIdUserId(ctx context.Context, streamId int64, userId int64) (*User, error) {
	var resp User

	query := fmt.Sprintf("select %s from %s where `stream_id` = ? and `user_id` = ? limit 1", userRows, m.table)

	err := m.conn.QueryRowCtx(ctx, &resp, query, streamId, userId)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserModel) Insert(ctx context.Context, data *User) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, userRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.StreamId, data.UserId, data.UserName, data.ImUserId, data.RoleType, data.IsMute, data.MuteEndAt)
	return ret, err
}

func (m *defaultUserModel) Update(ctx context.Context, newData *User) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.StreamId, newData.UserId, newData.UserName, newData.ImUserId, newData.RoleType, newData.IsMute, newData.MuteEndAt, newData.Id)
	return err
}

func (m *defaultUserModel) TableName() string {
	return m.table
}
