// Code generated by goctl. DO NOT EDIT.

package write_ppt

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	courseOutlineFieldNames          = builder.RawFieldNames(&CourseOutline{})
	courseOutlineRows                = strings.Join(courseOutlineFieldNames, ",")
	courseOutlineRowsExpectAutoSet   = strings.Join(stringx.Remove(courseOutlineFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	courseOutlineRowsWithPlaceHolder = strings.Join(stringx.Remove(courseOutlineFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	courseOutlineModel interface {
		Insert(ctx context.Context, data *CourseOutline) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*CourseOutline, error)
		Update(ctx context.Context, data *CourseOutline) error
		Delete(ctx context.Context, id int64) error
	}

	defaultCourseOutlineModel struct {
		conn  sqlx.SqlConn
		table string
	}

	CourseOutline struct {
		Id        int64     `db:"id"`         // 主键ID
		Name      string    `db:"name"`       // 单元名
		Unit      int64     `db:"unit"`       // 单元
		Category  int64     `db:"category"`   // 分类 1.细节 2.表达 3.布局
		Topic     string    `db:"topic"`      // 写作要求
		Series    string    `db:"series"`     // 课程系列
		Status    int64     `db:"status"`     // 数据是否已处理 1.未处理 2.已处理
		CreatedAt time.Time `db:"created_at"` // 创建时间
		UpdatedAt time.Time `db:"updated_at"` // 更新时间
	}
)

func newCourseOutlineModel(conn sqlx.SqlConn) *defaultCourseOutlineModel {
	return &defaultCourseOutlineModel{
		conn:  conn,
		table: "`aw_course_outline`",
	}
}

func (m *defaultCourseOutlineModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultCourseOutlineModel) FindOne(ctx context.Context, id int64) (*CourseOutline, error) {

	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", courseOutlineRows, m.table)

	var resp CourseOutline
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCourseOutlineModel) Insert(ctx context.Context, data *CourseOutline) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, courseOutlineRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Name, data.Unit, data.Category, data.Topic, data.Series, data.Status)
	return ret, err
}

func (m *defaultCourseOutlineModel) Update(ctx context.Context, data *CourseOutline) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, courseOutlineRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Name, data.Unit, data.Category, data.Topic, data.Series, data.Status, data.Id)
	return err
}

func (m *defaultCourseOutlineModel) TableName() string {
	return m.table
}
