// Code generated by goctl. DO NOT EDIT.

package write_ppt

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	gradeCourseSeriesFieldNames          = builder.RawFieldNames(&GradeCourseSeries{})
	gradeCourseSeriesRows                = strings.Join(gradeCourseSeriesFieldNames, ",")
	gradeCourseSeriesRowsExpectAutoSet   = strings.Join(stringx.Remove(gradeCourseSeriesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	gradeCourseSeriesRowsWithPlaceHolder = strings.Join(stringx.Remove(gradeCourseSeriesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	gradeCourseSeriesModel interface {
		Insert(ctx context.Context, data *GradeCourseSeries) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*GradeCourseSeries, error)
		Update(ctx context.Context, data *GradeCourseSeries) error
		Delete(ctx context.Context, id int64) error
	}

	defaultGradeCourseSeriesModel struct {
		conn  sqlx.SqlConn
		table string
	}

	GradeCourseSeries struct {
		Id           int64     `db:"id"`            // 主键
		Grade        int64     `db:"grade"`         // 年级
		CourseSeries string    `db:"course_series"` // 课程系列
		CreatedAt    time.Time `db:"created_at"`    // 创建时间
		UpdatedAt    time.Time `db:"updated_at"`    // 更新时间
	}
)

func newGradeCourseSeriesModel(conn sqlx.SqlConn) *defaultGradeCourseSeriesModel {
	return &defaultGradeCourseSeriesModel{
		conn:  conn,
		table: "`aw_grade_course_series`",
	}
}

func (m *defaultGradeCourseSeriesModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultGradeCourseSeriesModel) FindOne(ctx context.Context, id int64) (*GradeCourseSeries, error) {

	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", gradeCourseSeriesRows, m.table)

	var resp GradeCourseSeries
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultGradeCourseSeriesModel) Insert(ctx context.Context, data *GradeCourseSeries) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, gradeCourseSeriesRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Grade, data.CourseSeries)
	return ret, err
}

func (m *defaultGradeCourseSeriesModel) Update(ctx context.Context, data *GradeCourseSeries) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, gradeCourseSeriesRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Grade, data.CourseSeries, data.Id)
	return err
}

func (m *defaultGradeCourseSeriesModel) TableName() string {
	return m.table
}
