// Code generated by goctl. DO NOT EDIT.

package write_ppt

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	lessonFieldNames          = builder.RawFieldNames(&Lesson{})
	lessonRows                = strings.Join(lessonFieldNames, ",")
	lessonRowsExpectAutoSet   = strings.Join(stringx.Remove(lessonFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	lessonRowsWithPlaceHolder = strings.Join(stringx.Remove(lessonFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	lessonModel interface {
		Insert(ctx context.Context, data *Lesson) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Lesson, error)
		Update(ctx context.Context, data *Lesson) error
		Delete(ctx context.Context, id int64) error
	}

	defaultLessonModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Lesson struct {
		Id                int64     `db:"id"`                  // 主键
		CourseOutlineId   int64     `db:"course_outline_id"`   // 私教写作大纲
		LessonNo          int64     `db:"lesson_no"`           // 原数据来源ID
		Title             string    `db:"title"`               // 课程名
		SubTitle          string    `db:"sub_title"`           // 子标题
		LessonNumber      int64     `db:"lesson_number"`       // 课节序号
		LessonType        int64     `db:"lesson_type"`         // 课节类型 1.技巧 2.赏析
		LessonContent     string    `db:"lesson_content"`      // 讲稿
		LessonContentText string    `db:"lesson_content_text"` // 讲稿中的纯文本内容
		Notes             string    `db:"notes"`               // 笔记
		PptFiles          string    `db:"ppt_files"`           // ppt 文件 url 列表
		MindSlices        string    `db:"mind_slices"`         // 脑图步骤 json
		MindFull          string    `db:"mind_full"`           // 完整脑图 json
		AudioUrl          string    `db:"audio_url"`           // 讲稿音频地址
		ReviewStatus      int64     `db:"review_status"`       // 审核状态 1.初始录入 2.审核中 3.审核通过 4.审核未通过 5.下架
		CreatedAt         time.Time `db:"created_at"`          // 创建时间
		UpdatedAt         time.Time `db:"updated_at"`          // 更新时间
	}
)

func newLessonModel(conn sqlx.SqlConn) *defaultLessonModel {
	return &defaultLessonModel{
		conn:  conn,
		table: "`aw_lesson`",
	}
}

func (m *defaultLessonModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultLessonModel) FindOne(ctx context.Context, id int64) (*Lesson, error) {

	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", lessonRows, m.table)

	var resp Lesson
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultLessonModel) Insert(ctx context.Context, data *Lesson) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, lessonRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.CourseOutlineId, data.LessonNo, data.Title, data.SubTitle, data.LessonNumber, data.LessonType, data.LessonContent, data.LessonContentText, data.Notes, data.PptFiles, data.MindSlices, data.MindFull, data.AudioUrl, data.ReviewStatus)
	return ret, err
}

func (m *defaultLessonModel) Update(ctx context.Context, data *Lesson) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, lessonRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.CourseOutlineId, data.LessonNo, data.Title, data.SubTitle, data.LessonNumber, data.LessonType, data.LessonContent, data.LessonContentText, data.Notes, data.PptFiles, data.MindSlices, data.MindFull, data.AudioUrl, data.ReviewStatus, data.Id)
	return err
}

func (m *defaultLessonModel) TableName() string {
	return m.table
}
