// Code generated by goctl. DO NOT EDIT.

package lesson

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	courseFieldNames          = builder.RawFieldNames(&Course{})
	courseRows                = strings.Join(courseFieldNames, ",")
	courseRowsExpectAutoSet   = strings.Join(stringx.Remove(courseFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	courseRowsWithPlaceHolder = strings.Join(stringx.Remove(courseFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	courseModel interface {
		Insert(ctx context.Context, data *Course) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Course, error)
		FindOneByGradeTermBizType(ctx context.Context, grade int64, term int64, bizType int64) (*Course, error)
		Update(ctx context.Context, data *Course) error
		Delete(ctx context.Context, id int64) error
	}

	defaultCourseModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Course struct {
		Id          int64          `db:"id"`           // 主键ID
		Name        string         `db:"name"`         // 课程名称
		Grade       int64          `db:"grade"`        // 所属年级
		Term        int64          `db:"term"`         // 学期 1.上学期 2.下学期 3.学年
		BizType     int64          `db:"biz_type"`     // 课程所属业务类型 1.阅读理解
		PlanType    int64          `db:"plan_type"`    // 规划类型 1.长期规划 2.周规划
		Intro       sql.NullString `db:"intro"`        // 课程介绍
		LearnTarget string         `db:"learn_target"` // 学习目标
		CreatedAt   time.Time      `db:"created_at"`   // 创建时间
		UpdatedAt   time.Time      `db:"updated_at"`   // 更新时间
	}
)

func newCourseModel(conn sqlx.SqlConn) *defaultCourseModel {
	return &defaultCourseModel{
		conn:  conn,
		table: "`ls_course`",
	}
}

func (m *defaultCourseModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultCourseModel) FindOne(ctx context.Context, id int64) (*Course, error) {

	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", courseRows, m.table)

	var resp Course
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCourseModel) FindOneByGradeTermBizType(ctx context.Context, grade int64, term int64, bizType int64) (*Course, error) {
	var resp Course

	query := fmt.Sprintf("select %s from %s where `grade` = ? and `term` = ? and `biz_type` = ? limit 1", courseRows, m.table)

	err := m.conn.QueryRowCtx(ctx, &resp, query, grade, term, bizType)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCourseModel) Insert(ctx context.Context, data *Course) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, courseRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Name, data.Grade, data.Term, data.BizType, data.PlanType, data.Intro, data.LearnTarget)
	return ret, err
}

func (m *defaultCourseModel) Update(ctx context.Context, newData *Course) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, courseRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Name, newData.Grade, newData.Term, newData.BizType, newData.PlanType, newData.Intro, newData.LearnTarget, newData.Id)
	return err
}

func (m *defaultCourseModel) TableName() string {
	return m.table
}
