// Code generated by goctl. DO NOT EDIT.

package lesson

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	courseOutlineFieldNames          = builder.RawFieldNames(&CourseOutline{})
	courseOutlineRows                = strings.Join(courseOutlineFieldNames, ",")
	courseOutlineRowsExpectAutoSet   = strings.Join(stringx.Remove(courseOutlineFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	courseOutlineRowsWithPlaceHolder = strings.Join(stringx.Remove(courseOutlineFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	courseOutlineModel interface {
		Insert(ctx context.Context, data *CourseOutline) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*CourseOutline, error)
		Update(ctx context.Context, data *CourseOutline) error
		Delete(ctx context.Context, id int64) error
	}

	defaultCourseOutlineModel struct {
		conn  sqlx.SqlConn
		table string
	}

	CourseOutline struct {
		Id            int64        `db:"id"`              // 主键ID
		CourseId      int64        `db:"course_id"`       // 课程ID
		Unit          string       `db:"unit"`            // 单元名称
		Name          string       `db:"name"`            // 章节名称
		LessonType    int64        `db:"lesson_type"`     // 课程类型 1.主线课 2.月考 3.小灶课
		Grade         int64        `db:"grade"`           // 所属年级
		LessonGroupNo string       `db:"lesson_group_no"` // 课程组编号
		ExpectMonth   int64        `db:"expect_month"`    // 预期月份
		ExpectDate    sql.NullTime `db:"expect_date"`     // 预期上课日期
		Title         string       `db:"title"`           // 标题
		SubTitle      string       `db:"sub_title"`       // 副标题
		LearnTarget   string       `db:"learn_target"`    // 学习目标
		Sequence      float64      `db:"sequence"`        // 排序，正序，月份相同排序
		CreatedAt     time.Time    `db:"created_at"`      // 创建时间
		UpdatedAt     time.Time    `db:"updated_at"`      // 更新时间
		Remark        string       `db:"remark"`          // 导入时使用的课节名称
		MarkId        int64        `db:"mark_id"`         // 标记 id, 主线课小语文 id，小灶课为原理讲解 id
	}
)

func newCourseOutlineModel(conn sqlx.SqlConn) *defaultCourseOutlineModel {
	return &defaultCourseOutlineModel{
		conn:  conn,
		table: "`ls_course_outline`",
	}
}

func (m *defaultCourseOutlineModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultCourseOutlineModel) FindOne(ctx context.Context, id int64) (*CourseOutline, error) {

	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", courseOutlineRows, m.table)

	var resp CourseOutline
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCourseOutlineModel) Insert(ctx context.Context, data *CourseOutline) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, courseOutlineRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.CourseId, data.Unit, data.Name, data.LessonType, data.Grade, data.LessonGroupNo, data.ExpectMonth, data.ExpectDate, data.Title, data.SubTitle, data.LearnTarget, data.Sequence, data.Remark, data.MarkId)
	return ret, err
}

func (m *defaultCourseOutlineModel) Update(ctx context.Context, data *CourseOutline) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, courseOutlineRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.CourseId, data.Unit, data.Name, data.LessonType, data.Grade, data.LessonGroupNo, data.ExpectMonth, data.ExpectDate, data.Title, data.SubTitle, data.LearnTarget, data.Sequence, data.Remark, data.MarkId, data.Id)
	return err
}

func (m *defaultCourseOutlineModel) TableName() string {
	return m.table
}
