// Code generated by goctl. DO NOT EDIT.

package lesson

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userLessonAnswerFieldNames          = builder.RawFieldNames(&UserLessonAnswer{})
	userLessonAnswerRows                = strings.Join(userLessonAnswerFieldNames, ",")
	userLessonAnswerRowsExpectAutoSet   = strings.Join(stringx.Remove(userLessonAnswerFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userLessonAnswerRowsWithPlaceHolder = strings.Join(stringx.Remove(userLessonAnswerFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	userLessonAnswerModel interface {
		Insert(ctx context.Context, data *UserLessonAnswer) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*UserLessonAnswer, error)
		Update(ctx context.Context, data *UserLessonAnswer) error
		Delete(ctx context.Context, id int64) error
	}

	defaultUserLessonAnswerModel struct {
		conn  sqlx.SqlConn
		table string
	}

	UserLessonAnswer struct {
		Id                 int64     `db:"id"`                    // 主键
		UserId             int64     `db:"user_id"`               // 用户ID
		UserLessonDetailId int64     `db:"user_lesson_detail_id"` // 用户学习详情ID
		LessonType         int64     `db:"lesson_type"`           // 规划业务类型 1.课程 2.月考（单条记录更新）
		MediumType         int64     `db:"medium_type"`           // 回答类型
		Content            string    `db:"content"`               // 内容 类型为选择，则为选项 文本则为文本 语音则为解析文本
		Url                string    `db:"url"`                   // 资源地址，针对语音形式的回答
		Duration           int64     `db:"duration"`              // 时长，单位秒
		Analysis           string    `db:"analysis"`              // 解析，非选择题时，GPT解析记录
		ConversationId     string    `db:"conversation_id"`       // 大模型上下文标识
		IsGood             int64     `db:"is_good"`               // 用户点赞 0.默认值 1.点赞 2.点踩
		CreatedAt          time.Time `db:"created_at"`            // 添加时间
		UpdatedAt          time.Time `db:"updated_at"`            // 修改时间
	}
)

func newUserLessonAnswerModel(conn sqlx.SqlConn) *defaultUserLessonAnswerModel {
	return &defaultUserLessonAnswerModel{
		conn:  conn,
		table: "`ls_user_lesson_answer`",
	}
}

func (m *defaultUserLessonAnswerModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUserLessonAnswerModel) FindOne(ctx context.Context, id int64) (*UserLessonAnswer, error) {

	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userLessonAnswerRows, m.table)

	var resp UserLessonAnswer
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserLessonAnswerModel) Insert(ctx context.Context, data *UserLessonAnswer) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, userLessonAnswerRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.UserLessonDetailId, data.LessonType, data.MediumType, data.Content, data.Url, data.Duration, data.Analysis, data.ConversationId, data.IsGood)
	return ret, err
}

func (m *defaultUserLessonAnswerModel) Update(ctx context.Context, data *UserLessonAnswer) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userLessonAnswerRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserId, data.UserLessonDetailId, data.LessonType, data.MediumType, data.Content, data.Url, data.Duration, data.Analysis, data.ConversationId, data.IsGood, data.Id)
	return err
}

func (m *defaultUserLessonAnswerModel) TableName() string {
	return m.table
}
