// Code generated by goctl. DO NOT EDIT.

package lesson

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userScheduleDetailFieldNames          = builder.RawFieldNames(&UserScheduleDetail{})
	userScheduleDetailRows                = strings.Join(userScheduleDetailFieldNames, ",")
	userScheduleDetailRowsExpectAutoSet   = strings.Join(stringx.Remove(userScheduleDetailFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userScheduleDetailRowsWithPlaceHolder = strings.Join(stringx.Remove(userScheduleDetailFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	userScheduleDetailModel interface {
		Insert(ctx context.Context, data *UserScheduleDetail) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*UserScheduleDetail, error)
		Update(ctx context.Context, data *UserScheduleDetail) error
		Delete(ctx context.Context, id int64) error
	}

	defaultUserScheduleDetailModel struct {
		conn  sqlx.SqlConn
		table string
	}

	UserScheduleDetail struct {
		Id              int64        `db:"id"`                // 主键ID
		UserId          int64        `db:"user_id"`           // 用户ID
		UserScheduleId  int64        `db:"user_schedule_id"`  // 用户规划ID
		LessonType      int64        `db:"lesson_type"`       // 课程类型 1.课节 2.月考
		CourseOutlineId int64        `db:"course_outline_id"` // 课程大纲ID
		CourseId        int64        `db:"course_id"`         // 课程表ID
		LessonId        int64        `db:"lesson_id"`         // 课节ID
		PlannedDate     sql.NullTime `db:"planned_date"`      // 规划安排日期
		Grade           int64        `db:"grade"`             // 所属年级
		Status          int64        `db:"status"`            // 学习状态 1 未学习 2.进行中 3.已学习
		Sequence        float64      `db:"sequence"`          // 排序，正序，月份相同排序
		CreatedAt       time.Time    `db:"created_at"`        // 创建时间
		UpdatedAt       time.Time    `db:"updated_at"`        // 更新时间
	}
)

func newUserScheduleDetailModel(conn sqlx.SqlConn) *defaultUserScheduleDetailModel {
	return &defaultUserScheduleDetailModel{
		conn:  conn,
		table: "`ls_user_schedule_detail`",
	}
}

func (m *defaultUserScheduleDetailModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUserScheduleDetailModel) FindOne(ctx context.Context, id int64) (*UserScheduleDetail, error) {

	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userScheduleDetailRows, m.table)

	var resp UserScheduleDetail
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserScheduleDetailModel) Insert(ctx context.Context, data *UserScheduleDetail) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, userScheduleDetailRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.UserScheduleId, data.LessonType, data.CourseOutlineId, data.CourseId, data.LessonId, data.PlannedDate, data.Grade, data.Status, data.Sequence)
	return ret, err
}

func (m *defaultUserScheduleDetailModel) Update(ctx context.Context, data *UserScheduleDetail) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userScheduleDetailRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserId, data.UserScheduleId, data.LessonType, data.CourseOutlineId, data.CourseId, data.LessonId, data.PlannedDate, data.Grade, data.Status, data.Sequence, data.Id)
	return err
}

func (m *defaultUserScheduleDetailModel) TableName() string {
	return m.table
}
