// Code generated by goctl. DO NOT EDIT.

package lesson

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userScheduleFieldNames          = builder.RawFieldNames(&UserSchedule{})
	userScheduleRows                = strings.Join(userScheduleFieldNames, ",")
	userScheduleRowsExpectAutoSet   = strings.Join(stringx.Remove(userScheduleFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userScheduleRowsWithPlaceHolder = strings.Join(stringx.Remove(userScheduleFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	userScheduleModel interface {
		Insert(ctx context.Context, data *UserSchedule) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*UserSchedule, error)
		Update(ctx context.Context, data *UserSchedule) error
		Delete(ctx context.Context, id int64) error
	}

	defaultUserScheduleModel struct {
		conn  sqlx.SqlConn
		table string
	}

	UserSchedule struct {
		Id        int64        `db:"id"`         // 主键ID
		UserId    int64        `db:"user_id"`    // 用户ID
		PlanType  int64        `db:"plan_type"`  // 规划类型 1.长期规划 2.周规划
		BizType   int64        `db:"biz_type"`   // 课程所属业务类型 1.阅读理解
		IsDynamic int64        `db:"is_dynamic"` // 是否动态规划 1.否 固定课程 2.是 动态生成
		Status    int64        `db:"status"`     // 规划状态 1 正常
		EndDate   sql.NullTime `db:"end_date"`   // 规划结束日期
		CreatedAt time.Time    `db:"created_at"` // 创建时间
		UpdatedAt time.Time    `db:"updated_at"` // 更新时间
	}
)

func newUserScheduleModel(conn sqlx.SqlConn) *defaultUserScheduleModel {
	return &defaultUserScheduleModel{
		conn:  conn,
		table: "`ls_user_schedule`",
	}
}

func (m *defaultUserScheduleModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUserScheduleModel) FindOne(ctx context.Context, id int64) (*UserSchedule, error) {

	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userScheduleRows, m.table)

	var resp UserSchedule
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserScheduleModel) Insert(ctx context.Context, data *UserSchedule) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, userScheduleRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.PlanType, data.BizType, data.IsDynamic, data.Status, data.EndDate)
	return ret, err
}

func (m *defaultUserScheduleModel) Update(ctx context.Context, data *UserSchedule) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userScheduleRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserId, data.PlanType, data.BizType, data.IsDynamic, data.Status, data.EndDate, data.Id)
	return err
}

func (m *defaultUserScheduleModel) TableName() string {
	return m.table
}
