// Code generated by goctl. DO NOT EDIT.

package lesson

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userLessonDetailFieldNames          = builder.RawFieldNames(&UserLessonDetail{})
	userLessonDetailRows                = strings.Join(userLessonDetailFieldNames, ",")
	userLessonDetailRowsExpectAutoSet   = strings.Join(stringx.Remove(userLessonDetailFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userLessonDetailRowsWithPlaceHolder = strings.Join(stringx.Remove(userLessonDetailFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	userLessonDetailModel interface {
		Insert(ctx context.Context, data *UserLessonDetail) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*UserLessonDetail, error)
		Update(ctx context.Context, data *UserLessonDetail) error
		Delete(ctx context.Context, id int64) error
	}

	defaultUserLessonDetailModel struct {
		conn  sqlx.SqlConn
		table string
	}

	UserLessonDetail struct {
		Id                 int64        `db:"id"`                    // 主键
		UserId             int64        `db:"user_id"`               // 用户ID
		UserLessonRecordId int64        `db:"user_lesson_record_id"` // 用户学习记录ID
		QuestionId         int64        `db:"question_id"`           // 问题ID
		QuestionUsageType  int64        `db:"question_usage_type"`   // 使用类型，1.例题 2.练习题
		LessonType         int64        `db:"lesson_type"`           // 规划业务类型，1.课程 2.月考
		Status             int64        `db:"status"`                // 答题 态.1.进行 2.完成 3.跳过
		Result             int64        `db:"result"`                // 是否正确 0.未知，1.正确 2.错误
		StartTime          time.Time    `db:"start_time"`            // 开始时间
		FinishTime         sql.NullTime `db:"finish_time"`           // 完成时间
		CreatedAt          time.Time    `db:"created_at"`            // 添加时间
		UpdatedAt          time.Time    `db:"updated_at"`            // 修改时间
	}
)

func newUserLessonDetailModel(conn sqlx.SqlConn) *defaultUserLessonDetailModel {
	return &defaultUserLessonDetailModel{
		conn:  conn,
		table: "`ls_user_lesson_detail`",
	}
}

func (m *defaultUserLessonDetailModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUserLessonDetailModel) FindOne(ctx context.Context, id int64) (*UserLessonDetail, error) {

	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userLessonDetailRows, m.table)

	var resp UserLessonDetail
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserLessonDetailModel) Insert(ctx context.Context, data *UserLessonDetail) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, userLessonDetailRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.UserLessonRecordId, data.QuestionId, data.QuestionUsageType, data.LessonType, data.Status, data.Result, data.StartTime, data.FinishTime)
	return ret, err
}

func (m *defaultUserLessonDetailModel) Update(ctx context.Context, data *UserLessonDetail) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userLessonDetailRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserId, data.UserLessonRecordId, data.QuestionId, data.QuestionUsageType, data.LessonType, data.Status, data.Result, data.StartTime, data.FinishTime, data.Id)
	return err
}

func (m *defaultUserLessonDetailModel) TableName() string {
	return m.table
}
