// Code generated by goctl. DO NOT EDIT.

package lesson

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userLessonRecordFieldNames          = builder.RawFieldNames(&UserLessonRecord{})
	userLessonRecordRows                = strings.Join(userLessonRecordFieldNames, ",")
	userLessonRecordRowsExpectAutoSet   = strings.Join(stringx.Remove(userLessonRecordFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userLessonRecordRowsWithPlaceHolder = strings.Join(stringx.Remove(userLessonRecordFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	userLessonRecordModel interface {
		Insert(ctx context.Context, data *UserLessonRecord) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*UserLessonRecord, error)
		Update(ctx context.Context, data *UserLessonRecord) error
		Delete(ctx context.Context, id int64) error
	}

	defaultUserLessonRecordModel struct {
		conn  sqlx.SqlConn
		table string
	}

	UserLessonRecord struct {
		Id               int64     `db:"id"`                 // 主键
		UserId           int64     `db:"user_id"`            // 用户ID
		UserScheduleId   int64     `db:"user_schedule_id"`   // 用户规划ID
		ScheduleDetailId int64     `db:"schedule_detail_id"` // 规划详情ID
		BizType          int64     `db:"biz_type"`           // 业务类型  1 阅读理解
		LessonType       int64     `db:"lesson_type"`        // 规划业务类型，1.课节 2.月考
		LessonId         int64     `db:"lesson_id"`          // 课程ID
		Status           int64     `db:"status"`             // 状态 1.进行中 2.结束 3.中断 4.跳过
		TotalNum         int64     `db:"total_num"`          // 总题数
		RightNum         int64     `db:"right_num"`          // 正确题目数
		CreatedAt        time.Time `db:"created_at"`         // 添加时间
		UpdatedAt        time.Time `db:"updated_at"`         // 修改时间
	}
)

func newUserLessonRecordModel(conn sqlx.SqlConn) *defaultUserLessonRecordModel {
	return &defaultUserLessonRecordModel{
		conn:  conn,
		table: "`ls_user_lesson_record`",
	}
}

func (m *defaultUserLessonRecordModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUserLessonRecordModel) FindOne(ctx context.Context, id int64) (*UserLessonRecord, error) {

	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userLessonRecordRows, m.table)

	var resp UserLessonRecord
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserLessonRecordModel) Insert(ctx context.Context, data *UserLessonRecord) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, userLessonRecordRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.UserScheduleId, data.ScheduleDetailId, data.BizType, data.LessonType, data.LessonId, data.Status, data.TotalNum, data.RightNum)
	return ret, err
}

func (m *defaultUserLessonRecordModel) Update(ctx context.Context, data *UserLessonRecord) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userLessonRecordRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserId, data.UserScheduleId, data.ScheduleDetailId, data.BizType, data.LessonType, data.LessonId, data.Status, data.TotalNum, data.RightNum, data.Id)
	return err
}

func (m *defaultUserLessonRecordModel) TableName() string {
	return m.table
}
