// Code generated by goctl. DO NOT EDIT.

package teacher

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	teacherFieldNames          = builder.RawFieldNames(&Teacher{})
	teacherRows                = strings.Join(teacherFieldNames, ",")
	teacherRowsExpectAutoSet   = strings.Join(stringx.Remove(teacherFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	teacherRowsWithPlaceHolder = strings.Join(stringx.Remove(teacherFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	teacherModel interface {
		Insert(ctx context.Context, data *Teacher) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Teacher, error)
		Update(ctx context.Context, data *Teacher) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTeacherModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Teacher struct {
		Id        int64     `db:"id"`
		AccountId int64     `db:"account_id"` // 教师账户ID
		Name      string    `db:"name"`       // 教师姓名
		Nickname  string    `db:"nickname"`   // 教师昵称
		Phone     string    `db:"phone"`      // 教师手机号
		Email     string    `db:"email"`      // 教师邮箱
		Avatar    string    `db:"avatar"`     // 教师头像
		Introduce string    `db:"introduce"`  // 老师简介
		Style     string    `db:"style"`      // 教学风格
		Role      int64     `db:"role"`       // 角色 0.未选择角色 1.主讲 2.班主任 3.导播
		CreatedAt time.Time `db:"created_at"` // 添加时间
		UpdatedAt time.Time `db:"updated_at"` // 修改时间
	}
)

func newTeacherModel(conn sqlx.SqlConn) *defaultTeacherModel {
	return &defaultTeacherModel{
		conn:  conn,
		table: "`ds_teacher`",
	}
}

func (m *defaultTeacherModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultTeacherModel) FindOne(ctx context.Context, id int64) (*Teacher, error) {

	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", teacherRows, m.table)

	var resp Teacher
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTeacherModel) Insert(ctx context.Context, data *Teacher) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, teacherRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.AccountId, data.Name, data.Nickname, data.Phone, data.Email, data.Avatar, data.Introduce, data.Style, data.Role)
	return ret, err
}

func (m *defaultTeacherModel) Update(ctx context.Context, data *Teacher) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, teacherRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.AccountId, data.Name, data.Nickname, data.Phone, data.Email, data.Avatar, data.Introduce, data.Style, data.Role, data.Id)
	return err
}

func (m *defaultTeacherModel) TableName() string {
	return m.table
}
