// Code generated by goctl. DO NOT EDIT.

package user

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	baseUserFieldNames          = builder.RawFieldNames(&BaseUser{})
	baseUserRows                = strings.Join(baseUserFieldNames, ",")
	baseUserRowsExpectAutoSet   = strings.Join(stringx.Remove(baseUserFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	baseUserRowsWithPlaceHolder = strings.Join(stringx.Remove(baseUserFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	baseUserModel interface {
		Insert(ctx context.Context, data *BaseUser) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*BaseUser, error)
		FindOneByMaskPhoneProduct(ctx context.Context, maskPhone string, product int64) (*BaseUser, error)
		Update(ctx context.Context, data *BaseUser) error
		Delete(ctx context.Context, id int64) error
	}

	defaultBaseUserModel struct {
		conn  sqlx.SqlConn
		table string
	}

	BaseUser struct {
		Id        int64     `db:"id"`
		UserNo    string    `db:"user_no"`    // 用户编号[只做展示用途]
		MaskPhone string    `db:"mask_phone"` // 加密手机号
		Phone     string    `db:"phone"`      // 脱敏手机号
		Product   int64     `db:"product"`    // 所属产品 0.辞源
		Source    int64     `db:"source"`     // 首次来源 100.提审标记 0.APP 1.豆伴匠 2.风的颜色 1001.听力熊 1002.微软
		Status    int64     `db:"status"`     // 状态 0.正常 1.冻结 2.注销
		Remark    string    `db:"remark"`     // 备注
		CreatedAt time.Time `db:"created_at"` // 添加时间
		UpdatedAt time.Time `db:"updated_at"` // 修改时间
	}
)

func newBaseUserModel(conn sqlx.SqlConn) *defaultBaseUserModel {
	return &defaultBaseUserModel{
		conn:  conn,
		table: "`us_base_user`",
	}
}

func (m *defaultBaseUserModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultBaseUserModel) FindOne(ctx context.Context, id int64) (*BaseUser, error) {

	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", baseUserRows, m.table)

	var resp BaseUser
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultBaseUserModel) FindOneByMaskPhoneProduct(ctx context.Context, maskPhone string, product int64) (*BaseUser, error) {
	var resp BaseUser

	query := fmt.Sprintf("select %s from %s where `mask_phone` = ? and `product` = ? limit 1", baseUserRows, m.table)

	err := m.conn.QueryRowCtx(ctx, &resp, query, maskPhone, product)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultBaseUserModel) Insert(ctx context.Context, data *BaseUser) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, baseUserRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserNo, data.MaskPhone, data.Phone, data.Product, data.Source, data.Status, data.Remark)
	return ret, err
}

func (m *defaultBaseUserModel) Update(ctx context.Context, newData *BaseUser) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, baseUserRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.UserNo, newData.MaskPhone, newData.Phone, newData.Product, newData.Source, newData.Status, newData.Remark, newData.Id)
	return err
}

func (m *defaultBaseUserModel) TableName() string {
	return m.table
}
