// Code generated by goctl. DO NOT EDIT.

package user

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	smsRecordFieldNames          = builder.RawFieldNames(&SmsRecord{})
	smsRecordRows                = strings.Join(smsRecordFieldNames, ",")
	smsRecordRowsExpectAutoSet   = strings.Join(stringx.Remove(smsRecordFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	smsRecordRowsWithPlaceHolder = strings.Join(stringx.Remove(smsRecordFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	smsRecordModel interface {
		Insert(ctx context.Context, data *SmsRecord) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*SmsRecord, error)
		FindOneByPhone(ctx context.Context, phone string) (*SmsRecord, error)
		Update(ctx context.Context, data *SmsRecord) error
		Delete(ctx context.Context, id int64) error
	}

	defaultSmsRecordModel struct {
		conn  sqlx.SqlConn
		table string
	}

	SmsRecord struct {
		Id        int64     `db:"id"`
		Phone     string    `db:"phone"`      // 加密手机号
		Code      string    `db:"code"`       // 调用sdk后的状态码
		Message   string    `db:"message"`    // 状态码说明
		Channel   int64     `db:"channel"`    // 渠道 1.腾讯云 2.阿里云
		Template  string    `db:"template"`   // 短信模版id
		Status    int64     `db:"status"`     // 状态 1.成功 2.失败
		CreatedAt time.Time `db:"created_at"` // 添加时间
	}
)

func newSmsRecordModel(conn sqlx.SqlConn) *defaultSmsRecordModel {
	return &defaultSmsRecordModel{
		conn:  conn,
		table: "`sys_sms_record`",
	}
}

func (m *defaultSmsRecordModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultSmsRecordModel) FindOne(ctx context.Context, id int64) (*SmsRecord, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", smsRecordRows, m.table)
	var resp SmsRecord
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSmsRecordModel) FindOneByPhone(ctx context.Context, phone string) (*SmsRecord, error) {
	var resp SmsRecord
	query := fmt.Sprintf("select %s from %s where `phone` = ? limit 1", smsRecordRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, phone)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSmsRecordModel) Insert(ctx context.Context, data *SmsRecord) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, smsRecordRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Phone, data.Code, data.Message, data.Channel, data.Template, data.Status)
	return ret, err
}

func (m *defaultSmsRecordModel) Update(ctx context.Context, newData *SmsRecord) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, smsRecordRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Phone, newData.Code, newData.Message, newData.Channel, newData.Template, newData.Status, newData.Id)
	return err
}

func (m *defaultSmsRecordModel) TableName() string {
	return m.table
}
