// Code generated by goctl. DO NOT EDIT.

package user

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userFieldNames          = builder.RawFieldNames(&User{})
	userRows                = strings.Join(userFieldNames, ",")
	userRowsExpectAutoSet   = strings.Join(stringx.Remove(userFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userRowsWithPlaceHolder = strings.Join(stringx.Remove(userFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	userModel interface {
		Insert(ctx context.Context, data *User) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*User, error)
		Update(ctx context.Context, data *User) error
		Delete(ctx context.Context, id int64) error
	}

	defaultUserModel struct {
		conn  sqlx.SqlConn
		table string
	}

	User struct {
		Id             int64        `db:"id"`
		BaseUserId     int64        `db:"base_user_id"`     // 主用户ID
		IsDefault      int64        `db:"is_default"`       // 是否为默认账户 1.默认 2.非默认
		RoleType       int64        `db:"role_type"`        // 角色类型 1.孩子[默认] 2.家长
		Nickname       string       `db:"nickname"`         // 用户昵称
		RealName       string       `db:"real_name"`        // 真实姓名
		Avatar         string       `db:"avatar"`           // 用户头像
		Gender         int64        `db:"gender"`           // 性别 0.未知 1.男 2.女
		Grade          int64        `db:"grade"`            // 年级 10.学龄前 11.一年级 12.二年级 13.三年级 14.四年级 15.五年级 16.六年级 20.中小衔接 21.初一 22.初二 23.初三 31.高一 32.高二 33.高三 41.大学语文 42.中文专业 43.文学专家
		Birthday       sql.NullTime `db:"birthday"`         // 生日[年月日]
		ProvinceId     int64        `db:"province_id"`      // 省ID
		ProvinceName   string       `db:"province_name"`    // 省名称
		CityId         int64        `db:"city_id"`          // 市ID
		CityName       string       `db:"city_name"`        // 市名称
		AreaId         int64        `db:"area_id"`          // 区ID
		AreaName       string       `db:"area_name"`        // 区名称
		IsInfoFinished int64        `db:"is_info_finished"` // 是否完善信息 1.未完善 2.已完善
		DeviceId       string       `db:"device_id"`        // 最近一次登录设备号
		Status         int64        `db:"status"`           // 用户状态 1.正常 2.删除
		Remark         string       `db:"remark"`           // 备注
		CreatedAt      time.Time    `db:"created_at"`       // 添加时间
		UpdatedAt      time.Time    `db:"updated_at"`       // 修改时间
	}
)

func newUserModel(conn sqlx.SqlConn) *defaultUserModel {
	return &defaultUserModel{
		conn:  conn,
		table: "`us_user`",
	}
}

func (m *defaultUserModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUserModel) FindOne(ctx context.Context, id int64) (*User, error) {

	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userRows, m.table)

	var resp User
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserModel) Insert(ctx context.Context, data *User) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, userRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.BaseUserId, data.IsDefault, data.RoleType, data.Nickname, data.RealName, data.Avatar, data.Gender, data.Grade, data.Birthday, data.ProvinceId, data.ProvinceName, data.CityId, data.CityName, data.AreaId, data.AreaName, data.IsInfoFinished, data.DeviceId, data.Status, data.Remark)
	return ret, err
}

func (m *defaultUserModel) Update(ctx context.Context, data *User) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.BaseUserId, data.IsDefault, data.RoleType, data.Nickname, data.RealName, data.Avatar, data.Gender, data.Grade, data.Birthday, data.ProvinceId, data.ProvinceName, data.CityId, data.CityName, data.AreaId, data.AreaName, data.IsInfoFinished, data.DeviceId, data.Status, data.Remark, data.Id)
	return err
}

func (m *defaultUserModel) TableName() string {
	return m.table
}
