// Code generated by goctl. DO NOT EDIT.

package user

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userAuthFieldNames          = builder.RawFieldNames(&UserAuth{})
	userAuthRows                = strings.Join(userAuthFieldNames, ",")
	userAuthRowsExpectAutoSet   = strings.Join(stringx.Remove(userAuthFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userAuthRowsWithPlaceHolder = strings.Join(stringx.Remove(userAuthFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	userAuthModel interface {
		Insert(ctx context.Context, data *UserAuth) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*UserAuth, error)
		FindOneByIdentifierIdentityType(ctx context.Context, identifier string, identityType int64) (*UserAuth, error)
		Update(ctx context.Context, data *UserAuth) error
		Delete(ctx context.Context, id int64) error
	}

	defaultUserAuthModel struct {
		conn  sqlx.SqlConn
		table string
	}

	UserAuth struct {
		Id           int64     `db:"id"`
		BaseUserId   int64     `db:"base_user_id"`  // 用户ID
		IdentityType int64     `db:"identity_type"` // 授权类型 1.手机号 2.微信授权 3.一键登录 4.设备标识
		Identifier   string    `db:"identifier"`    // 登录账号 例：手机号、邮箱、用户名或第三方应用的唯一标识
		Certificate  string    `db:"certificate"`   // 密码凭证 例：站内的密码，站外的token
		Status       int64     `db:"status"`        // 状态 0.正常 1.冻结 2.注销
		CreatedAt    time.Time `db:"created_at"`    // 添加时间
		UpdatedAt    time.Time `db:"updated_at"`    // 修改时间
	}
)

func newUserAuthModel(conn sqlx.SqlConn) *defaultUserAuthModel {
	return &defaultUserAuthModel{
		conn:  conn,
		table: "`us_user_auth`",
	}
}

func (m *defaultUserAuthModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUserAuthModel) FindOne(ctx context.Context, id int64) (*UserAuth, error) {

	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userAuthRows, m.table)

	var resp UserAuth
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserAuthModel) FindOneByIdentifierIdentityType(ctx context.Context, identifier string, identityType int64) (*UserAuth, error) {
	var resp UserAuth

	query := fmt.Sprintf("select %s from %s where `identifier` = ? and `identity_type` = ? limit 1", userAuthRows, m.table)

	err := m.conn.QueryRowCtx(ctx, &resp, query, identifier, identityType)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserAuthModel) Insert(ctx context.Context, data *UserAuth) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, userAuthRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.BaseUserId, data.IdentityType, data.Identifier, data.Certificate, data.Status)
	return ret, err
}

func (m *defaultUserAuthModel) Update(ctx context.Context, newData *UserAuth) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userAuthRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.BaseUserId, newData.IdentityType, newData.Identifier, newData.Certificate, newData.Status, newData.Id)
	return err
}

func (m *defaultUserAuthModel) TableName() string {
	return m.table
}
