// Code generated by goctl. DO NOT EDIT.

package user

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userLoginLogFieldNames          = builder.RawFieldNames(&UserLoginLog{})
	userLoginLogRows                = strings.Join(userLoginLogFieldNames, ",")
	userLoginLogRowsExpectAutoSet   = strings.Join(stringx.Remove(userLoginLogFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userLoginLogRowsWithPlaceHolder = strings.Join(stringx.Remove(userLoginLogFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	userLoginLogModel interface {
		Insert(ctx context.Context, data *UserLoginLog) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*UserLoginLog, error)
		Update(ctx context.Context, data *UserLoginLog) error
		Delete(ctx context.Context, id int64) error
	}

	defaultUserLoginLogModel struct {
		conn  sqlx.SqlConn
		table string
	}

	UserLoginLog struct {
		Id            int64     `db:"id"`
		BaseUserId    int64     `db:"base_user_id"`   // 主用户ID
		UserId        int64     `db:"user_id"`        // 子用户ID
		Product       int64     `db:"product"`        // 所属产品 0.辞源
		IdentityType  int64     `db:"identity_type"`  // 授权类型 1.手机号 2.微信 3.一键登录 4.设备标识
		Command       int64     `db:"command"`        // 操作类型 1.注册成功 2.注册失败 3.登录成功 4.登录失败 5.登出成功 6.登出失败
		Client        string    `db:"client"`         // 客户端
		ClientVersion string    `db:"client_version"` // 客户端版本号
		DeviceId      string    `db:"device_id"`      // 登录时设备号
		LastIp        string    `db:"last_ip"`        // 登录ip
		Os            string    `db:"os"`             // 手机系统
		OsVersion     string    `db:"os_version"`     // 手机系统版本
		CreatedAt     time.Time `db:"created_at"`     // 添加时间
	}
)

func newUserLoginLogModel(conn sqlx.SqlConn) *defaultUserLoginLogModel {
	return &defaultUserLoginLogModel{
		conn:  conn,
		table: "`us_user_login_log`",
	}
}

func (m *defaultUserLoginLogModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUserLoginLogModel) FindOne(ctx context.Context, id int64) (*UserLoginLog, error) {

	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userLoginLogRows, m.table)

	var resp UserLoginLog
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserLoginLogModel) Insert(ctx context.Context, data *UserLoginLog) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, userLoginLogRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.BaseUserId, data.UserId, data.Product, data.IdentityType, data.Command, data.Client, data.ClientVersion, data.DeviceId, data.LastIp, data.Os, data.OsVersion)
	return ret, err
}

func (m *defaultUserLoginLogModel) Update(ctx context.Context, data *UserLoginLog) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userLoginLogRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.BaseUserId, data.UserId, data.Product, data.IdentityType, data.Command, data.Client, data.ClientVersion, data.DeviceId, data.LastIp, data.Os, data.OsVersion, data.Id)
	return err
}

func (m *defaultUserLoginLogModel) TableName() string {
	return m.table
}
