// Code generated by goctl. DO NOT EDIT.

package user

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	whiteListFieldNames          = builder.RawFieldNames(&WhiteList{})
	whiteListRows                = strings.Join(whiteListFieldNames, ",")
	whiteListRowsExpectAutoSet   = strings.Join(stringx.Remove(whiteListFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	whiteListRowsWithPlaceHolder = strings.Join(stringx.Remove(whiteListFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	whiteListModel interface {
		Insert(ctx context.Context, data *WhiteList) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*WhiteList, error)
		FindOneByProductSourcePhone(ctx context.Context, product int64, source int64, phone string) (*WhiteList, error)
		Update(ctx context.Context, data *WhiteList) error
		Delete(ctx context.Context, id int64) error
	}

	defaultWhiteListModel struct {
		conn  sqlx.SqlConn
		table string
	}

	WhiteList struct {
		Id        int64     `db:"id"`
		Phone     string    `db:"phone"`      // 白名单手机号
		StartTime time.Time `db:"start_time"` // 有效期起始时间
		EndTime   time.Time `db:"end_time"`   // 有效期起始时间
		Product   int64     `db:"product"`    // 产品线
		Source    int64     `db:"source"`     // 来源
		Status    int64     `db:"status"`     // 状态 1.正常 2.失效
		Remark    string    `db:"remark"`     // 备注
		CreatedAt time.Time `db:"created_at"` // 添加时间
		UpdatedAt time.Time `db:"updated_at"` // 修改时间
	}
)

func newWhiteListModel(conn sqlx.SqlConn) *defaultWhiteListModel {
	return &defaultWhiteListModel{
		conn:  conn,
		table: "`us_white_list`",
	}
}

func (m *defaultWhiteListModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultWhiteListModel) FindOne(ctx context.Context, id int64) (*WhiteList, error) {

	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", whiteListRows, m.table)

	var resp WhiteList
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultWhiteListModel) FindOneByProductSourcePhone(ctx context.Context, product int64, source int64, phone string) (*WhiteList, error) {
	var resp WhiteList

	query := fmt.Sprintf("select %s from %s where `product` = ? and `source` = ? and `phone` = ? limit 1", whiteListRows, m.table)

	err := m.conn.QueryRowCtx(ctx, &resp, query, product, source, phone)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultWhiteListModel) Insert(ctx context.Context, data *WhiteList) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, whiteListRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Phone, data.StartTime, data.EndTime, data.Product, data.Source, data.Status, data.Remark)
	return ret, err
}

func (m *defaultWhiteListModel) Update(ctx context.Context, newData *WhiteList) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, whiteListRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Phone, newData.StartTime, newData.EndTime, newData.Product, newData.Source, newData.Status, newData.Remark, newData.Id)
	return err
}

func (m *defaultWhiteListModel) TableName() string {
	return m.table
}
