// Code generated by goctl. DO NOT EDIT.

package hub

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	lessonSnapshotFieldNames          = builder.RawFieldNames(&LessonSnapshot{})
	lessonSnapshotRows                = strings.Join(lessonSnapshotFieldNames, ",")
	lessonSnapshotRowsExpectAutoSet   = strings.Join(stringx.Remove(lessonSnapshotFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	lessonSnapshotRowsWithPlaceHolder = strings.Join(stringx.Remove(lessonSnapshotFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	lessonSnapshotModel interface {
		Insert(ctx context.Context, data *LessonSnapshot) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*LessonSnapshot, error)
		Update(ctx context.Context, data *LessonSnapshot) error
		Delete(ctx context.Context, id int64) error
	}

	defaultLessonSnapshotModel struct {
		conn  sqlx.SqlConn
		table string
	}

	LessonSnapshot struct {
		Id            int64     `db:"id"`
		LessonNo      int64     `db:"lesson_no"`      // 课节来源编号
		NodeType      int64     `db:"node_type"`      // 节点类型 1.小灶课 2.小语文 3.大语文
		Name          string    `db:"name"`           // 课程名称
		PointName     string    `db:"point_name"`     // 知识点名称
		Status        int64     `db:"status"`         // 审核状态 1.初始录入 2.审核中 3.审核通过 4.审核未通过 5.下架
		Grade         int64     `db:"grade"`          // 年级 10.学龄前 11.一年级 12.二年级 13.三年级 14.四年级 15.五年级 16.六年级 20.中小衔接 21.初一 22.初二 23.初三 31.高一 32.高二 33.高三 41.大学语文 42.中文专业 43.文学专家
		Version       int64     `db:"version"`        // 版本号
		OperateStatus int64     `db:"operate_status"` // 操作状态 0.未推送 1.已推送 2.已下架
		OperateId     int64     `db:"operate_id"`     // 操作人ID
		Data          string    `db:"data"`           // 原始数据
		AppVersion    string    `db:"app_version"`    // APP版本
		CreatedAt     time.Time `db:"created_at"`
		UpdatedAt     time.Time `db:"updated_at"`
	}
)

func newLessonSnapshotModel(conn sqlx.SqlConn) *defaultLessonSnapshotModel {
	return &defaultLessonSnapshotModel{
		conn:  conn,
		table: "`bk_lesson_snapshot`",
	}
}

func (m *defaultLessonSnapshotModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultLessonSnapshotModel) FindOne(ctx context.Context, id int64) (*LessonSnapshot, error) {

	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", lessonSnapshotRows, m.table)

	var resp LessonSnapshot
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultLessonSnapshotModel) Insert(ctx context.Context, data *LessonSnapshot) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, lessonSnapshotRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.LessonNo, data.NodeType, data.Name, data.PointName, data.Status, data.Grade, data.Version, data.OperateStatus, data.OperateId, data.Data, data.AppVersion)
	return ret, err
}

func (m *defaultLessonSnapshotModel) Update(ctx context.Context, data *LessonSnapshot) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, lessonSnapshotRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.LessonNo, data.NodeType, data.Name, data.PointName, data.Status, data.Grade, data.Version, data.OperateStatus, data.OperateId, data.Data, data.AppVersion, data.Id)
	return err
}

func (m *defaultLessonSnapshotModel) TableName() string {
	return m.table
}
