// Code generated by goctl. DO NOT EDIT.

package hub

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	liveSnapshotFieldNames          = builder.RawFieldNames(&LiveSnapshot{})
	liveSnapshotRows                = strings.Join(liveSnapshotFieldNames, ",")
	liveSnapshotRowsExpectAutoSet   = strings.Join(stringx.Remove(liveSnapshotFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	liveSnapshotRowsWithPlaceHolder = strings.Join(stringx.Remove(liveSnapshotFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	liveSnapshotModel interface {
		Insert(ctx context.Context, data *LiveSnapshot) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*LiveSnapshot, error)
		Update(ctx context.Context, data *LiveSnapshot) error
		Delete(ctx context.Context, id int64) error
	}

	defaultLiveSnapshotModel struct {
		conn  sqlx.SqlConn
		table string
	}

	LiveSnapshot struct {
		Id            int64     `db:"id"`
		LessonNo      string    `db:"lesson_no"`      // 来源编号
		VersionNo     string    `db:"version_no"`     // 版本号编号
		Name          string    `db:"name"`           // 课程名称
		Status        int64     `db:"status"`         // 审核状态 1.初始录入 2.审核中 3.审核通过 4.审核未通过 5.下架
		Version       int64     `db:"version"`        // 版本号
		OperateStatus int64     `db:"operate_status"` // 操作状态 0.未推送 1.已推送 2.已下架
		OperateId     int64     `db:"operate_id"`     // 操作人ID
		Data          string    `db:"data"`           // 原始数据
		AppVersion    string    `db:"app_version"`    // APP版本
		Remark        string    `db:"remark"`         // 备注
		CreatedAt     time.Time `db:"created_at"`
		UpdatedAt     time.Time `db:"updated_at"`
	}
)

func newLiveSnapshotModel(conn sqlx.SqlConn) *defaultLiveSnapshotModel {
	return &defaultLiveSnapshotModel{
		conn:  conn,
		table: "`bk_live_snapshot`",
	}
}

func (m *defaultLiveSnapshotModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultLiveSnapshotModel) FindOne(ctx context.Context, id int64) (*LiveSnapshot, error) {

	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", liveSnapshotRows, m.table)

	var resp LiveSnapshot
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultLiveSnapshotModel) Insert(ctx context.Context, data *LiveSnapshot) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, liveSnapshotRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.LessonNo, data.VersionNo, data.Name, data.Status, data.Version, data.OperateStatus, data.OperateId, data.Data, data.AppVersion, data.Remark)
	return ret, err
}

func (m *defaultLiveSnapshotModel) Update(ctx context.Context, data *LiveSnapshot) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, liveSnapshotRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.LessonNo, data.VersionNo, data.Name, data.Status, data.Version, data.OperateStatus, data.OperateId, data.Data, data.AppVersion, data.Remark, data.Id)
	return err
}

func (m *defaultLiveSnapshotModel) TableName() string {
	return m.table
}
