// Code generated by goctl. DO NOT EDIT.

package hub

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	superTrainSnapshotFieldNames          = builder.RawFieldNames(&SuperTrainSnapshot{})
	superTrainSnapshotRows                = strings.Join(superTrainSnapshotFieldNames, ",")
	superTrainSnapshotRowsExpectAutoSet   = strings.Join(stringx.Remove(superTrainSnapshotFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	superTrainSnapshotRowsWithPlaceHolder = strings.Join(stringx.Remove(superTrainSnapshotFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	superTrainSnapshotModel interface {
		Insert(ctx context.Context, data *SuperTrainSnapshot) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*SuperTrainSnapshot, error)
		Update(ctx context.Context, data *SuperTrainSnapshot) error
		Delete(ctx context.Context, id int64) error
	}

	defaultSuperTrainSnapshotModel struct {
		conn  sqlx.SqlConn
		table string
	}

	SuperTrainSnapshot struct {
		Id            int64     `db:"id"`
		No            string    `db:"no"`             // 编号
		Name          string    `db:"name"`           // 课程名称
		Status        int64     `db:"status"`         // 审核状态 1.初始录入 2.审核中 3.审核通过 4.审核未通过 5.下架
		Version       int64     `db:"version"`        // 版本号
		OperateStatus int64     `db:"operate_status"` // 操作状态 0.未推送 1.已推送 2.已下架
		OperateId     int64     `db:"operate_id"`     // 操作人ID
		Data          string    `db:"data"`           // 原始数据
		AppVersion    string    `db:"app_version"`    // APP版本
		Remark        string    `db:"remark"`         // 备注
		CreatedAt     time.Time `db:"created_at"`
		UpdatedAt     time.Time `db:"updated_at"`
	}
)

func newSuperTrainSnapshotModel(conn sqlx.SqlConn) *defaultSuperTrainSnapshotModel {
	return &defaultSuperTrainSnapshotModel{
		conn:  conn,
		table: "`bk_super_train_snapshot`",
	}
}

func (m *defaultSuperTrainSnapshotModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultSuperTrainSnapshotModel) FindOne(ctx context.Context, id int64) (*SuperTrainSnapshot, error) {

	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", superTrainSnapshotRows, m.table)

	var resp SuperTrainSnapshot
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSuperTrainSnapshotModel) Insert(ctx context.Context, data *SuperTrainSnapshot) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, superTrainSnapshotRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.No, data.Name, data.Status, data.Version, data.OperateStatus, data.OperateId, data.Data, data.AppVersion, data.Remark)
	return ret, err
}

func (m *defaultSuperTrainSnapshotModel) Update(ctx context.Context, data *SuperTrainSnapshot) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, superTrainSnapshotRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.No, data.Name, data.Status, data.Version, data.OperateStatus, data.OperateId, data.Data, data.AppVersion, data.Remark, data.Id)
	return err
}

func (m *defaultSuperTrainSnapshotModel) TableName() string {
	return m.table
}
