// Code generated by goctl. DO NOT EDIT.

package hub

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	writePptSnapshotFieldNames          = builder.RawFieldNames(&WritePptSnapshot{})
	writePptSnapshotRows                = strings.Join(writePptSnapshotFieldNames, ",")
	writePptSnapshotRowsExpectAutoSet   = strings.Join(stringx.Remove(writePptSnapshotFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	writePptSnapshotRowsWithPlaceHolder = strings.Join(stringx.Remove(writePptSnapshotFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	writePptSnapshotModel interface {
		Insert(ctx context.Context, data *WritePptSnapshot) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*WritePptSnapshot, error)
		Update(ctx context.Context, data *WritePptSnapshot) error
		Delete(ctx context.Context, id int64) error
	}

	defaultWritePptSnapshotModel struct {
		conn  sqlx.SqlConn
		table string
	}

	WritePptSnapshot struct {
		Id             int64     `db:"id"`
		LessonNo       int64     `db:"lesson_no"`       // 来源编号
		Unit           int64     `db:"unit"`            // 单元
		Title          string    `db:"title"`           // 标题
		Status         int64     `db:"status"`          // 审核状态 1.初始录入 2.审核中 3.审核通过 4.审核未通过 5.下架
		LessonType     int64     `db:"lesson_type"`     // 课节类型 1.技巧 2.赏析
		LessonCategory int64     `db:"lesson_category"` // 课节类型 1.技巧 2.赏析
		Version        int64     `db:"version"`         // 版本号
		OperateStatus  int64     `db:"operate_status"`  // 操作状态 0.未推送 1.已推送 2.已下架
		OperateId      int64     `db:"operate_id"`      // 操作人ID
		Data           string    `db:"data"`            // 原始数据
		AppVersion     string    `db:"app_version"`     // APP版本
		Remark         string    `db:"remark"`          // 备注
		CreatedAt      time.Time `db:"created_at"`
		UpdatedAt      time.Time `db:"updated_at"`
	}
)

func newWritePptSnapshotModel(conn sqlx.SqlConn) *defaultWritePptSnapshotModel {
	return &defaultWritePptSnapshotModel{
		conn:  conn,
		table: "`bk_write_ppt_snapshot`",
	}
}

func (m *defaultWritePptSnapshotModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultWritePptSnapshotModel) FindOne(ctx context.Context, id int64) (*WritePptSnapshot, error) {

	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", writePptSnapshotRows, m.table)

	var resp WritePptSnapshot
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultWritePptSnapshotModel) Insert(ctx context.Context, data *WritePptSnapshot) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, writePptSnapshotRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.LessonNo, data.Unit, data.Title, data.Status, data.LessonType, data.LessonCategory, data.Version, data.OperateStatus, data.OperateId, data.Data, data.AppVersion, data.Remark)
	return ret, err
}

func (m *defaultWritePptSnapshotModel) Update(ctx context.Context, data *WritePptSnapshot) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, writePptSnapshotRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.LessonNo, data.Unit, data.Title, data.Status, data.LessonType, data.LessonCategory, data.Version, data.OperateStatus, data.OperateId, data.Data, data.AppVersion, data.Remark, data.Id)
	return err
}

func (m *defaultWritePptSnapshotModel) TableName() string {
	return m.table
}
