// Code generated by goctl. DO NOT EDIT.

package supervisor

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	interactionFieldNames          = builder.RawFieldNames(&Interaction{})
	interactionRows                = strings.Join(interactionFieldNames, ",")
	interactionRowsExpectAutoSet   = strings.Join(stringx.Remove(interactionFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	interactionRowsWithPlaceHolder = strings.Join(stringx.Remove(interactionFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	interactionModel interface {
		Insert(ctx context.Context, data *Interaction) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Interaction, error)
		Update(ctx context.Context, data *Interaction) error
		Delete(ctx context.Context, id int64) error
	}

	defaultInteractionModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Interaction struct {
		Id           int64          `db:"id"`            // 主键
		Name         string         `db:"name"`          // 互动名字
		Description  string         `db:"description"`   // 描述
		TeachingData sql.NullString `db:"teaching_data"` // 教师ppt
		Data         sql.NullString `db:"data"`          // 互动内容
		CreatedAt    time.Time      `db:"created_at"`    // 创建时间
		UpdatedAt    time.Time      `db:"updated_at"`    // 更新时间
	}
)

func newInteractionModel(conn sqlx.SqlConn) *defaultInteractionModel {
	return &defaultInteractionModel{
		conn:  conn,
		table: "`supv_interaction`",
	}
}

func (m *defaultInteractionModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultInteractionModel) FindOne(ctx context.Context, id int64) (*Interaction, error) {

	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", interactionRows, m.table)

	var resp Interaction
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultInteractionModel) Insert(ctx context.Context, data *Interaction) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, interactionRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Name, data.Description, data.TeachingData, data.Data)
	return ret, err
}

func (m *defaultInteractionModel) Update(ctx context.Context, data *Interaction) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, interactionRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Name, data.Description, data.TeachingData, data.Data, data.Id)
	return err
}

func (m *defaultInteractionModel) TableName() string {
	return m.table
}
