// Code generated by goctl. DO NOT EDIT.

package supervisor

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	scheduleFieldNames          = builder.RawFieldNames(&Schedule{})
	scheduleRows                = strings.Join(scheduleFieldNames, ",")
	scheduleRowsExpectAutoSet   = strings.Join(stringx.Remove(scheduleFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	scheduleRowsWithPlaceHolder = strings.Join(stringx.Remove(scheduleFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	scheduleModel interface {
		Insert(ctx context.Context, data *Schedule) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Schedule, error)
		Update(ctx context.Context, data *Schedule) error
		Delete(ctx context.Context, id int64) error
	}

	defaultScheduleModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Schedule struct {
		Id               int64     `db:"id"`                // 主键
		TeacherId        int64     `db:"teacher_id"`        // 讲师ID
		TeacherName      string    `db:"teacher_name"`      // 讲师名称
		CourseId         int64     `db:"course_id"`         // 课程ID
		CourseType       int64     `db:"course_type"`       // 类型 1-超级作文 2-超练阅读
		Name             string    `db:"name"`              // 督学课名称
		StreamId         int64     `db:"stream_id"`         // 直播ID
		EffectiveStart   time.Time `db:"effective_start"`   // 活动生效时间
		EffectiveEnd     time.Time `db:"effective_end"`     // 活动结束时间
		AppointmentStart time.Time `db:"appointment_start"` // 预约开始时间
		AppointmentEnd   time.Time `db:"appointment_end"`   // 预约结束时间
		StartTime        time.Time `db:"start_time"`        // 开课时间
		MaxStock         int64     `db:"max_stock"`         // 预约人数上限
		SurplusStock     int64     `db:"surplus_stock"`     // 剩余预约人数
		ScheduleType     int64     `db:"schedule_type"`     // 排课类型 1直播 2录播
		Status           int64     `db:"status"`            // 排课状态 1待开放 2开放 3进行中 4结束
		BgUrl            string    `db:"bg_url"`            // 伴学、督学课程背景图片
		Content          string    `db:"content"`           // 伴学、督学课程文案
		CreatedAt        time.Time `db:"created_at"`        // 创建时间
		UpdatedAt        time.Time `db:"updated_at"`        // 更新时间
	}
)

func newScheduleModel(conn sqlx.SqlConn) *defaultScheduleModel {
	return &defaultScheduleModel{
		conn:  conn,
		table: "`supv_schedule`",
	}
}

func (m *defaultScheduleModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultScheduleModel) FindOne(ctx context.Context, id int64) (*Schedule, error) {

	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", scheduleRows, m.table)

	var resp Schedule
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultScheduleModel) Insert(ctx context.Context, data *Schedule) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, scheduleRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.TeacherId, data.TeacherName, data.CourseId, data.CourseType, data.Name, data.StreamId, data.EffectiveStart, data.EffectiveEnd, data.AppointmentStart, data.AppointmentEnd, data.StartTime, data.MaxStock, data.SurplusStock, data.ScheduleType, data.Status, data.BgUrl, data.Content)
	return ret, err
}

func (m *defaultScheduleModel) Update(ctx context.Context, data *Schedule) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, scheduleRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.TeacherId, data.TeacherName, data.CourseId, data.CourseType, data.Name, data.StreamId, data.EffectiveStart, data.EffectiveEnd, data.AppointmentStart, data.AppointmentEnd, data.StartTime, data.MaxStock, data.SurplusStock, data.ScheduleType, data.Status, data.BgUrl, data.Content, data.Id)
	return err
}

func (m *defaultScheduleModel) TableName() string {
	return m.table
}
