// Code generated by goctl. DO NOT EDIT.

package supervisor

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	scheduleInteractionLinkFieldNames          = builder.RawFieldNames(&ScheduleInteractionLink{})
	scheduleInteractionLinkRows                = strings.Join(scheduleInteractionLinkFieldNames, ",")
	scheduleInteractionLinkRowsExpectAutoSet   = strings.Join(stringx.Remove(scheduleInteractionLinkFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	scheduleInteractionLinkRowsWithPlaceHolder = strings.Join(stringx.Remove(scheduleInteractionLinkFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	scheduleInteractionLinkModel interface {
		Insert(ctx context.Context, data *ScheduleInteractionLink) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*ScheduleInteractionLink, error)
		Update(ctx context.Context, data *ScheduleInteractionLink) error
		Delete(ctx context.Context, id int64) error
	}

	defaultScheduleInteractionLinkModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ScheduleInteractionLink struct {
		Id            int64     `db:"id"`
		ScheduleId    int64     `db:"schedule_id"`    // 督学排课ID
		InteractionId int64     `db:"interaction_id"` // 督学互动ID
		Status        int64     `db:"status"`         // 状态 1.有效 2.无效
		CreatedAt     time.Time `db:"created_at"`     // 添加时间
		UpdatedAt     time.Time `db:"updated_at"`     // 修改时间
	}
)

func newScheduleInteractionLinkModel(conn sqlx.SqlConn) *defaultScheduleInteractionLinkModel {
	return &defaultScheduleInteractionLinkModel{
		conn:  conn,
		table: "`supv_schedule_interaction_link`",
	}
}

func (m *defaultScheduleInteractionLinkModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultScheduleInteractionLinkModel) FindOne(ctx context.Context, id int64) (*ScheduleInteractionLink, error) {

	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", scheduleInteractionLinkRows, m.table)

	var resp ScheduleInteractionLink
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultScheduleInteractionLinkModel) Insert(ctx context.Context, data *ScheduleInteractionLink) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, scheduleInteractionLinkRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ScheduleId, data.InteractionId, data.Status)
	return ret, err
}

func (m *defaultScheduleInteractionLinkModel) Update(ctx context.Context, data *ScheduleInteractionLink) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, scheduleInteractionLinkRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.ScheduleId, data.InteractionId, data.Status, data.Id)
	return err
}

func (m *defaultScheduleInteractionLinkModel) TableName() string {
	return m.table
}
