// Code generated by goctl. DO NOT EDIT.

package supervisor

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	streamFieldNames          = builder.RawFieldNames(&Stream{})
	streamRows                = strings.Join(streamFieldNames, ",")
	streamRowsExpectAutoSet   = strings.Join(stringx.Remove(streamFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	streamRowsWithPlaceHolder = strings.Join(stringx.Remove(streamFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	streamModel interface {
		Insert(ctx context.Context, data *Stream) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Stream, error)
		Update(ctx context.Context, data *Stream) error
		Delete(ctx context.Context, id int64) error
	}

	defaultStreamModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Stream struct {
		Id             int64     `db:"id"`               // 主键 Id
		TeacherId      int64     `db:"teacher_id"`       // 讲师ID
		Title          string    `db:"title"`            // 直播标题
		RoomId         string    `db:"room_id"`          // 房间号
		PlaybackTaskId string    `db:"playback_task_id"` // 直播云端录制任务ID
		PlaybackUrl    string    `db:"playback_url"`     // 直播回放地址
		IsMute         int64     `db:"is_mute"`          // 是否禁言（1是，2否）
		StartTime      time.Time `db:"start_time"`       // 开播时间
		Status         int64     `db:"status"`           // 直播状态：1.待开始 2.进行中 3.结束
		CreatedAt      time.Time `db:"created_at"`       // 创建时间
		UpdatedAt      time.Time `db:"updated_at"`       // 更新时间
	}
)

func newStreamModel(conn sqlx.SqlConn) *defaultStreamModel {
	return &defaultStreamModel{
		conn:  conn,
		table: "`lv_stream`",
	}
}

func (m *defaultStreamModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultStreamModel) FindOne(ctx context.Context, id int64) (*Stream, error) {

	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", streamRows, m.table)

	var resp Stream
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultStreamModel) Insert(ctx context.Context, data *Stream) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, streamRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.TeacherId, data.Title, data.RoomId, data.PlaybackTaskId, data.PlaybackUrl, data.IsMute, data.StartTime, data.Status)
	return ret, err
}

func (m *defaultStreamModel) Update(ctx context.Context, data *Stream) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, streamRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.TeacherId, data.Title, data.RoomId, data.PlaybackTaskId, data.PlaybackUrl, data.IsMute, data.StartTime, data.Status, data.Id)
	return err
}

func (m *defaultStreamModel) TableName() string {
	return m.table
}
