// Code generated by goctl. DO NOT EDIT.

package supervisor

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	teacherFieldNames          = builder.RawFieldNames(&Teacher{})
	teacherRows                = strings.Join(teacherFieldNames, ",")
	teacherRowsExpectAutoSet   = strings.Join(stringx.Remove(teacherFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	teacherRowsWithPlaceHolder = strings.Join(stringx.Remove(teacherFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	teacherModel interface {
		Insert(ctx context.Context, data *Teacher) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Teacher, error)
		Update(ctx context.Context, data *Teacher) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTeacherModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Teacher struct {
		Id               int64     `db:"id"`                // 主键
		TeacherCode      string    `db:"teacher_code"`      // code
		TeacherName      string    `db:"teacher_name"`      // 名字
		TeacherNickname  string    `db:"teacher_nickname"`  // 昵称
		TeacherTone      string    `db:"teacher_tone"`      // 音色
		ToneModel        string    `db:"tone_model"`        // 音色模型
		TeacherIntroduce string    `db:"teacher_introduce"` // 介绍
		TeacherGif       string    `db:"teacher_gif"`       // 动图
		TeacherPng       string    `db:"teacher_png"`       // 静图
		CreatedAt        time.Time `db:"created_at"`        // 创建时间
		UpdatedAt        time.Time `db:"updated_at"`        // 更新时间
	}
)

func newTeacherModel(conn sqlx.SqlConn) *defaultTeacherModel {
	return &defaultTeacherModel{
		conn:  conn,
		table: "`ac_teacher`",
	}
}

func (m *defaultTeacherModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultTeacherModel) FindOne(ctx context.Context, id int64) (*Teacher, error) {

	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", teacherRows, m.table)

	var resp Teacher
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTeacherModel) Insert(ctx context.Context, data *Teacher) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, teacherRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.TeacherCode, data.TeacherName, data.TeacherNickname, data.TeacherTone, data.ToneModel, data.TeacherIntroduce, data.TeacherGif, data.TeacherPng)
	return ret, err
}

func (m *defaultTeacherModel) Update(ctx context.Context, data *Teacher) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, teacherRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.TeacherCode, data.TeacherName, data.TeacherNickname, data.TeacherTone, data.ToneModel, data.TeacherIntroduce, data.TeacherGif, data.TeacherPng, data.Id)
	return err
}

func (m *defaultTeacherModel) TableName() string {
	return m.table
}
