// Code generated by goctl. DO NOT EDIT.

package member

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userInfoFieldNames          = builder.RawFieldNames(&UserInfo{})
	userInfoRows                = strings.Join(userInfoFieldNames, ",")
	userInfoRowsExpectAutoSet   = strings.Join(stringx.Remove(userInfoFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userInfoRowsWithPlaceHolder = strings.Join(stringx.Remove(userInfoFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	userInfoModel interface {
		Insert(ctx context.Context, data *UserInfo) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*UserInfo, error)
		Update(ctx context.Context, data *UserInfo) error
		Delete(ctx context.Context, id int64) error
	}

	defaultUserInfoModel struct {
		conn  sqlx.SqlConn
		table string
	}

	UserInfo struct {
		Id               int64     `db:"id"`
		BaseUserId       int64     `db:"base_user_id"`       // 用户ID
		RoleType         int64     `db:"role_type"`          // 角色类型 1.家长 2.孩子
		Nickname         string    `db:"nickname"`           // 昵称
		Gender           int64     `db:"gender"`             // 性别 0.未知 1.男 2.女
		Grade            int64     `db:"grade"`              // 年级 10.学龄前 11.一年级 12.二年级 13.三年级 14.四年级 15.五年级 16.六年级 20.中小衔接 21.初一 22.初二 23.初三 31.高一 32.高二 33.高三 41.大学语文 42.中文专业 43.文学专家
		Province         int64     `db:"province"`           // 省
		City             int64     `db:"city"`               // 市
		InitAbilityScore int64     `db:"init_ability_score"` // 阅读理解初始得分
		IsInfoFinished   int64     `db:"is_info_finished"`   // 是否完善信息 1.未完善 2.已完善
		IsAssessment     int64     `db:"is_assessment"`      // 用户测评状态 1.未评测 2.已评测
		IsGuide          int64     `db:"is_guide"`           // 是否引导过 0.没有 1.有
		IsGuideTips      int64     `db:"is_guide_tips"`      // 引导卡片下方Tips是否展示过 0 没有 1 有
		UpdatedBy        int64     `db:"updated_by"`         // 编辑人ID
		CreatedAt        time.Time `db:"created_at"`         // 添加时间
		UpdatedAt        time.Time `db:"updated_at"`         // 修改时间
	}
)

func newUserInfoModel(conn sqlx.SqlConn) *defaultUserInfoModel {
	return &defaultUserInfoModel{
		conn:  conn,
		table: "`us_user_info`",
	}
}

func (m *defaultUserInfoModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUserInfoModel) FindOne(ctx context.Context, id int64) (*UserInfo, error) {

	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userInfoRows, m.table)

	var resp UserInfo
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserInfoModel) Insert(ctx context.Context, data *UserInfo) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, userInfoRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.BaseUserId, data.RoleType, data.Nickname, data.Gender, data.Grade, data.Province, data.City, data.InitAbilityScore, data.IsInfoFinished, data.IsAssessment, data.IsGuide, data.IsGuideTips, data.UpdatedBy)
	return ret, err
}

func (m *defaultUserInfoModel) Update(ctx context.Context, data *UserInfo) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userInfoRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.BaseUserId, data.RoleType, data.Nickname, data.Gender, data.Grade, data.Province, data.City, data.InitAbilityScore, data.IsInfoFinished, data.IsAssessment, data.IsGuide, data.IsGuideTips, data.UpdatedBy, data.Id)
	return err
}

func (m *defaultUserInfoModel) TableName() string {
	return m.table
}
