// Code generated by goctl. DO NOT EDIT.

package member

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userOpinionFieldNames          = builder.RawFieldNames(&UserOpinion{})
	userOpinionRows                = strings.Join(userOpinionFieldNames, ",")
	userOpinionRowsExpectAutoSet   = strings.Join(stringx.Remove(userOpinionFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userOpinionRowsWithPlaceHolder = strings.Join(stringx.Remove(userOpinionFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`delete_at`", "`delete_time`", "`deleted_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	userOpinionModel interface {
		Insert(ctx context.Context, data *UserOpinion) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*UserOpinion, error)
		Update(ctx context.Context, data *UserOpinion) error
		Delete(ctx context.Context, id int64) error
	}

	defaultUserOpinionModel struct {
		conn  sqlx.SqlConn
		table string
	}

	UserOpinion struct {
		Id        int64     `db:"id"`         // 主键
		UserId    int64     `db:"user_id"`    // 用户ID
		Urls      string    `db:"urls"`       // urls路径，“|” 分割，支持多个
		Comment   string    `db:"comment"`    // 意见
		Status    int64     `db:"status"`     // 0.新意见 1.已回复
		Reply     string    `db:"reply"`      // 回复信息
		CreatedAt time.Time `db:"created_at"` // 添加时间
		UpdatedAt time.Time `db:"updated_at"` // 修改时间
	}
)

func newUserOpinionModel(conn sqlx.SqlConn) *defaultUserOpinionModel {
	return &defaultUserOpinionModel{
		conn:  conn,
		table: "`us_user_opinion`",
	}
}

func (m *defaultUserOpinionModel) Delete(ctx context.Context, id int64) error {

	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUserOpinionModel) FindOne(ctx context.Context, id int64) (*UserOpinion, error) {

	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userOpinionRows, m.table)

	var resp UserOpinion
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserOpinionModel) Insert(ctx context.Context, data *UserOpinion) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, userOpinionRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.Urls, data.Comment, data.Status, data.Reply)
	return ret, err
}

func (m *defaultUserOpinionModel) Update(ctx context.Context, data *UserOpinion) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userOpinionRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserId, data.Urls, data.Comment, data.Status, data.Reply, data.Id)
	return err
}

func (m *defaultUserOpinionModel) TableName() string {
	return m.table
}
